### ISSUE TITLE
[Tooltip] Align with triggering div

### ISSUE THREAD

**Issue by Plondrein** [angular/components#10034]
#### Bug, feature request, or proposal:
Feature request

#### What is the expected behavior?
We can set tooltip position to top, bottom, left right - but when we got tooltip above div triggering it, we can't simply tell tooltip to align with start / end of triggering div
just like here - in section 'Positioning - Variants': https://hekigan.github.io/vue-directive-tooltip/

#### What is the use-case or motivation for changing an existing behavior?
I got long tooltip (position 'above') triggered by table cells, but the most left cell's tooltip is getting outside screen - it would be nice to still have it above cell, but it could align with triggering cell start

**Comment by benneq** [comment]
Tooltips within mat-table headers suffer really bad from this, because the whole column in the triggering div: https://stackblitz.com/edit/components-issue-e48ynr
As you can see, applying `matTooltip` to the `th` element looks extremely weird. Though the only option is to use an additional `span` tag within the `th`. But now the tooltip can't show when hovering the sort arrow.

**Comment by jelbourn** [comment]
Tracking via #22493
