### ISSUE TITLE
100% reproducible memory leak 

### ISSUE THREAD

**Issue by MarkJeoffery** [angular/components#10573]
#### Bug, feature request, or proposal:
Bug

#### What is the current behavior?
Any overlay control (menu, popup) if opened and closed enough times affects the performance of all the input boxes. As funny as it seems, it does!

#### What are the steps to reproduce?
Try material's website: https://material.angular.io 

1. Navigate to the "Form Controls -> Input" to load the input page
2. Navigate to "Navigation -> Menu"
3. Open and close the menu 150 times or more by clicking on the "Menu" button.
4. Navigate to the "Form Controls -> Input". (to see the issue better, try to repeat steps 2 to 4)
5- Try to type quickly in any of the input boxes and you will see it's typing slowly. Try to delete the text by holding the backspace key and you will see it's lagging. 

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
The latest stable version: 5.2.4
We even tried on 6.0.0-beta.4

**Comment by neil-justice** [comment]
@crisbeto Although #10160 was tagged with 5.2.4, it seems like it isn't actually in the 5.2.4 release.

I made a quick stackblitz to check it out which just prints out  the 5.2.4 `OverlayKeyboardDispatcher.ngOnDestroy()` method [here](https://stackblitz.com/edit/angular-qdzapq), which should have been changed as part of that PR ([link](https://github.com/angular/material2/blob/5.2.4/src/cdk/overlay/keyboard/overlay-keyboard-dispatcher.ts#L32))

**Comment by WizardPC** [comment]
Can be linked to : [https://stackblitz.com/edit/issue-error-message](https://stackblitz.com/edit/issue-error-message) ?

For one input with `formControlName`, at the first load i enter 4 times in the `getErrorMessage` function, and 6 times, each time i open or close the `mat-accordion`. All this, multiplied by the number of formControlName inside my HTML... 

It's seem independant from the number of validators (eg : Validators.required in TS or required in HTML).

Perhaps it's can be a performance issue, but if it's not linked to #10573 i will open another issue :+1:

**Comment by lnaie** [comment]
I'm using Augury to look at the component graph. So the menu is a child component. I see that every time the menu opens/shows, it creates a new object in the graph. 
How about fixing that?

**Comment by SudhakarSundar** [comment]
will there be any update on this issue, this is impacting applications developed using angular material, we are hit with a bad performance, the components not getting destroyed on route change.

**Comment by SudhakarSundar** [comment]
Looks like mat-form-field is causing the memory issue, and checking the form-field.ts I dont see how the components get destructed.

**Comment by gund** [comment]
It looks like the leak might be because of leaked rxjs subscription in `CdkConnectedOverlay._createOverlay()` method:
https://github.com/angular/components/blob/e512581a81aee546a23aa003898399a5068769b8/src/cdk/overlay/overlay-directives.ts#L284

I've checked the code of [`OverlayRef`](https://github.com/angular/components/blob/ee96e05e8251aa0b9757c4002119d0fccaba9057/src/cdk/overlay/overlay-ref.ts#L32) class and found that there are 2 streams involved - one is inner subject that is used to dispatch events from services (like [`OverlayKeyboardDispatcher`](https://github.com/angular/components/blob/5c51301b4a3c266cc700717b814f1db25528f649/src/cdk/overlay/keyboard/overlay-keyboard-dispatcher.ts#L27)) and another outer observable that subscribes internally to that subject and forwards events further:

https://github.com/angular/components/blob/ee96e05e8251aa0b9757c4002119d0fccaba9057/src/cdk/overlay/overlay-ref.ts#L48-L57

The problem with this is that those 2 observables are not connected and so despite the fact that inner subject is completed (cleaned up) in `OverlayRef.dispose()` method it's outer counterpart will remain subscribed and thus causing potential memory leaks.


_NOTE:_ This was discovered by the streaming dude in his [video course on CDK Overlays](https://www.youtube.com/watch?v=2pS9bYtsBRo) (it's just to give him credit).
