### ISSUE TITLE
mat-label and placeholder is hidden when there is floatLabel = "never" and floatPlaceholder="never"

### ISSUE THREAD

**Issue by missionraj** [angular/components#10770]
#### Bug, feature request, or proposal:
when the page is loaded  for the  first   time the matlabel or placeholder is hidden 
but when ever page is reloaded the mat labels seems  to appear
 
#### What is the expected behavior?
it sholud display themat-labels on the first time

#### What are the steps to reproduce?
Providing a StackBlitz reproduction is the *best* way to share your issue. <br/>
StackBlitz starter: https://goo.gl/wwnhMV<br/>

**Comment by mmalerba** [comment]
It does hide the placeholder for the legacy version of the form-field (this is WAI because the legacy one didn't really differentiate between label and placeholder).

For the newer variants `floatLabel="never"` is not a supported option, they ignore it and show the placeholder

https://stackblitz.com/edit/components-issue-it47ul?file=src%2Fapp%2Fexample-component.html
