### ISSUE TITLE
Broken link fragment in documentation

### ISSUE THREAD

**Issue by VagrantAI-c** [angular/components#11473]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Anchor links ("link to the heading") should lead to the corresponding heading in all cases

#### What is the current behavior?
Currently some cases not triggering scroll to the specified article, e.g. 
_Responding to changes in the autofill state of an `<input>`_:
https://material.angular.io/components/input/overview#responding-to-changes-in-the-autofill-state-of-an-code-lt-input-gt-code-
_`Utilities` link in same part_:
https://material.angular.io/components/input/overview#monitoring-the-autofill-state-of-an-input

Moreover, links might not lead to their designated anchor for the first time, if they are opened via `Open link in new tab` context menu item while already being on documentation site.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular Material 6.1.0
Chrome 66

**Comment by walvekarnikhil** [comment]
In [Responding to changes in the autofill state of an](https://material.angular.io/components/input/overview#responding-to-changes-in-the-autofill-state-of-an-input) section link for utilities is https://material.angular.io/cdk/text-field/overview#monitoring-the-autofill-state-of-an-code-lt-input-gt-code- 
But as per the Text-field documentation, it should be https://material.angular.io/cdk/text-field/overview#monitoring-the-autofill-state-of-an-input

This was done as part of
https://github.com/angular/components/commit/920f32e6fcbbcebfa2a538ff8f6620a8c44315a7

Seems like those links were auto-generated. The text is "**Monitoring the autofill state of an <input>**" and generated link is **monitoring-the-autofill-state-of-an-code-lt-input-gt-code- **

In the above fragment **code-lt** & **gt-code** is due to 
```
<code><input></code>
```
Since this is my first time to contribute to Angular Material, few questions:
Do we auto-generate such files?
Can we modify the file to point to proper links?
