### ISSUE TITLE
baseline for label doesn't match placeholder (on 2 of 3 appearances)

### ISSUE THREAD

**Issue by hblieb** [angular/components#12047]
#### Bug, feature request, or proposal:
BUG

#### What is the expected behavior?
baseline for a label should match baseline for placeholder

#### What is the current behavior?
baseline for a label is higher than baseline for a placeholder when appearance is outline or fill. Looks good when baseline is standard.

#### What are the steps to reproduce?
Providing a StackBlitz reproduction is the *best* way to share your issue. <br/>

https://stackblitz.com/edit/angular-material2-issue-pgo76x

#### What is the use-case or motivation for changing an existing behavior?
Side-by-side text fields should look consistent

**Comment by mmalerba** [comment]
This is because the text is aligned with the inputted value rather than the label (try typing in the field and see). The baseline of the label and the inputted text are not the same, [as the spec shows](), but the spec also gives no guidance that I can find on how to deal with this alignment issue. I'll mark this as blocked pending discussion with the Material Design team

**Comment by crisbeto** [comment]
Closing since this is referring to the legacy version of the component that has been removed.
