### ISSUE TITLE
fix(mat-datepicker): button ripple radius

### ISSUE THREAD

**Issue by vladimir-barsuchenko** [angular/components#12227]
#### Bug:
After switching from **Month view** to **Year view**, ripple doesn't take all of the width of the button. 
Since year notation contains more characters, a width of the button is larger than the month notation equivalent. Plus seems like since button width is different, velocity of the ripple to fill the whole button is different as well.

#### What is the expected behavior?
Ripple to take fullwidth of the button.

#### What is the current behavior?
![datepicker-ripple](https://user-images.githubusercontent.com/10091564/42751779-7e430dba-88f4-11e8-974f-da636ddcbde5.gif)

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Material: **v.6.3.3**

**Comment by DevVersion** [comment]
Thinking about it in regards to the ripples. I'm not sure if that's something we need to address in the ripple implementation. There would be definitely some way to make the ripples always expand to the _current_ boundaries, but it might turn into a breaking change, performance impacts etc.

Maybe we could instead just have a minimum width for the datepicker button that avoids a change in boundaries.

**Comment by devversion** [comment]
Closing this one as we cannot fix this. The ripple starts on mousedown, and then mid-animation the button changes its dimensions. We could expand to the full dimensions mid-animation with negative impact in performance, but then there would be the complexity of managing velocity of the ripple when it was already slower before (due to the smaller & old dimensions).
