### ISSUE TITLE
Feature request: Enable/Disable label in calendar-body

### ISSUE THREAD

**Issue by lordgit** [angular/components#12612]
#### Bug, feature request, or proposal:
feature request

Disable label in calendar-body.html

Line 5: <tr *ngIf="_firstRowOffset < labelMinRequiredCells"
Line 22: <td *ngIf="rowIndex === 0 && _firstRowOffset"

#### What is the expected behavior?
default enable, but could be disabled visibility.

#### What is the current behavior?
is alway visible

#### What are the steps to reproduce?
Providing a StackBlitz reproduction is the *best* way to share your issue. <br/>
StackBlitz starter: https://goo.gl/wwnhMV<br/>

#### What is the use-case or motivation for changing an existing behavior?
We need this for customer request, wouldn't have label there

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Anguarl 6.0.8, Material  6.4.2

**Comment by josephperrott** [comment]
You should be able to control the visibility of the label via css targeting the `mat-calendar-body-label` class.

**Comment by timruhle** [comment]
I would like this feature as well, or at least some guidance for the css. Here are the things I can achieve, neither or which are quite right.


As you can see in this example the first row doesn't align properly
```css
.mat-calendar-body-label {
    display: none;
}
```
![image](https://user-images.githubusercontent.com/28910600/57111340-1c9f8000-6d7f-11e9-99fe-d2f82ab3da98.png)

As you can see in this example there is a row of white space which I don't want
```css
.mat-calendar-body-label {
    visibility: hidden;
}
```
![image](https://user-images.githubusercontent.com/28910600/57111373-33de6d80-6d7f-11e9-89fb-7a4a34fdba4b.png)

**Comment by mihdemarko** [comment]
> I would like this feature as well, or at least some guidance for the css. Here are the things I can achieve, neither or which are quite right.
> 
> As you can see in this example the first row doesn't align properly
> 
> ```css
> .mat-calendar-body-label {
>     display: none;
> }
> ```
> ``

Hi, you should be more specific using css selectors.
.mat-calendar-body-label also creates free space in the beginning of calendar. Try this workaround:
`[aria-hidden=true] .mat-calendar-body-label {
    display: none;
}`
This is for whole line label. And:
`td.mat-calendar-body-label {
    visibility: hidden;
}`
This for partial line label.

**Comment by x1c0** [comment]
@mihdemarko unfortunately this is not enough since only using css to hide stuff is not taking in consideration when the height is calculated.. look how it looks here:
![image](https://user-images.githubusercontent.com/2421483/75434704-42bb8f80-5952-11ea-9837-57bc0819f79f.png)

cool would be some input where we could hide the body

**Comment by Totati** [comment]
.mat-calendar-body-label:not(:last-of-type) {
    visibility: hidden;
}
.mat-calendar-body-label:last-of-type {
    display: none;
}

**Comment by x1c0** [comment]
Sure I understand that, since my intention is to remove 1 row of the table then it would be nice that, that change was taken into consideration when calculating the height (and this cannot be achieved by CSS only)

here I have a 6 rows month (the bigger possible) and still there is this last unnecessary table row:

![image](https://user-images.githubusercontent.com/2421483/75524703-b7540400-5a0e-11ea-9126-617deec37caf.png)

**Comment by Totati** [comment]
Now I understand your problem.  You have to override [this](https://github.com/angular/components/blob/c7c02072d100800ddb573ef2a52337dc85ca8f2f/src/material/datepicker/datepicker-content.scss#L7) value. Since it's a scss variable, but it's not a default one, you can't override it. You have to calculate your calendar height by hand like they did, and add a selector to your calendar like this:
`.mat-datepicker-content .mat-calendar {
    height: 300px;
}`

**Comment by duxor** [comment]
You can try something like this (works for me - I have a custom dialog):
```
.datepicker-dialog { // custom class
    max-width: 700px !important;
    width: 100vw;
    position: absolute !important;

    .mat-calendar {
        width: 100vw;
        max-width: 100%;
        height: 100vw;
        max-height: 700px;
    }
}
```

**Comment by andrewseguin** [comment]
Sounds like this issue has been resolved using style overrides

**Comment by RkSabando** [comment]
> Now I understand your problem. You have to override [this](https://github.com/angular/components/blob/c7c02072d100800ddb573ef2a52337dc85ca8f2f/src/material/datepicker/datepicker-content.scss#L7) value. Since it's a scss variable, but it's not a default one, you can't override it. You have to calculate your calendar height by hand like they did, and add a selector to your calendar like this:
> `.mat-datepicker-content .mat-calendar { height: 300px; }`

use height:auto !important; instead
