### ISSUE TITLE
FocusMonitor on MatButton and MatTooltip triggers repaints and kills performace on the page

### ISSUE THREAD

**Issue by c69** [angular/components#12722]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Keydown events should not cause any observable slowdown, especially if they are outside of respective controls. 

#### What is the current behavior?
We have a page with around 200 material controls, it works ok. When I scroll with mouse, touchpad or scrollbar - scrolling is smooth (and no repaints happen in Chrome Performance chart).
If I try to scroll with arrow keys OR type in any input OR just randomly press any key (e.g. "A") - performance goes down (and ugly violet repaints dominate the Chrom Performace chart) 

#### What are the steps to reproduce?
Open my non public application</sarcasm>

#### What is the use-case or motivation for changing an existing behavior?
Lol.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 6.1.1, TS 2.9.2, Material UI 6.4.2, Windows 7, Chrome 68.

#### Is there anything else we should know?
FocusMonitor installs global event listener for 'keydown' event. It appears that this only applies to MatTooltip and MatButton, not MatInput.

**Comment by c69** [comment]
'performaNce' of course. Sorry for typo in title.

**Comment by DevVersion** [comment]
@mmalerba I don't think we can do anything about that right? Checking if a `keydown/start` event affects a monitored element is not possible because the keyboard event is not guaranteed to always happen on the target element.

If we _could_ check if the event affects a monitored element, we then could avoid setting up a `timeout` if the keyboard event is not affecting anything (e.g. down-keys for scrolling page)

https://github.com/angular/material2/blob/992bcfb1799c3342de33153e5de7e404821a1e2e/src/cdk/a11y/focus-monitor/focus-monitor.ts#L306-L314

**Comment by mmalerba** [comment]
Hmm I don't see why that keydown listener or setTimeout would be causing repaints though. Maybe if its actually changing the classes on elements, but if the events turn out to be on elements that aren't monitored I wouldn't expect a repaint. May need some more investigation

> Open my non public application

@c69 How about a stackblitz instead?

**Comment by wagnermaciel** [comment]
Closing because this issue has been inactive for 2 weeks or more after follow up was requested.
