### ISSUE TITLE
mat-card-actions has inconsistent spacing

### ISSUE THREAD

**Issue by kyletanders** [angular/components#13382]
#### Bug, feature request, or proposal:
Button spacing in mat-card-actions is different between the 1st and 2nd button and the 2nd and 3rd button.
![image](https://user-images.githubusercontent.com/38547705/46312492-75593100-c582-11e8-9fb6-5119f9234af7.png)

#### What is the expected behavior?
Spacing should be consistent.

#### What is the current behavior?
Spacing is not consistent

#### What are the steps to reproduce?
https://stackblitz.com/edit/angular-fjkrkb

Look at spacing between the buttons in mat-card-actions and see that they are not the same

#### What is the use-case or motivation for changing an existing behavior?
Seems like a bug

**Comment by crisbeto** [comment]
I think the reason for the negative margin is to prevent the actions' margin from overlapping with the card's padding.

**Comment by Totati** [comment]
Since the latest release selectors should be change to .mat-button-base, I had a [issue](https://github.com/angular/components/issues/16762) as .mat-flat-button and .mat-stroked-button are absolutely ignored in .mat-card-actions and .mat-dialog-actions. The part with the dialog has been fixed, but with the card hasn't, but I can't reopen it.

**Comment by crisbeto** [comment]
I've updated #13390 to use `.mat-button-base`.

**Comment by amysorto** [comment]
The new MDC based card component coming soon in v15 does not have any padding between the buttons anymore so this will be not applicable anymore.
