### ISSUE TITLE
Provide CSS that sizes all elements of demos.

### ISSUE THREAD

**Issue by briangmilnes** [angular/components#13718]
#### Bug, feature request, or proposal:
Feature: it's difficult to see which CSS directives will allow the resizing of the material2 component.
In each example, adjust the mostly empty CSS files to show how to resize the components.

#### What is the expected behavior?
New user confusion about changing element size. Look at stacktrace to see
lots of I tried this and it didn't work questions all with different answers also
not clearly bound to versions/revisions of material2.

#### What is the current behavior?
New user wasted time and confusion trying CSS changes.

#### What are the steps to reproduce?
Providing a StackBlitz reproduction is the *best* way to share your issue. <br/>
StackBlitz starter: https://goo.gl/wwnhMV<br/>

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
All.

**Comment by crisbeto** [comment]
Usually the Material components are set up to be `display: block` and `display: inline-block` and you can resize them by resizing the container. I don't think that it would be practical to document this for every single component in the library, because it is bound to go out of sync as we change the CSS of the components.
