### ISSUE TITLE
Virtual Scrolling in mat-table

### ISSUE THREAD

**Issue by KlausEvenEnevoldsen** [angular/components#13767]
#### Bug, feature request, or proposal:

Feature request

#### What is the expected behavior?

Faster initialization and scrolling inside mat-table

#### What is the current behavior?

With mat-table using MatTableDataSource it does not support virtual scroll

#### What are the steps to reproduce?

n/a

#### What is the use-case or motivation for changing an existing behavior?

We have two long lists side by side, with the possibility of dragging from one list to the other. The performance is very slow because Change Detection is running on the full lists, when only the items that are visible in each list should be subject to the Change Detection.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

Latest

#### Is there anything else we should know?

We love Angular and Material Design 👍

**Comment by manavalan** [comment]
Mat-table available with this feature ?

https://datatables.net/extensions/scroller/examples/initialisation/server-side_processing.html

**Comment by Splaktar** [comment]
@manavalan this issue is closed. If you have a question about how to implement a certain feature using `mat-table`, please post to the [forums](https://groups.google.com/forum/?pli=1#!forum/angular-material2). Otherwise discussion of virtual scrolling with `mat-table` is taking place in https://github.com/angular/components/issues/10122.

If you have a feature request, please open a new issue.
