### ISSUE TITLE
Slider Thumb not updating in Ionic 4 based app

### ISSUE THREAD

**Issue by chrisgriffith** [angular/components#13797]
#### Bug, feature request, or proposal:
Slider thumbnail is not updating when used within an Ionic 4 application

#### What is the expected behavior?
The thumbnail's position updates while the user drags.

#### What is the current behavior?
The slider renders correctly within the Ionic app, the only issue is that the thumb does not update it's position while dragging. Upon release, the thumb animates to the proper position.

#### What are the steps to reproduce?
Providing a StackBlitz reproduction is the *best* way to share your issue. <br/>
StackBlitz starter: https://goo.gl/wwnhMV<br/>

#### What is the use-case or motivation for changing an existing behavior?
The material component supports vertical sliders, while the Ionic slider does not.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 6.1.1
Material 6.4.7
TypeScript 2.9.2

**Comment by jelbourn** [comment]
Without a reproduction we likely won't be able to do anything about this.

**Comment by chrisgriffith** [comment]
Will work on a sample repo. Have to check the status of Ionic's Stackblitz integration.

**Comment by chrisgriffith** [comment]
https://github.com/chrisgriffith/ionic-angular-material
Was unable to get a StackBlitz instance working.
Included the two other components that rely on HammerJS. The SlideToggle exhibits the same issue. I do not see anything with the tooltip

**Comment by wagnermaciel** [comment]
I tried to get the example running but wasn't able to. I'm a bit confused by it because it seems like it's attempting to bind to a `press` output which I don't think ever existed, and it also uses a function `onPress` in the template which doesn't seem to be defined anywhere

@chrisgriffith I created a new ionic app using the MDC slider and it seems to be working correctly now. If you are able to reproduce the issue with the latest version of the slider, please file a new bug and feel free to at-mention me on it 👍🏽
