### ISSUE TITLE
Keyboard input for chips with input gives unintuitive focus

### ISSUE THREAD

**Issue by Mark-Hetherington** [angular/components#13822]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
When a Chip is focused within a chip list, any keystrokes should return focus to the input to start a new chip. If the user presses "right" from the rightmost chip, focus should move to the input. If the user presses "left" from the start of the input, focus should move to the chip.

#### What is the current behavior?
The user needs to use "shift+tab" to get from the input to the chips, and tab to move from the chips to the input.

#### What are the steps to reproduce?
1. Open stackblitz of official demo:
https://stackblitz.com/angular/gxkenpgblbd?file=app%2Fchips-input-example.ts

2. Set focus in the input (e.g. click in input)

3. Press left arrow key -> desired behaviour is "Lemon" chip is focused, current behaviour is input remains focused.

4. Focus "Lemon" chip (e.g. Click on chip, or press shift+tab)

5. Type characters (e.g. "Straw") -> desired behaviour is autocomplete is triggered, and typed characters are placed into input, current behaviour is no change in UI.

6. Press Right -> desired behaviour is to move focus to input. 

#### What is the use-case or motivation for changing an existing behavior?
The current behaviour does not allow for intuitive movement of focus using the arrow keys.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular/Material >=6

**Comment by iget-esoares** [comment]
I agree with your complain, and want to increment it:

When the chips are updated, the focused chip is reseted, and tihs is not intuitive.

Example:

I have an application that when I click on a chip, this chip will be removed and it value carried to the MatChipInput value, so I can edit it.

When I have just one chip, it works fine since theres no chips to gain focus.

But, when I have two or more chips, it will remove the focus from the input (setted by me using the `focus` method) and give the focus to the last chip.

I didn't found any way to solve it other then using a timeout to set focus on next digest cycle.

**Comment by crisbeto** [comment]
We're in the process of cleaning up our issue backlog. I'm closing this issue, because I don't think it's the right thing to do. Many users who are using the keyboard to navigate have no idea where the input is in relation to the chips and will likely be confused if focus moves from a chip to the input while using the arrow keys.
