### ISSUE TITLE
cdkStepper error

### ISSUE THREAD

**Issue by brackio** [angular/components#13928]
#### Bug, feature request, or proposal:
Bug 

#### What is the current behavior?

Error message when using cdkStepper. 

ERROR TypeError: Cannot read property '0' of undefined
    at FocusKeyManager.push../node_modules/@angular/cdk/esm5/a11y.es5.js.ListKeyManager.updateActiveItem

#### What are the steps to reproduce?

    <div cdkStepper>
       <cdk-step label="Step 1" [stepControl]="someformGroup">
        <button cdkStepperPrevious mat-button color="primary">Previous</button>
        <button cdkStepperNext mat-button color="primary">Next</button>
       </cdk-step>
    </div>

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

@angular/material 7.0.2
@angular/cdk 7.0.2

**Comment by crisbeto** [comment]
I couldn't reproduce the issue based off of the code snippet above. Can you provide a more complete example?

**Comment by josephperrott** [comment]
Can you provide a reproduction in [StackBlitz]( https://goo.gl/wwnhMV).  This will help us to investigate the issue you are seeing.

**Comment by crisbeto** [comment]
@brackio your example seems to be on Material `6.0.0-beta.7`. I can't reproduce it against 7.0.

**Comment by brackio** [comment]
How about this one? I updated the packages.

https://stackblitz.com/edit/angular-2dobc6

**Comment by crisbeto** [comment]
I can definitely see the error in the Stackblitz, but I'm having a hard time reproducing it in our dev app. [The error comes from the ngAfterViewInit hook](https://github.com/angular/material2/blob/master/src/cdk/stepper/stepper.ts#L313) where the `_stepHeader` is undefined for some reason. This shouldn't be possible, because Angular defines it as a `QueryList` even if no elements match the query. The only case where it could be undefined is if we were checking it too early, however we're doing it in `ngAfterViewInit` which comes after `ngAfterContentInit` which is where the `_stepHeader` would be available.

**Comment by tobang** [comment]
I think this is related to #10614

**Comment by devversion** [comment]
I updated the StackBlitz to the latest version and this error no longer shows up. I also updated the StackBlitz to actually render the selected tab. Works as expected.

https://stackblitz.com/edit/angular-2dobc6?file=src%2Fapp%2Fapp.component.html
