### ISSUE TITLE
Inconsistent checkbox styles

### ISSUE THREAD

**Issue by tinybigideas** [angular/components#13945]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Consistent checkbox style

#### What is the current behavior?

`mat-checkbox`
![image](https://user-images.githubusercontent.com/2805752/47926266-17d53e80-deb8-11e8-8b6e-d3e86b99325e.png)

`mat-tree`
![image](https://user-images.githubusercontent.com/2805752/47926084-9ed5e700-deb7-11e8-94f5-1a46d34342b5.png)

`mat-selection-list`
![image](https://user-images.githubusercontent.com/2805752/47926148-c3ca5a00-deb7-11e8-9b1a-e59903e062b6.png)

`mat-selection-list` checkbox styles are slightly inconsistent. Only obvious when side by side with another source.

#### What are the steps to reproduce?
See:
https://material.angular.io/components/checkbox/overview
vs
https://material.angular.io/components/list/overview#selection-lists

#### What is the use-case or motivation for changing an existing behavior?
Consistency

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 7, Material 7, Linux, Chrome/Firefox

#### Is there anything else we should know?
Nope. Super low priority, but worth mentioning.

**Comment by crisbeto** [comment]
The reason is that we have two checkboxes: `mat-checkbox` that comes with all the behavior, animations, accessibility etc. and `mat-pseudo-checkbox` which is CSS-only and intended only for presentation. After we reduced the sizes of checkbox, they ended up rendering slightly differently, because one uses SVG and the other one is pure CSS.

**Comment by thomas-parrish** [comment]
But both checkboxes are used in forms, and when they are used within the same form, it's extremely noticeable. Also, pseudo-checkboxes do not support the necessary features that would allow us to replace actual checkboxes with them (such as indeterminate state.) In our case, we have a multi-select with a select all feature, and it looks ridiculous now because of this change. 

![select](https://user-images.githubusercontent.com/8125983/48510050-c8c8cb00-e820-11e8-85de-75161cf0b5fe.png)

**Comment by Angelinsky7** [comment]
i've got the same effect as @thomas-parrish but in a simple mat-selection-list without doing nothing special
