### ISSUE TITLE
Chips Autocomplete cant be disabled (both input and chips)

### ISSUE THREAD

**Issue by cnotv** [angular/components#14036]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Setting control to disabled should disable both input and chips.

#### What is the current behavior?
Nothing changes even if the formControl is set to disabled.

#### What are the steps to reproduce?
Open the pen ad try to toggle the disable status, you'll get a boolean value in the log.
- [Pen created using markup from the documentation](https://stackblitz.com/edit/angular-autocomplete-chip-doesnt-disable?file=app/chips-autocomplete-example.ts)
- Chip with autocomplete [Doc]( https://material.angular.io/components/chips/examples) [Pen](https://run.stackblitz.com/api/angular/v1?file=app%2Fchips-autocomplete-example.ts)
- Autocomplete with disable toggle [Doc](https://material.angular.io/components/autocomplete/examples) [Pen](https://run.stackblitz.com/api/angular/v1?file=app%2Fautocomplete-overview-example.ts)

#### What is the use-case or motivation for changing an existing behavior?
Every provided input from the library must have a disabled case.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Same version as documentation.
7.0.3/7.0.2

#### Is there anything else we should know?
The component should propagate the disable status to the chips, [using existing API](https://material.angular.io/components/chips/api#MatChip), and dropdown as restriction set by Angular library.

**Comment by zxlee618** [comment]
Hi, is anyone working on this? I am thinking to take on this as my first contribution. 😀

**Comment by jelbourn** [comment]
Feel free to send a PR!

**Comment by zxlee618** [comment]
Should we put a formControl at the input? Shouldn't it be set at mat-chip-list level?

**Comment by jelbourn** [comment]
@zxlee618 I don't quite understand your question

**Comment by jelbourn** [comment]
I'm not sure we'd want to encourage making the chip-list a form control. While it's currently implemented as `role="listbox"`, we have an item in our backlog to change it to `role="grid"`, which isn't a form control.

**Comment by zxlee618** [comment]
Hmm.. well `MatChipList` implements `MatFormFieldControl` at the moment. Sound like we might need to redesign the whole thing?

**Comment by jelbourn** [comment]
Yeah, that seems like something we'd have to work into the switch over to `role="grid"`

**Comment by jelbourn** [comment]
Having the chip-list be aware of the form control on its associated input is an area to explore

**Comment by Aleksandyr** [comment]
Hello @jelbourn I have a fix for the issue, but firstly we have to clarify a few things.
As I observed in the API documentation you don't have exposed that [MatChipList](https://material.angular.io/components/chips/api) has a disabled input property which disables all chips that the list contains. So the questions here is do we need to keep that [input setter](https://github.com/angular/material2/blob/master/src/lib/chips/chip-list.ts#L268) or we can remove it?
Second one is:
You have specified above in the conversation:
    **I'm not sure we'd want to encourage making the chip-list a form control. While it's currently 
       implemented as `role="listbox"`, we have an item in our backlog to change it to `role="grid"`, which 
       isn't a form control.**
This means that [here](https://github.com/angular/material2/blob/master/src/lib/chips/chip-list.ts#L267) there is no need for that clause:
```typescript
this.ngControl ? !!this.ngControl.disabled
```
Which leads to the other question:
Do we need to implement [here](https://github.com/angular/material2/blob/master/src/lib/chips/chip-list.ts#L104) **ControlValueAccessor** interface at all?

The last question is:
If we won't need disabled input property into MatChipList. We won't need [this ](https://github.com/angular/material2/blob/master/src/lib/chips/chip-input.ts#L90) clause here at all.
```typescrtip
(this._chipList && this._chipList.disabled);
```

After we clear the ambiguities I would be able to provide the fix for the issue.

**Comment by Rlcolli4** [comment]
Is there any update on this issue? We are using MatChipList in our form as well with the input as a form control. We have to set the disabled property manually because the input ignores the formControls enabled/disabled properties. As a result we get this warning, we would like to get rid of it but it looks like until this stuff is changed we won't be able to get rid of it:
`It looks like you're using the disabled attribute with a reactive form directive. If you set disabled to true
      when you set up this control in your component class, the disabled attribute will actually be set in the DOM for
      you. We recommend using this approach to avoid 'changed after checked' errors`

**Comment by vishnu-dev** [comment]
@jelbourn Will we get any updates on this?

**Comment by ianmantripp** [comment]
I'm late to the party but as this is still "open", I'll post my working code.

I have a component (AutoChipsComponent) which is basically the same as the example with a few changes. In my application I have a whole bunch of instances of this component which are enabled/disabled depending on the values of other instances.
I add a "disabled" input to the mat-chip-list:

auto-chips.component.html
```
<mat-form-field fxFlex (focusout)="focusOut($event)">
  <mat-chip-list #chipList [disabled]="disabled">
    <mat-chip
      class="my-chip"
      *ngFor="let item of selectedItems"
      ...
```
auto-chips.component.ts
```
@Input() disabled: boolean;
```

In the parent component one instance is:
module-edit.component.html
```
<app-auto-chips
  #profilesSelector
  placeholder="Select Profile(s)"
  [items]=profiles
  [controller]=profilesCtrl
  [disabled]=true
>
</app-auto-chips>
```

and module-edit.component.ts
```
 @ViewChild('shoptypesSelector') shoptypesSelector: AutoChipsComponent;
...
setDisabled(state: boolean) {
    this.shoptypesSelector.disabled = state;
    this.profilesSelector.disabled = state;
  }
```

This works as expected, so in this example the status of "Shoptype" and "Profile" depend on the presence of "Sales" in "Departments".

![Screenshot Sep 29 12 44 35](https://user-images.githubusercontent.com/1322133/94549004-d7bc9900-0251-11eb-87d8-20aca6ee9422.png)

![Screenshot Sep 29 12 44 47](https://user-images.githubusercontent.com/1322133/94549024-ddb27a00-0251-11eb-9a9a-494f5998e5b6.png)

**Comment by ankurdeal** [comment]
Is there any plan for this?

**Comment by Krun-al** [comment]
input tag within mat chip do this
add -> [disabled]="condition"
update -> matInput to matChipInput

This one worked for me

**Comment by zarend** [comment]
This issue has been fixed in the newer, MDC-based components. Install v15 to get access to them.

`MatChipGrid` has an `@Input disabled`, which allows the developer to disable the entire input and associated chips.
