### ISSUE TITLE
Datepicker: scroll page enable on iOS

### ISSUE THREAD

**Issue by laurent1** [angular/components#14938]
When the Datepicker is open on iOS devices with Safari, users can still scroll the web page. This behavior is not permitted on other browsers for desktops and android devices.

It seems that the CSS property pointer-events used on the element with the class cdk-overlay-backdrop is not working in this environment.

I am using Angular 7 and it has been behaving this way since I have been using that feature a year ago. So, this is not version related.

**Comment by mmalerba** [comment]
`pointer-events` _should_ be supported on mobile Safari: https://caniuse.com/#feat=pointer-events, will need to look further into it

**Comment by devversion** [comment]
Hello @laurent1! I tried this with iOS 13 w/ Safari 13 and it looks like with an open datepicker the only visible scroll was due to the iOS scroll bouncing/elastic scroll. Is that what you are referring to, or do you see cases where the full page can be scrolled (i.e. also actual content and it persists scroll position)

**Comment by devversion** [comment]
Closing as it seems to be working as expected on my end. Please let me know if you have more information. happy to re-open! thanks!
