### ISSUE TITLE
mat-select: Possibility to set height of mat-select-panel

### ISSUE THREAD

**Issue by flemgs** [angular/components#15192]
#### Please describe the feature you would like to request.
Possibility to have a mat-select panel that could expand till reaching top and bottom borders of the viewport before displaying scrollbar, when there is enough mat-option inside. In Material 7.3.2 mat-select panel height is limited to 256px. It would be nice to provide a way to override this value.
 
#### What is the use-case or motivation for this proposal?
Displaying more list items at once so the user can select the one he wants without having to scroll.

**Comment by flemgs** [comment]
Any update on this ? Does anyone know an alternative to the use of mat-select to display a drop down list ?

**Comment by andrewseguin** [comment]
Here's an example of overriding the max-height using CSS, but unfortunately there doesn't seem to be a great way to make sure the height goes past the viewport without dynamic computations

https://stackblitz.com/edit/angular-vs8nco?file=app/select-overview-example.css

**Comment by JanNadrasky** [comment]
> Here's an example of overriding the max-height using CSS, but unfortunately there doesn't seem to be a great way to make sure the height goes past the viewport without dynamic computations
> 
> https://stackblitz.com/edit/angular-vs8nco?file=app/select-overview-example.css

Hi, it works cool. If you want to have it responsive, for me the vh and vw instead of px work fine.

**Comment by ThomazAquino** [comment]
Same problem here. Just override the panel class with ::ng-deep could be a problem if you have enough options to go out of the viewport.

**Comment by jonnytest1** [comment]
with this approach if the size is too big for the viewport the position of the dropdown behaves odd even positioning different depending on wether or not one of the first 2 items is selected

**Comment by amysorto** [comment]
In the new MDC based components coming soon in v15, you can change the height by overriding the CSS as mentioned above. Except now the rule selector would look like this in your styles: `::ng-deep .mdc-menu-surface.mat-mdc-select-panel.your-panel-class-name`. [The default height max height now defaults to 275px](https://github.com/angular/components/blob/main/src/material/select/select.scss#L10).

In terms of having the panel be full height of the viewport, it's not something we will support since the height is customizable and it would be a small use case to add extra checks for. One thing to note for adding long panels in your app, [the material spec suggests leaving enough room at the bottom for another row](https://m2.material.io/components/menus).
