### ISSUE TITLE
Backdrop stays open after navigate using routerlink from inside mat dialog

### ISSUE THREAD

**Issue by eyalhakim** [angular/components#15248]
#### What is the expected behavior?
When clicking an element with the `routerLink` directive, the navigation should close the dialog and make the backdrop disappear

#### What is the current behavior?
The dialog closes but the backdrop stays open.
Doesn't work even with `closeOnNavigation: true` or with applying `mat-dialog-close` to the element that has the `routerLink` directive

#### What are the steps to reproduce?
Providing a StackBlitz reproduction is the *best* way to share your issue. <br/>
StackBlitz starter: https://goo.gl/wwnhMV<br/>
Have an <a> element with a routerLink directive inside a mat dialog template and click on it to navigate.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular Core: 7.2.5
Angular Material: 7.3.2

**Comment by josephperrott** [comment]
Can you provide a reproduction in [StackBlitz](https://stackblitz.com/fork/components-issue).  This will help us to investigate the issue you are seeing.

**Comment by goelinsights** [comment]
I ran into this and found that the issue was that the dialogRef wasn't triggering ngOnDestroy when it moved to the new route.

Found something that seems to work  - I wrapped the routerLink in an <a> tag
From within the dialog:
`<button mat-button [routerLink]="'newRoute'">GO SOMEWHERE</button>`
To
`<a [routerLink]="'newRoute'"><button mat-button >GO SOMEWHERE</button></a>`

Early finding is that it seems to trigger a cleanup of the old components and creation of a new route tree - will add more if I see anything different.

**Comment by flensrocker** [comment]
reproduce: https://angular-h4uz66.stackblitz.io

**Comment by flensrocker** [comment]
Any news on this?

My current workaround:
```
private _dialogRef: MatDialogRef<ModalComponent> = null;

openDialog() {
    this._dialogRef = this._dialog.open(ModalComponent);
    this._dialogRef.afterClosed().subscribe(() => this._dialogRef = null);
}

ngOnDestroy() {
    if (this._dialogRef) {
        this._dialogRef.close();
    }
}
```

**Comment by wagnermaciel** [comment]
Closing because this issue has been inactive for 2 weeks or more after follow up was requested.
