### ISSUE TITLE
[Virtual scrolling] Introduce immutable.js as a valid input for iteration

### ISSUE THREAD

**Issue by adarowiec** [angular/components#15398]
#### Please describe the feature you would like to request.

Maybe I'm mistaken but there is no way to get immutable.js List working in cdkVirtualFor directive. With a regular ngFor it actually works.

#### What is the use-case or motivation for this proposal?

Introducing immutable.js List to handle scrollable viewport with relatively big in height and graphicly rich elements.

#### Is there anything else we should know?

-

**Comment by djleonskennedy** [comment]
@adarowiec Have you used conversion back to js?
https://github.com/immutable-js/immutable-js/#converts-back-to-raw-javascript-objects

**Comment by adarowiec** [comment]
@djleonskennedy What's the point of having immutable if I convert it back to JS? Point is that if I pass data down the node it won't get mutated.

**Comment by djleonskennedy** [comment]
@adarowiec no questions

**Comment by marco6** [comment]
@adarowiec As per the current implementation, the only thing that limits you in using an immutable.List in virtual scrolling is the lack of the "length" property (wich you can define easily) and [this](https://github.com/angular/material2/blob/fe569529bf2b1f342445751c39aa087231eee090/src/cdk/scrolling/virtual-for-of.ts#L94) line of code which coerces your structure in an array. 

For the first point, we can define a polyfill (found in polyfills.ts in the example below) to take care of "length". For the second point, you can use a DataSource or an Observable to wrap your immutable (or, in general, Iterable<T>). 

Of course that is not generally true if you want to use the DataSource as it requires the source to be an array (T[]) or a ReadonlyArray<T> wich you won't be able to cast due to missing square bracket operator (this means that what I said is true only in the current implementation of cdkNgFor).

Maybe the details above can help to make the current implementation working as it is a minor change (use count instead of length, enhance DataSource typings) needed to make it work as expected. Moreover the syntax is a bit misleading as the input is marked as "DataSource<T> | Observable<T[]> | NgIterable<T>" while because of its usage it really is DataSource<T> | Observable<T[]> | ReadonlyArray<T>" imho, but I guess it needed to be like that to implement the right interface from angular...

I'll leave you a sample usage here that "works": https://stackblitz.com/edit/angular-v34p6s

Hope this helps,
Marco

**Comment by adarowiec** [comment]
@marco6 thanks, I'll check soon

**Comment by adarowiec** [comment]
@marco6 ok, that's some workaround, but I have an issue now with getting items:
![image](https://user-images.githubusercontent.com/26795400/55616285-c3e5c300-5791-11e9-9027-fba9c55e7b0e.png)

**Comment by adarowiec** [comment]
@marco6 it works, thanks man

**Comment by andrewseguin** [comment]
Looks like there are some valid approaches you can take, I don't think we'll need to implement a separate interface for this.
