### ISSUE TITLE
jQuery serialize() does not serialize all the form inputs when it's inside a mat-tab

### ISSUE THREAD

**Issue by SlimenTN** [angular/components#15472]
#### What is the expected behavior?
serialize all inputs

#### What is the current behavior?
serialize only the active tab

#### What are the steps to reproduce?
This occurs when adding mat-tab component inside form tag
you can find a live example here: https://stackblitz.com/edit/angular-qeeo5b

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular: 7.0.0
Angular Material: 7.3.3
Typescript: 3.1.6
Browser : Chome

#### Is there anything else we should know?
No, that's it.

**Comment by jelbourn** [comment]
This is the expected behavior. Only the active tab is rendered in the DOM.

**Comment by SBCDevelopers** [comment]
@jelbourn so we can't use MaterialTabs within a form and then serialize it ?!

**Comment by jelbourn** [comment]
You can capture the state in other ways, but you can't rely on inactive tabs being in the DOM.

**Comment by SBCDevelopers** [comment]
if it becomes optional it would be better (you get to chose whether you render only the active tab or all tabs)
because in our case (a legacy code) we need to put some tabs inside a form and we need to serialize it with `jQuery.serialize()`, and since, only, the active tab is rendered in the DOM, jQuery can't serialize the other fields.
