### ISSUE TITLE
[Docs] How to actually theme Angular Material

### ISSUE THREAD

**Issue by michael-letcher** [angular/components#15480]
#### What is the expected behavior?
What the generated mat-palette actually does?
How the colors are used in Material?
How to make a palette? i.e. What are 50-A700 and contrast 50-A700. (How are they selected by Material and why)?

#### What is the current behavior?
No information, apart from setting up a default theme.

This is equivalent to saying here's the paint and how to put it on a wall but not mentioning how to make the paints and why it's applied each wall.

**Comment by jelbourn** [comment]
The documentation does intentionally just capture the public APIs and how to use them, since most people shouldn't _need_ to know the implementation details. Those implementation details are captured in the comments of the source:
https://github.com/angular/components/blob/master/src/material/core/theming/_theming.scss
https://github.com/angular/components/blob/master/src/material/core/theming/_palette.scss

If you see something imported omitted from the usage docs, feel free to open a specific issue.
