### ISSUE TITLE
mat-menu won't display when returning an array of objects from a function

### ISSUE THREAD

**Issue by dominicasley** [angular/components#15525]
#### What is the expected behavior?
That mat-menu be displayed when the menu item is activated

#### What is the current behavior?
The mat-menu doesn't display when using *ngFor to loop over an array of objects to create your top level menu buttons. 

#### What are the steps to reproduce?
https://stackblitz.com/edit/angular-mfusft

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular: 7.2.5
Angular Material: 5.2.4

#### Is there anything else we should know?
Works when returning an array of string from a function or using the array of objects from a property.

**Comment by josephperrott** [comment]
This is working as expected because the functions returns an array of items that cannot be tracked (in contrast to the array of strings which can be tracked by simple equality checks).

I have updated [your stackblitz](https://stackblitz.com/edit/angular-eewk2b?file=src/app/menus.component.html) showing that using a `trackBy` in the `*ngFor` for your template works as expected.
