### ISSUE TITLE
Inclusion of Dependent API in documentation

### ISSUE THREAD

**Issue by jgwill** [angular/components#15541]
#### Please describe the feature you would like to request.
When viewing a component  API reference, add a section for dependencies of the said component.

#### What is the use-case or motivation for this proposal?
Example: I am viewing the Button API at :  https://material.angular.io/components/button/api 
I want quickly to have all imports I require (for instance MatIconModule is required by the Button example)
#### Is there anything else we should know?
I love Angular Material :)

**Comment by jelbourn** [comment]
Closing this because I don't believe we have any components that implicitly require a developer to import another `NgModule`. In the case of icon buttons, you are actually _directly_ using `MatIcon` inside of a `MatButton`. It's that direct usage of `MatIcon` that required `MatIconModule`. In other cases where a component is used inside another (like `MatPaginator`), the dependencies are already imported in the appropriate `NgModule`.
