### ISSUE TITLE
MatTabs | selectedIndexChange event not firing when expected

### ISSUE THREAD

**Issue by CollinGraf314** [angular/components#15635]
#### What is the expected behavior?
Any time that the selectedIndex of a mat-tab-group changes, selectedIndexChange should fire.

#### What is the current behavior?
In the case where a tab is dynamically added to an index in the mat-tab-group that is before the currently selected tab's index, the selectedIndex increments but selectedIndexChange does not fire.

#### What are the steps to reproduce?
Click 'Add New Tab' and notice that the 'Selected Tab Index' does not change.
editor: https://stackblitz.com/edit/angular-5kqpjj
app: https://angular-5kqpjj.stackblitz.io

**Comment by josephperrott** [comment]
Closing as we intentionally do not fire an event because it can cause an infinite loop in some cases, such as when `selectedIndexChange` causes a tab to be added. ([note in code](https://github.com/angular/components/blob/8b5c0f12c823a16bdf3d4bcd767d0c42c6b0e870/src/material/tabs/tab-group.ts#L244))
