### ISSUE TITLE
mat-datepicker force change detection

### ISSUE THREAD

**Issue by wadahh** [angular/components#15776]
Im using matDatepickerFilter, but if my data change when panel is opened, change detection  not working.

I have created a [blitz](https://stackblitz.com/edit/angular-8uevn4)

To reproduce it: 

- click on input

- wait for 2 seconds

- click on disabled date or close and open panel

**Comment by andrewseguin** [comment]
The datepicker is set up to determine the disabled dates after content is initialized. Since this is a one-time thing done by the month-view, you'll want to determine the disabled states before showing that month.

A workaround will likely involve making the month-view refresh itself, which may be by closing/opening it quickly, or switching back and forth from a month.

Here's one implemented workaround: https://stackblitz.com/edit/angular-w42tkh?file=src/app/app.component.ts

**Comment by fabienavedissian** [comment]
Thanks Andrew,
[Blitz](
https://angular-vgqzoy.stackblitz.io/)

**Comment by wadahh** [comment]
Thanks Andrew,
[Blitz](https://angular-vgqzoy.stackblitz.io/)
