### ISSUE TITLE
[MatSort ] ExpressionChangedAfterItHasBeenCheckedError with aria-sort

### ISSUE THREAD

**Issue by Xen3r0** [angular/components#15848]
#### What is the current behavior?
I have a ExpressionChangedAfterItHasBeenCheckedError :

> Error: ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: 'aria-sort: null'. Current value: 'aria-sort: ascending'.

How can i fix this ?

#### What are the steps to reproduce?
Example: https://stackblitz.com/edit/angular-vqqick

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular: 7.2.13
Material: 7.3.7
Browser : chrome (latest)

**Comment by crisbeto** [comment]
It's hard to tell when this is happening without a code sample or some more information.

**Comment by Xen3r0** [comment]
You have a projet sample in description, just lance and watch js console

**Comment by crisbeto** [comment]
Ah, I had missed it because it says "Stackblitz starter".

**Comment by Xen3r0** [comment]
Sorry, i edit my description :)

**Comment by joaodforce** [comment]
Im having a similar issue, And I cannot seem to find what the cause is.
![Captura de Tela 2019-04-22 às 18 00 17](https://user-images.githubusercontent.com/9410916/56530388-a9993c80-6528-11e9-8359-c7131f50f0e7.png)

It seems to be something with the `hintLabel` property, in my project my fields are being generated from a metadata array.
<img width="779" alt="Captura de Tela 2019-04-22 às 18 00 37" src="https://user-images.githubusercontent.com/9410916/56530386-a900a600-6528-11e9-9e92-9c724276aa53.png">

I've tried replicating the issue on Stackblitz with a simple project, and there no errors appear, Im using the same Angular and Material versions as the Author.

Even if I try `[hintLabel]="'Text with fixed value'"` the error appears, each `mat-form-field` is in a different component instance, maybe this is the issue, Im trying to replicate a similar case on Stackblitz to see if the same error appears, then I'll open an Issue of my own.

**Comment by andrewseguin** [comment]
You are changing the sort during change detection (after view init) which changes the template bindings in sort, so when Angular runs CD again (dev mode), it recognizes that a binding has been changed when it should have been stable.

To resolve this, you need to make sure you are not changing your sort during change detection. Either perform sort during `ngOnInit` before the view is checked, or add something like a timeout to your sort.

Here's a working example: https://stackblitz.com/edit/angular-mxm9h3?file=src/app/app.component.ts

**Comment by Xen3r0** [comment]
Thanks for you answer !
