### ISSUE TITLE
MatInput directive's "required" property is not showing the status correctly !!

### ISSUE THREAD

**Issue by anieshvishnu** [angular/components#15959]
#### What is the expected behavior?
For a required form control the required property should return true.

#### What is the current behavior?
Required form control's required property is returning false always.

#### What are the steps to reproduce?
https://stackblitz.com/edit/angular-ftwcyt

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

    "@angular/animations": "^7.2.14",
    "@angular/cdk": "^7.3.7",
    "@angular/common": "^7.2.14",
    "@angular/compiler": "^7.2.14",
    "@angular/core": "^7.2.14",
    "@angular/forms": "^7.2.14",
    "@angular/http": "^7.2.14",
    "@angular/material": "^7.3.7",
    "@angular/platform-browser": "^7.2.14",
    "@angular/platform-browser-dynamic": "^7.2.14",
    "@angular/router": "^7.2.14",
    "bootstrap": "3.3.7",
    "core-js": "^2.5.4",
    "hammerjs": "^2.0.8",
    "rxjs": "6.5.1",
    "rxjs-compat": "^6.1.0",
    "zone.js": "^0.8.26"

**Comment by andrewseguin** [comment]
Thanks for filing the issue and showing a good reproduction. Unfortunately this is caused by a few different factors, and to solve it right we would need some better integration/information from the form control. As of right now, there is no great way to ensure a form control is "required" - e.g. the form control may use a custom "required" function and we could not detect that.

For now, the best way to workaround this would be to manually mark the input as `required`: https://stackblitz.com/edit/angular-vcvrss?file=src/app/app.component.html

**Comment by mmalerba** [comment]
This is a dup of https://github.com/angular/components/issues/2574
