### ISSUE TITLE
Tree rendering with huge dataset tree is too slow

### ISSUE THREAD

**Issue by sambsa** [angular/components#15960]
I have a mat-tree with with 3000 records in child level
The scenario is like this . I have tree with 3 level suppose Root Parent and children. When I click on parent it is fetching data from backend using API call. From API it returns 30K records I am appending with the current data set and re-rendering it

this.dataSource.data = newDataSource;

It will re-render data and also I am expand the tree to make sure it maintains the previous state using expand function

this.treeControl.expand();

Here API call took 1 second but rendering took 15sec to render the tree including expand. Which is not at all acceptable. Is there any method available to render partially like render node() . Because rendering full node is too costly I guess for 30k elements.

I have filter in child level I mean in 30k elements coming that level. So frequently filter and load operations happening. Please help guys. I am stuck with this

**Comment by andrewseguin** [comment]
In general, rendering 30,000 elements at once on a page will be slow. This is more of a problem with browser capabilities than something we can fix.

Is it helpful to the user to have those 30,000 records displayed? What information are you trying to convey to the user, and what is the users hoping to gain from the tree-view? It is probable that you want to provide better paging/sorting/filtering functionalities so that the user can quickly find what they are looking for. At the very least, I would have a "Load more" button after 20-30 rows if the user has not yet found what they are looking for.

Closing since unfortunately we cannot do much to help this case. If you need more guidance on layout/render architecture, check out our community at StackOverflow and feel free to ask questions there
