### ISSUE TITLE
Material Table Does not detect the changes in the datasource as per angular shange detection

### ISSUE THREAD

**Issue by Prat041192** [angular/components#15972]
#### What is the expected behaviour?
When there is a new row added or deleted on the fly, new row should be visible or delete record is removed

#### What is the current behaviour?
As per the current status, there is no change to the rows, Once the data source is mapped, the component need to get reloaded even after the change detection in angular.

#### What are the steps to reproduce?
https://stackblitz.com/edit/angular-material2-issue-tfh1rs

#### What is the use-case or motivation for changing an existing behaviour?
Use case: Add or remove records on the fly with add or remove operations.
e.g. : Use has populated a list of records say cities where some service is available but on the admin side of the UI

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
I am using following
"@angular/cli": "~7.3.6",
"@angular/compiler-cli": "~7.2.0",
"typescript": "~3.2.2"

**Comment by andrewseguin** [comment]
When passing an array to the table, it will only re-render if the array reference is changed because it is based on the principle of using an immutable data array. There are two approaches you can do:

1. Create a new array reference when mutating the array: https://stackblitz.com/edit/angular-material2-issue-mmqauw?file=app/app.component.ts
2. Use a data source that emits whenever the data is changed: https://stackblitz.com/edit/angular-material2-issue-mtix5b?file=app/app.component.ts
3. Call the render function on the table when your data is changed: https://stackblitz.com/edit/angular-material2-issue-kf4rnt?file=app/app.component.ts

The table is designed this way to prevent any unnecessary diff checking of the provided data array, and making it explicit when changes occur so it can be as efficient as possible.
