### ISSUE TITLE
Observable completes on router.navigate to change query params

### ISSUE THREAD

**Issue by JDouven** [angular/components#15979]
#### What is the expected behavior?
When using Router.navigate() to navigate to the same route (but to change the query parameters), observables do not complete and retain their observers.

#### What is the current behavior?
When using Router.navigate() to navigate to the same route (but to change the query parameters), observables complete and therefore lose their observers.

#### What are the steps to reproduce?
[https://stackblitz.com/edit/angular-material2-issue-ayqaoe](Stackblitz)
1. Open the Stackblitz
2. Open the angular page (you might need to refresh a few times until you see a table instead of a loading spinner)
3. Once you see the table, click on the link at the top, this will use Router.navigate (but to the route you're currently on, it's done just to set the query params)
4. Watch the spinner turn forever because it's no longer subscribed to the WebApiDataSource.loading$ observable.

_**Now change @angular/cdk & @angular/material version to 7.3.0 and try again**_

You will see that it works now. This bug will occur only in Material version 7.3.1 and up. 7.3.0 and below works fine.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
"@angular/core": "7.0.1",
"@angular/material": "^7.3.1",
OSX
"typescript": "~3.1.1",
Chrome, Edge, Opera, Firefox, Safari

#### Is there anything else we should know?
I have tried to look through the changes between 7.3.0 and 7.3.1 but I could not identify a cause. Perhaps someone more experienced with this code can take a better look.

**Comment by andrewseguin** [comment]
This seems unrelated to Material, so I'll close the issue and recommend that you re-open it in Angular or rxjs if you find that there is a routing issue or observable issue.

That said, it seems that your issue stems from the fact that when the table is destroyed, it will call `disconnect` on the data source, which is completing the loading stream. The next time you call `loadExamples`, you emit a `true` on the `loadingSubject` but it has already been completed at that point.

Here's an example showing what happens if you do not complete the loading subject on disconnect: https://stackblitz.com/edit/angular-material2-issue-fmmums?file=app%2Fdatasource%2Fweb-api-datasource.ts

**Comment by JDouven** [comment]
The reason I opened it here is due to the fact that lowering this package's version fixes my issue. Logic dictates that the issue stems from this package. Please explain to me why you think it can't be related to this package.

**Comment by andrewseguin** [comment]
Hm, you got me there. Looks like this is the result of fixing a bug where the datasource was not disconnecting in some cases: https://github.com/angular/components/pull/14966

In your case, the disconnect function should have been called when the route changed, but it was not because the table didn't consider your data source to be an instance of DataSource. This is because you are using `implements` instead of `extends`.

In your example, if you change the data source to extend DataSource, you'll see the issue appear in 7.3.0: https://stackblitz.com/edit/angular-material2-issue-ttbpfz?file=app/datasource/web-api-datasource.ts

**Comment by JDouven** [comment]
Nice find! Thank you for thinking with me on this. I agree that this is the cause of my issue. Could you point me in the right direction how I can fix this? Because only the query params change, the component is not re-initialised. Should I initialise the table with the datasource again on route change ([like this](https://stackoverflow.com/questions/33520043/how-to-detect-a-route-change-in-angular?rq=1))?
Or do you know of any other way? 

To me it feels wrong that I need to do initialisation on the table again when my component does not need to initialise. However I do not know how you intended the table component to work.

**Comment by andrewseguin** [comment]
In your case I'd start with just not destroying the table every time the data source is loading. You could set up your spinner to be in the same container as the table, so that it overlays directly over it, and it shows up whenever the data is loading.

Here's one option for an implementation, in case you want to see what that looks like: https://stackblitz.com/edit/angular-material2-issue-hcyv25?file=app/datasource/web-api-datasource.ts
