### ISSUE TITLE
Angular Material components is refreshing dynamic embed tag

### ISSUE THREAD

**Issue by diegomachado1** [angular/components#16015]
#### What is the expected behavior?

I expect to use an Angular form with an `embed` tag (to see PDF files)  on the same page.

#### What is the current behavior?

When I click on input and start typing, the embed is refreshing after each key I press

#### What are the steps to reproduce?
[StackBlitz](https://stackblitz.com/edit/angular-rsbqxr)

Click at `Sushi` and start typing

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 7
Material 7

Browsers: Chrome, Firefox

#### Is there anything else we should know?

With static URI on `embed src` it works fine. The problem are links that come from some var

**Comment by crisbeto** [comment]
It's because `bypassSecurityTrustResourceUrl` returns a new object for every change detection which makes Angular think that the value has changed on every change detection run. You should assign the sanitized URL to a property that only updates if the URL is updated. Closing since this works as expected.
