### ISSUE TITLE
Toolbar modes

### ISSUE THREAD

**Issue by uahic** [angular/components#16030]
#### Please describe the feature you would like to request.
A multi-mode toolbar that implements a contextual overlay 

#### What is the use-case or motivation for this proposal?

I am working on a PWA, intended to work on both desktop and mobile and now is the question how to properly implement a contextual toolbar since I want to have basically a search-bar like on the MDC webpage (https://material.io/develop/web/). 

Of course it could be done quite easily by just using structural directives and manipulating the child-content directly but if the toolbar is used in a layout frame with router then services would be required. I was thinking about to implement the context (search bar) similar to a bottom sheet such that get a contextRef programatically as handle. 

Actually my question is: how would the angular material team solve this? or do you think there is no generic solution so you just keep it to the minimum (the current state)?

My current implementation does not have any context yet only a cdk portal service to change page-actions. 

The more I think about it the less it makes sense to have a app bar defined in a layout (at least if you want to change the title, possible contexts and page actions you dont have really code-reduction)

**Comment by andrewseguin** [comment]
Here's the route I've taken in my apps:

- The header component contains a cdkPortalOutlet
- A global service provides the current portal template that should be displayed
- Any subcomponent in my app (normally the page level components) will write a custom template, then grab it using `ViewChild`, and stash it into the global service.

I'm sure there's other solutions but so far this works well for me since the individual routes can change the toolbar's content and the toolbar doesn't need to be coupled with the knowledge of pages.

As for providing a general solution in Material or CDK, I don't foresee us putting that in our roadmap
