### ISSUE TITLE
Vertical alignment in mat-card-title and button not correct

### ISSUE THREAD

**Issue by jpike88** [angular/components#16094]
```
		<mat-card-header>
			<mat-card-title>
				Specifications
			</mat-card-title>
			<span fxFlex></span>
				<button mat-icon-button
				(click)="doSomething()">
					<mat-icon>edit</mat-icon>
				</button>
		</mat-card-header>
```

The button should be auto-aligned or have a margin to suit the mat-card-title.
![Screen Shot 2019-05-23 at 1 04 18 pm](https://user-images.githubusercontent.com/9585787/58229262-687c8e00-7d5b-11e9-89ee-d1b9d939a819.png)

If I place the button in a div with `margin-bottom: 12px; margin-top: -4px;` (which is same as mat-card-title), this mimics the correct layout:

![Screen Shot 2019-05-23 at 1 04 07 pm](https://user-images.githubusercontent.com/9585787/58229309-8f3ac480-7d5b-11e9-96b4-ce2a8d5dd1fe.png)

If I place the <span> and <button> tag INSIDE the mat-card-title, it doesn't flex to full width:

![Screen Shot 2019-05-23 at 1 06 28 pm](https://user-images.githubusercontent.com/9585787/58229335-a4175800-7d5b-11e9-9f50-b6c019919232.png)

I think buttons/icon elements should be vertically aligned/margined in a mat-card-header to offset the same as the title itself.

**Comment by wolframm** [comment]
It's pretty sad that adding a simple button at the end of a card header is not backed in. Wasted so much time trying to set this up.

**Comment by ctaleck** [comment]
It would be nice to have right-aligned menus "baked" into Material Design. For now, see my solution in Example 6 & 7 where I've added special handling divs and flex spacers to handle. See [Stackblitz](https://stackblitz.com/edit/angular-cards-y9e3iq?file=src/app/card-overview-example.html).

While I see the vertical alignment issue, it does not bother me so much, especially when you consider the ripple effect on the button:

![image](https://user-images.githubusercontent.com/8421373/107590907-a91ed980-6bc6-11eb-84c7-918c3090a772.png)

**Comment by jelbourn** [comment]
I took a look at this with the mdc-based card/button:
https://stackblitz.com/edit/angular-mdc-issue-tcvaj3?file=src%2Fapp%2Fmdc%2Fmdc-example-module.ts

I think that we probably won't change anything about this. The issue is that the button styles are meant to be used in more standalone contexts, and the card header is mainly meant for text content. Adding extra styles just for icon buttons in card headers would be extra bloat that most apps don't need. I know it's nice if everything just aligns in all circumstances, but I don't think adding a special case here is worth it.
