### ISSUE TITLE
Add the ability for matPrefix and matSuffix to have the same color as the mat-form-field.

### ISSUE THREAD

**Issue by andreElrico** [angular/components#16110]
#### Feature Description
This here is funny and spoils the story -> [STACKBLITZ](https://stackblitz.com/edit/angular-fzbjcw?file=app/form-field-appearance-example.html) 

It would look nice if the prefix and suffix color could match the overall formfield color. 
It would also be nice if this behaviour could be set globally.

Esp on error I like to see some red pre/suffix!

#### Use Case

Neater UX.

**Comment by mmalerba** [comment]
The spec shows that icons should usually be black (https://material.io/components/text-fields). The one exception is when they show an error icon, it is usually red. Rather than having the color of the prefix / suffix automatically change we suggest people just use `<mat-icon color="error">` if they want to show an error icon like in the spec. It wouldn't make sense for other icons like the datepicker toggle icon to turn red.
