### ISSUE TITLE
Sidenav overlaps main content when used in multiple tabs

### ISSUE THREAD

**Issue by ghanashyam-c-k** [angular/components#16119]
#### Reproduction

Use StackBlitz to reproduce your issue: https://angular-n1uhed.stackblitz.io

Steps to reproduce:
1. Navigate between tabs
 
 
#### Expected Behavior

sidenav and the main content rendered side by side without overlap

#### Actual Behavior

Sidenav seems to overlap the main content. I am new to angular, so I can't tell if I'm doing something wrong.

#### Environment

- Angular: 7.2.15
- CDK/Material: 7.3.7
- Browser(s): chrome, firefox
- Operating System (e.g. Windows, macOS, Ubuntu):  Win10 x64

**Comment by andrewseguin** [comment]
The issue is related to how Angular creates the content/view and some timing issues.

To workaround this, you can lazily load the tab content by wrapping the tab content in `<ng-template matTabContent>`

See the workaround in action here: https://stackblitz.com/edit/angular-qha2aa?file=src/app/app.component.html
