### ISSUE TITLE
Not able to install dependencies

### ISSUE THREAD

**Issue by manasarora119** [angular/components#16187]
not able to install  dependencies

needs yarn to install dependencies rather than Npm

**Comment by devversion** [comment]
@manasarora119 The components repository requires `yarn` for installing the dependencies. This is because our lock file is from `yarn` and we want to ensure that development on this repository is consistent across different devices.

Please see: https://github.com/angular/components/blob/master/DEV_ENVIRONMENT.md

**Comment by manasarora119** [comment]
@devversion  , It is possible to install dependencies via npm ???

**Comment by devversion** [comment]
You can, but it is not recommended. If you want to use `npm`, you need to update `postinstall` script in the `package.json` to not run `check-npm.js`

**Comment by manasarora119** [comment]
@devversion  Still  getting error .............

The serve command requires to be run in an Angular project, but a project definition could not be found.

**Comment by manasarora119** [comment]
@devversion  any update ????

**Comment by devversion** [comment]
Hi @manasarora119. Can you please elaborate what you are trying to achieve?

From what you wrote.. it sounds like you want to run `ng serve` for the `angular/components` repository. This will _never_ work as the components repository is not an Angular CLI project and we have our own tooling infrastructure.

You could just:

1) Run `yarn install`
2) Run `yarn dev-app`
