### ISSUE TITLE
Issue with mat-menu once upgraded to 8 when changing the screen size

### ISSUE THREAD

**Issue by kuncevic** [angular/components#16199]
#### Reproduction

https://stackblitz.com/github/kuncevic/mat-menu-issue

Steps to reproduce:
1) on a big screen click the person icon
2) see dropdown menu appearing
3) switch to small screen
4) the dropdown still appearing on the top left (that was not a case using version 7 before upgrade)
 
#### Expected Behavior

The dropdown should hide the same way as it does with version 7
The same code with version 7 https://stackblitz.com/github/kuncevic/mat-menu-issue/tree/angular7

#### Actual Behavior

The mat-menu dropdown present on screen when screen changed to small size

#### Environment

@angular/material                    8
@angular-devkit/core              8.0.1
@angular-devkit/schematics  8.0.1
@angular/cli                              8.0.1

**Comment by StephenFluin** [comment]
@kuncevic We looked into this. It looks like you are relying on the internal DOM and CSS of the component, which isn't part of the API.

The right thing to do here is to use a [Breakpoint Observer](https://alligator.io/angular/breakpoints-angular-cdk/) to open and close it instead of just hiding it.

As a small workaround (NOT RECOMMENDED, WE MAY BREAK YOU AGAIN) might be to target `::ng-deep .mat-menu-panel {` [instead](https://stackblitz.com/edit/github-zo1hjv?file=src/app/app.component.ts).

**Comment by josephperrott** [comment]
Closing based on the explanation @StephenFluin gave above.  The class names and HTML structures of our components are not considered part of our API and are subject to change.  They are typically pretty stable, but can change unexpectedly.
