### ISSUE TITLE
mat-card in mat-dialog-content has top and bottom edges clipped

### ISSUE THREAD

**Issue by jpike88** [angular/components#16227]
This is what happens when a mat-card goes inside a mat-dialog-content
![Screen Shot 2019-06-07 at 1 21 52 pm](https://user-images.githubusercontent.com/9585787/59084945-39ebdf00-8927-11e9-9a39-46dd5e580a1b.png)

Top and bottom shadows are clipped.

adding this to .mat-dialog-content fixed it:
```padding: 1px 24px;```

![Screen Shot 2019-06-07 at 1 22 13 pm](https://user-images.githubusercontent.com/9585787/59085009-6142ac00-8927-11e9-9d57-88c0b2c7cf78.png)

I could have multiple cards in the content, it's why I'm using a card.

**Comment by jelbourn** [comment]
Example with mdc-based card/dialog: https://stackblitz.com/edit/angular-mdc-issue-zh7adg?file=src%2Fapp%2Fmdc%2Fmdc-example-component.ts

The top is slightly clipped, but I think it's reasonable for the dialog content to be given a padding at the application level since this is just a general behavior of box-shadow (being clipped by element boundaries).
