### ISSUE TITLE
How can I get flexible position for overlay like mat-select?

### ISSUE THREAD

**Issue by wis-ekubesh** [angular/components#16302]
#### What are you trying to do?

I'm trying to get exact same behaviour like in mat-select. Depends on how much space under select element - portal overlay with options opens above or below select element.

I'm trying to get the same behaviour, but without cdk-overlay directive, just using OverlayRef.attach(containerPortal).

I tried so many different ways, but it still opens below my element and clipped.

Where is some way or example of using position strategies for correct position elements depends on screen size?

![image](https://user-images.githubusercontent.com/17099950/59564466-ecbaec00-904f-11e9-9be8-b6ebfd6c0907.png)

**Comment by jelbourn** [comment]
`MatSelect` has custom code for its positioning, which isn't currently available as a standalone API because it's super tightly coupled to internal structure of the select. We have no plans to make a more general version at this time, but overlay does support custom `PositionStrategy` implementations.
