### ISSUE TITLE
Submitted state on FormGroup in subcomponent is inconsistent/incorrect

### ISSUE THREAD

**Issue by MatthiasKunnen** [angular/components#16360]
#### Reproduction

[https://stackblitz.com/edit/components-issue-form-group-submitted](https://stackblitz.com/edit/components-issue-form-group-submitted?file=app%2Fapp.component.html)

Steps to reproduce:
1. Click on submit to see one submitted state become true but not the other
 

 #### Expected Behavior

Both form groups should become submitted.

#### Actual Behavior

The component which uses a `[formGroup]` directive does not become submitted.

#### Environment

- Angular: 8.0.0
- CDK/Material: 8.0.0
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Ubuntu & StackBlitz

**Comment by Airblader** [comment]
1. This repository is for Angular Material, but your question is entirely about the Angular framework, so you're in the wrong repository.
2. This behavior is correct/intended. For subforms you should use the formGroupName directive rather than another formGroup directive. Or better yet, implement a ControlValueAccessor.

**Comment by MatthiasKunnen** [comment]
I've added a new scenario to the [StackBlitz](https://stackblitz.com/edit/components-issue-form-group-submitted?file=app%2Fapp.component.html) which uses formGroupName but that does not do what I want either.

If that behavior is intentional as well I'll take this issue to <https://github.com/angular/angular>.
