### ISSUE TITLE
mat-sidenav breaks sticky

### ISSUE THREAD

**Issue by pburkindine** [angular/components#16443]
#### Reproduction

https://stackblitz.com/edit/sidebar-sticky

Steps to reproduce:
1. Add a sticky element inside a `mat-sidenav-content`
2. Element will not stick to the top of the screen
3. Unsetting `display: block` on `mat-sidenav-container` fixes this but breaks the sidenav itself
 
 
#### Expected Behavior

Be able to use sticky elements inside the `mat-sidenav-content`

#### Actual Behavior

Elements do not stick

#### Environment

- Angular: 8
- CDK/Material: 8
- Browser(s): Chrome, Firefox
- Operating System (e.g. Windows, macOS, Ubuntu): OSX High Sierra

**Comment by pburkindine** [comment]
This issue is fixed by applying `position: absolute` to the container as in the example:
https://stackblitz.com/angular/jxyxrjpkkaj?file=app%2Fsidenav-overview-example.css

making the container `position: absolute` is also necessary to prevent the content from scrolling, which is normal functionality when the backdrop is shown

I think it would be good to add an input to control whether `position: absolute` is applied to the container, and consider setting it true by default.

**Comment by jelbourn** [comment]
(revisiting older issues as part of a triaging fix-it)

The problem here is that you're not actually scrolling the `mat-sidenav-content` element- the `body` element is scrolling. The way `position: sticky` works is that it's sticky relative to its containing element, so when the _body_ scrolls instead, the entire `mat-sidenav-content` is being scrolled through the body. You can see this manifest by adding a smaller height to `mat-sidenav-content` and scrolling.
