### ISSUE TITLE
virtual-scroll: buggy behavior with tr elements and attribute rowspan

### ISSUE THREAD

**Issue by viktordavidovich** [angular/components#16474]
#### Reproduction

Please find an example of buggy behavior with virtual-scroll applied on `tr` with `rowspan` attribute.

[https://stackblitz.com/edit/angular-virtual-table-scrolling-16bscz](https://stackblitz.com/edit/angular-virtual-table-scrolling-16bscz)

Steps to reproduce:
1. Simply apply virtual-scroll on `tr` elements inside `table`.
2. Add some logic of adding `rowspan` attribute.

#### Expected Behavior

I would expect to see similar smooth scroll behavior without "jumping" content from place to place.

#### Actual Behavior

I see some buggy behavior, content jumping from place to place.

#### Environment

- Angular: 7.0.1
- CDK/Material: 7.1.0
- Browser(s): Version 75.0.3770.100 (Official Build) (64-bit)
- Operating System (e.g. Windows, macOS, Ubuntu):  Windows 10

**Comment by shanehsu** [comment]
Since your rows might not render as expected boundaries, that’s probably why things are jumpy.

You might have to create a custom scroll strategy to achieve expected behavior, or set `minBufferPx` to a large enough value that exceeds your `itemSize` × max(`rowSpan`). This way you will be sure that incorrectly-placed `td` will not appear in the viewport.

**Comment by viktordavidovich** [comment]
@shanehsu I’m sorry, I just removed example from stackblitz a couple of days ago. Need to try yours solution, thanks. Because as for now, I had to get rid of `rowspan` attribute completely.

**Comment by shanehsu** [comment]
@viktordavidovich Now I think about it, though a large enough `minBufferPx` would work, my formula is problematic to say the least. But the idea remains to have viewport to always render a large enough block of `tr`s and `td`s so that things that are currently visible in the viewport appear normal.

Another way you could potentially try is to not use `table` at all, and do the table-like layout yourself. This means that you can control where each cell appear, and whether or not preceding `td`s with `rowspan` is rendered won't matter.
