### ISSUE TITLE
mat-radio-label custom-height

### ISSUE THREAD

**Issue by Nodarii** [angular/components#16520]
#### Feature Description

I would like mat-radio-label to fill 100% height of mat-radio-button so it’s vertically aligned when I increase height of the button. 

#### Use Case

actual:
![image](https://user-images.githubusercontent.com/1251685/61218665-2d735700-a71b-11e9-96a2-17772e90a1b1.png)
![image](https://user-images.githubusercontent.com/1251685/61218709-4e3bac80-a71b-11e9-9f73-acce61624e2a.png)
expected:
![image](https://user-images.githubusercontent.com/1251685/61218787-82af6880-a71b-11e9-94bd-96aeba05ca44.png)
![image](https://user-images.githubusercontent.com/1251685/61218832-9e1a7380-a71b-11e9-911b-b070b2023ebf.png)

**Comment by andrewseguin** [comment]
I don't think that at this point we would make this change since it would break current apps that do not expect this, and it's fairly trivial to add styling that would center the options. I'd feel more comfortable about this change if it were defined in spec. 
```css
mat-radio-group {
  display: flex;
  align-items: center;
}
```


https://stackblitz.com/edit/angular-loku3u?file=app/radio-overview-example.css
