### ISSUE TITLE
Drag and drop scrolling container

### ISSUE THREAD

**Issue by plchampigny** [angular/components#16535]
#### Feature Description

In version 8.1.0 of components, the new scrolling feature enables auto scrolling of the cdkDropList or the viewport. It would be awesome to specify the drag scroll container if the scrolling container is not the droplist or the viewport. 

Cdk drag scroll enables this feature using the vsDragScrollContainer directive,
https://github.com/volser/cdk-drag-scroll

#### Use Case

Container with scrolling containing a droplist that can't be scrolled with a viewport that cant be scrolled. Specifying the container and hooking up on its scrolling should enable scrolling.

**Comment by fatmaE19** [comment]
any sollution for that ? i have the same problem :/

**Comment by palsmadal** [comment]
I have been playing around with some code that does this since I have the same requirements for my application. Basicly it's a new input for the CDKDropList which is called "cdkDropListAutoScrollContainer". Here you just pass inn an element reference and the autoscroll should use this container for scrolling. As it is designed now it will override the scrolling behaviour on both window and the cdkDropList container.

What do you think about this solution?

I have a branch with my solution that you can check out if you want: https://github.com/palsmadal/components/tree/feature/cdk-drop-list-scrolling-container

**Comment by palsmadal** [comment]
Any feedback on solution?

**Comment by aeslinger0** [comment]
I'd like to expand on this and suggest that multiple scroll containers be supported. I have a page that has many scrollable columns side by side, but unfortunately I'm unable to drag and autoscroll horizontally. You can see what I mean here: https://www.techgroups.com/job-tracker

**Comment by leandroz** [comment]
Same as @aeslinger0 , it could be awesome to have the ability to not only scroll vertically but also horizontally between different list containers, similar to a Trello board.

**Comment by gabrielkunkel** [comment]
I would settle for a way to adjust where scrolling kicks in on the viewport.

**Comment by maknapp** [comment]
I think this is fixed by #18082.

**Comment by elezar42** [comment]
@crisbeto Do you know if there will be an 8.x release that includes #18082?

**Comment by crisbeto** [comment]
This is supported now by setting `cdkScrollable` on the parents that should scroll. Closing.
