### ISSUE TITLE
material table header sticky hover bug

### ISSUE THREAD

**Issue by markkoo** [angular/components#16564]
#### Reproduction

Use StackBlitz to reproduce your issue: [https://stackblitz.com/github/markkoo/material-table-sticky-issue](https://stackblitz.com/github/markkoo/material-table-sticky-issue)
![gif3](https://user-images.githubusercontent.com/4880701/61513535-045f0900-aa30-11e9-9d9a-024c930bbb87.gif)

Steps to reproduce:
1. scroll and hover header
 
 
#### Expected Behavior

What behavior were you expecting to see?
1. header background color will remain when scroll and hover.

#### Actual Behavior

What behavior did you actually see?
1. header background is transparent when scroll and hover.

#### Environment

- Angular: 8.1.2
- CDK/Material: 8.1.2
- Browser(s): chrome
- Operating System (e.g. Windows, macOS, Ubuntu): window 10

**Comment by andrewseguin** [comment]
This doesn't seem to be a problem with the table, it's just that you are setting a transparent background on the row. Change `background:rgba(0,0,0,0.5);` to an opaque color so that there is no transparency, e.g. `#3f3f3f` or `#7f7f7f`

Here's a stackblitz example: https://stackblitz.com/edit/github-xdhdq9?file=src/app/app.component.scss
