### ISSUE TITLE
Should sortingDataAccessor coerce value to number if value type already specified as string?

### ISSUE THREAD

**Issue by daveccrit** [angular/components#16646]
#### Reproduction

https://stackblitz.com/edit/angular-nxkhsk

Steps to reproduce:
1. Click on version column header to short ascending or descending to see issue
 
 
#### Expected Behavior

Table is sorted by version column string value. It shouldn't matter if the value can be coerced to a number, if the column is defined as a string shouldn't the sort treat it as such?
I have read some similar issues opened against this issue (: https://github.com/angular/components/issues/9966), and a work around can be done to allow for the behavior to be changed, however the default behavior seems odd when the columns already have a type definition.

#### Actual Behavior

Table is not sorted correctly by version number.

#### Environment

- Angular: 8.1.3
- CDK/Material: 8.1.2
- Browser(s): Chrome, Firefox
- Operating System (e.g. Windows, macOS, Ubuntu): macOS

**Comment by andrewseguin** [comment]
Unfortunately we cannot make that assumption since we need to support the case where numbers are passed as strings. The `MatTableDataSource` tries its best to fit the majority of cases but provide a way to customize it when those cases are not met. This is a good example where we may not be able to elegantly handle this.
