### ISSUE TITLE
Toggle Buttons: Wrong height with Angular Flex

### ISSUE THREAD

**Issue by KlausHans** [angular/components#16660]
#### Reproduction

Use StackBlitz to reproduce your issue: https://stackblitz.com/edit/angular-ik8ikp?file=app%2Fbutton-toggle-overview-example.html

Steps to reproduce:
1. Open the provided Stackblitz
2. The toggle buttons have a wrong height
3. Play with the inline height of the row
 
 
#### Expected Behavior

What behavior were you expecting to see?
I would expect the height of the toggle buttons stays the same and is independent of the row height.

#### Actual Behavior

What behavior did you actually see?
The toggle button height grows with the wrapping row height.

#### Environment

- Angular: 8.2
- CDK/Material: 8.1.2
- Browser(s): Firefox
- Operating System (e.g. Windows, macOS, Ubuntu): Windows 10

**Comment by andrewseguin** [comment]
The combination of the toggle group being `inline-flex` and the parent being `flex` causes this behavior. 

Changing the `inline-flex` of the toggle group is likely not going to happen but this can be fixed by applying the cross-axis parameter to your `fxLayoutAlign`. This will help the container know where you position the toggle group rather than stretching it.

Here's an example of adding `start` as the cross-axis parameter, causing the toggle group to be aligned to the top: https://stackblitz.com/edit/angular-ik8ikp-38bwm9?file=app/button-toggle-overview-example.html
