### ISSUE TITLE
mat-datepicker - unable to set date display format as dd-mmm-yyyy

### ISSUE THREAD

**Issue by muruganklt** [angular/components#16774]
if I am entered 29/05/1995 mat-datepicker field  displayed 29/JAN/2019 instead of  29/MAY/2019 

export const DateFormats = {
  parse: {
    dateInput: 'DD/MMM/YYYY',
  },
  display: {
    dateInput: 'DD/MMM/YYYY',
    monthYearLabel: 'MMM YYYY',
    dateA11yLabel: 'DD/MMM/YYYY',
    monthYearA11yLabel: 'MMM YYYY',
  },
};

**Comment by muruganklt** [comment]
![image](https://user-images.githubusercontent.com/51367333/62998145-31180c00-be88-11e9-9505-195d696e6f9f.png)

![image](https://user-images.githubusercontent.com/51367333/62998160-412feb80-be88-11e9-8400-c3a0694a6f18.png)

**Comment by MatthiasKunnen** [comment]
This issue is missing info such as the date adapter used, the value the datepicker reports, and a minimal reproduction using a StackBlitz. Please follow the issue templates. This is why you haven't received an answer yet. Another reason is that this is a question more suitable for Stack Overflow.

These things put aside, your problem probably is that your parse format is incorrect. Your current parse format, `parse.dateInput`, is `DD/MMM/YYYY` which takes inputs such as `15/May/1995`. Change it to `DD/MM/YYYY`.
