### ISSUE TITLE
Mat-radio-group selects another radio beside clicked one

### ISSUE THREAD

**Issue by yilmazhasan** [angular/components#16801]
#### Reproduction

Here you can see code:
1.  https://stackblitz.com/edit/components-issue-2vg68d
  
#### Expected Behavior

Should select clicked one

#### Actual Behavior

E.g. When clicked first, second one is getting selected too

#### Environment

- Angular: 7.0.2
- CDK/Material: 8.1.3
- Browser: Chrome
- Operating System  Windows

**Comment by andrewseguin** [comment]
Since your array is made of primitives, `ngFor` is unsure how to track the repeated elements. E.g. When both rows are "a", then `ngFor` sees them as equal.

To fix this, add a `trackBy` function to tell `ngFor` to track by index instead of reference. 

In addition, switch from `ngModel` to explicitly defining the `value` of the toggles and responding to the changes by modifying your array. 

https://stackblitz.com/edit/components-issue-hymcru?file=app/app.component.html
