### ISSUE TITLE
Weird behavior when hovering a matSortHeader using a function to print data

### ISSUE THREAD

**Issue by prmces** [angular/components#16873]
Hello All..

I am facing an weird behavior in the Material table when using a SortHeader and a function to show the value in the Cell.

[StackBlitz Repro](https://stackblitz.com/edit/angular-rswapg)

![image](https://user-images.githubusercontent.com/20740261/63645459-0b370680-c6d5-11e9-9a62-a32d7a781d82.png)

If you look at the image, I created a function PrintData. It only gets the element[column] and return it. Then I added a console.log to show how many times this function is called, and it is a lot. It is ok as it is loading for each column, each line.

The problem starts when I try to hover the header columns. I just move the mouse over the header colums and the printdata functions starts to be called, and I dont know if this is really needed.

To TEST, only move you to any header column and you will see the console.log filling up.

This is the intended behavior??

Thanks

**Comment by andrewseguin** [comment]
This is intended since change detection needs to run for the sort header's animation. In general, using functions to render template HTML will be more expensive since Angular cannot know if the function's value will be changed. Otherwise, Angular is a bit smarter about checking if the value is dirty and is far more performant.
