### ISSUE TITLE
 Incorrect work of the scroll in the mat chip list

### ISSUE THREAD

**Issue by MayorovNE** [angular/components#16887]
### **Bug**
Scroll does not work correctly when you click on the scrollbar itself, it twitches and returns. I found a good example in issue # 11915. 
[**Example**](https://stackblitz.com/edit/share-angular-chips-q8qas4?file=app%2Fchips-stacked-example.scss)
**instruction**
Click 2 times in the middle of a simple scroll toolbar and 2 times in the middle of a mat-chip-list scroll toolbar for understanding.
**Expected Behavior**
Scroll of mat chip list should work like a scroll in a simple block (smoothly)
**Environment**
Angular:
CDK/Material: Material 8.1.3
Browser(s): Chrome
Operating System (e.g. Windows):

**Comment by jelbourn** [comment]
This may seem strange, but it's actually working as expected. The `mat-chip-list` is focusable, and when it gets focus, it redirects that focus to the first chip. When focus moves, it scrolls the container to that chip. You can avoid this by having another element _around_ mat-chip-list be the scrollable container rather than making `mat-chip-list` scroll itself.
