### ISSUE TITLE
Angular 8 Upgrade Dramatically Changed My CSS [pics included]

### ISSUE THREAD

**Issue by FiringBlanks** [angular/components#16934]
#### Reproduction
I'm using Angular Material and [Fomantic UI](https://fomantic-ui.com/elements/button.html). I just upgraded from Angular v7 to v8 and noticed my Fomantic-related UI (which is class-based) looks very off. 
 
#### Expected Behavior

The UI (tables, spacing, margins, etc.) should have remained the same between Angular updates. 

#### Actual Behavior

This. Everything is very off.  _Before_ on left, _after_ on right:

![QMN Update Before-After Combined 1](https://user-images.githubusercontent.com/8304326/64069020-1074e380-cbf6-11e9-9520-5d8061464a8b.png)
![QMN Update Before-After Combined 2](https://user-images.githubusercontent.com/8304326/64069022-12d73d80-cbf6-11e9-8e72-88e906163c3c.png)
![QMN Update Before-After Combined 3](https://user-images.githubusercontent.com/8304326/64069023-15399780-cbf6-11e9-9089-e487777242d9.png)

The icons showing on the right side of the table in the last pic are only because I was signed in, but the icons should not have stacked on top of one another like that. It should all be on one line. 

#### Environment

- Angular and CDK/Material:

![8-31-19 - ng version](https://user-images.githubusercontent.com/8304326/64069007-f1765180-cbf5-11e9-872a-bf855c6b4244.PNG)

- Browser(s): Chrome 76.0
- Operating System: Windows 10

**Comment by jelbourn** [comment]
While there weren't many changes in v8, it is a _major_ version change. Generally we avoid any significant changes for patch and minor releases, but ultimately some styles _will_ change as the library is actively developed. 

While we could certainly make an effort to capture more CSS changes in the changelog, it's not clear what specifically changed here that affected your app; the screenshots don't really provide enough information, since the changes could be coming from anywhere.

Feel free to open a new issue if you have specific changes you think should be called out.
