### ISSUE TITLE
Add HTML tags in Mat tooltip

### ISSUE THREAD

**Issue by VGawade** [angular/components#17082]
#### Feature Description

Add HTML tags in mat tooltip

#### Use

It will be useful to modify the tooltip design if the tooltip provides the way to add HTML tags in it.

@mprobst, @peterblazejewicz

**Comment by crisbeto** [comment]
This has come up before and the reasons we haven't done it are:
1. According to the Material Design spec tooltips should only contain text.
2. It's more difficult to make it accessible to screen readers, because we'd have to keep the content in the DOM at all times.
3. We'd have to introduce a different API for specifying the message which could conflict with the current one.
