### ISSUE TITLE
mat-checkbox in mat-header-cell is not displaying the correct state

### ISSUE THREAD

**Issue by hisankaran** [angular/components#17107]
#### Reproduction
https://stackblitz.com/edit/components-issue-xbj9ne

Steps to reproduce:
1. Click on the checkbox in mat-header to select all, it selects all the items in the current page [indeterminate state]
2. Again click to select all [checked state]
 
#### Expected Behavior

The checkbox in the header should be in checked state.

#### Actual Behavior

The checkbox in the header displays unchecked.

#### Environment

- Angular: 8.0.0
- CDK/Material: 8.0.0
- Browser(s): Safari
- Operating System (e.g. Windows, macOS, Ubuntu): macOS

<img width="1448" alt="Screenshot 2019-09-17 at 3 26 53 PM" src="https://user-images.githubusercontent.com/501259/65032157-3fae8300-d960-11e9-8715-9318cac9f540.png">

**Comment by mmalerba** [comment]
I think since you're trying to implement custom logic on click here, you probably want to set teh click action to `noop` (see https://material.angular.io/components/checkbox/overview#click-action-config) and then implement your own logic to update the state as desired.

Alternatively you can use `$event.preventDefault()` to stop the default action of toggling the checkbox and implement your own logic.
