### ISSUE TITLE
placeholder not appearing in IE11

### ISSUE THREAD

**Issue by michael-letcher** [angular/components#17243]
#### Reproduction

Use StackBlitz to reproduce your issue: https://stackblitz.com/angular/mkagoelgeyo

Steps to reproduce:
1. Open in IE 11
 
 
#### Expected Behavior
To see the words "Simple placeholder" when selecting the "Both a label and a placeholder" field.

#### Actual Behavior
No words appear when selecting the field.

#### Environment

- Angular: 8.2.1
- CDK/Material: 8.2.1
- Browser(s): IE 11 (11.737.17763.0)
- Operating System (e.g. Windows, macOS, Ubuntu): Windows 10

#### Other Notes
I don't mind if this IE being IE and it's not supported. But it would be good to add a foot note on what is expected to be unsupported.

**Comment by crisbeto** [comment]
It seems like the Stackblitz link is invalid.

**Comment by michael-letcher** [comment]
@crisbeto Sorry, fixed. It's just one of the default stackblitz from the Material site.

**Comment by crisbeto** [comment]
I don't think it's a bug, it's just how IE handles placeholders. In most browsers the placeholder is only hidden if there's a value, but IE hides it whenever the input has focus. E.g. if you set "Float label" to "always" you'll be able to see it. Closing since there's not much we can do about it, aside from re-implementing the placeholder behavior from scratch.
