### ISSUE TITLE
Mat-Select scroll bar displayed off page or behind page scroll bar

### ISSUE THREAD

**Issue by stpwebdev** [angular/components#17438]
#### Reproduction

Stackblitz: https://stackblitz.com/edit/angular-xrksc1

screenshot: 
![image](https://user-images.githubusercontent.com/49412779/67042316-a1941100-f0f5-11e9-81af-839b5fd6c224.png)

Steps to reproduce:
1. Create a mat-select component directly in the page body with enough options that a vertical scroll bar should appear. The scroll bar will display off-screen. (Example 1 in stackblitz, comment out the div.expand-page element)
2. Create a mat-select component, set it's width and float it right. Add enough options that the vertical scroll bar appears. Create a div below the mat-select element and set its height to 150vh to make a scroll bar appear on the body element. Now the mat-select component's scroll bar will be hidden behind the body elements scroll bar.
 
 
#### Expected Behavior

What behavior were you expecting to see?
The mat-select vertical scroll bar should always be visible if it exists.

#### Actual Behavior

What behavior did you actually see?
The mat-select scroll bar gets hidden either off-screen or behind other scroll bars

#### Environment

- Angular: 8.2.11
- CDK/Material: 8.2.3
- Browser(s): Google Chrome: Version 77.0.3865.120 (Official Build) (64-bit)
- Operating System (e.g. Windows, macOS, Ubuntu): Windows 10 Pro: version 1809

**Comment by stpwebdev** [comment]
The same issue is present in Angular 9

- Angular 9.0.1
- CDK/Material: 9.0.0
- Browser: Google Chrome: Version 80.0.3987.87 (Official Build) (64-bit)
- Operating System (e.g. Windows, macOS, Ubuntu): Windows 10 Pro: version 1909

**Comment by madmurl0c** [comment]
This issue is still present in Angular 13.

Angular: 13.0.0
CDK/Material: 13.3.1
Browser: Google Chrome Version 99, Microsoft Edge Version 99
Operating System (e.g. Windows, macOS, Ubuntu): Windows 11

I reproduced the issue in the stackblitz mat-select example: https://stackblitz.com/edit/angular-1pnvan

It's _fixed_ if you select the `<div role="listbox"...>` and disable the `min-width` property:
![image](https://user-images.githubusercontent.com/42262826/160573557-006d9ea6-f0dc-4641-9dbe-de0e6c4dd3b2.png)
It probably isn't this easy to fix but maybe this helps finding the issue.

Would you consider changing the priority of this issue?

**Comment by amysorto** [comment]
This is fixed in the MDC based select component available in v15 soon.
