### ISSUE TITLE
Update material root import schematic to function with v9

### ISSUE THREAD

**Issue by jelbourn** [angular/components#17433]

**Comment by devversion** [comment]
To give some context. We currently rely on the type checker to figure out where imports to `@angular/material` resolve to. This won't work in v9 anymore because we removed the primary entry-point.

This means that we either leave the migration broken and say that people should sequentially update to v8 and then to v9, or we fix it by introducing some logic to map imported symbols to their entry-point.

We decided that we want to create a map that can be used to lookup the entry-point for a given symbol by name. This map can be most likely generated through the TS compiler API.
