### ISSUE TITLE
Empty cdkList container "lose drop area" if its position changes.

### ISSUE THREAD

**Issue by ajeiie120120** [angular/components#17736]
#### Reproduction

Hi, i've found some weird issue using a simple empty div as "drop container" in order to show users a box where to drop contents into.
It seems that if this box, for whatever reason, changes its visibility, position, etc... it loses the "drop capability".

Here's the stackblitz used to reproduce the bug:

https://stackblitz.com/edit/angular-hqxu2m

Steps to reproduce:
1. Test the example dragging a "done" element into the "to do" list (a "exited" console log should appear each time you enter the "to do" container while dragging an element)
2. In the template file, uncomment the second line (as suggested by the comment) and retry the step 1, now it's impossibile to make the console log"exited" again
 
 
#### Expected Behavior

The drop zone of the container should be always active

#### Actual Behavior

The drop zone of the container is lost whenever the container is moved around or it's visibility changes

#### Environment

- Angular: 8.2.14
- CDK/Material: 8.2.3
- Chrome: 78.0.3904.97
- Operating System :  Windows

**Comment by mushyak** [comment]
I experience the same issue with Angular 8.2.11, Material: 8.2.3.

**Comment by ajeiie120120** [comment]
Any news?

**Comment by ajeiie120120** [comment]
Up

**Comment by ajeiie120120** [comment]
Any help?

**Comment by james-logan** [comment]
Up. Also experiencing this. 

Potentially a related issue here: https://github.com/angular/components/issues/18638

**Comment by ekselys** [comment]
Issue still present with the latest dependencies, the stackblitz example has been updated.

It's quite critical, is there any workaround?

**Comment by matthewerwin** [comment]
https://github.com/angular/components/issues/19085

**Comment by matthewerwin** [comment]
The drop area "client rect" is cached for performance according to the comments in the code which would result in problems with animations (which the code tries to account for) though there are many reasons content could shift (such as the removal of the drag element during drag), use of *ngIf="dragging" on a drop zone you wish to show only when dragging is available, or [hidden].

Caching the clientrect to me seems unreliable since even mouse movement can be a trigger for changes (e.g. highlighting a dropzone on mouse-over).

I have some separate scenarios I set up of drop zone being "lost" or not found in the first place even without changes to the position: https://github.com/angular/components/issues/19085

**Comment by crisbeto** [comment]
Falls in the same category as https://github.com/angular/components/issues/14703 where the logic breaks down if the size changes after we've cached it.
