### ISSUE TITLE
[MatTable] ViewChildren returns MatRow in incorrect order if you add new rows in the middle of the table

### ISSUE THREAD

**Issue by glushkova91** [angular/components#17816]
#### Reproduction

Use StackBlitz to reproduce your issue: https://stackblitz.com/fork/components-issue

Steps to reproduce:
1. Open https://stackblitz.com/edit/components-issue-rhyhnz?file=app/app.component.ts
2. Click "Add Element button"
3. Verify displayed rows - it's inserted in the middle of the table
4. Check console with ViewChildren log - it inserts in the end of query list.
 
 
#### Expected Behavior

ViewChildren for mat table rows should return data in according to the table model and view.

#### Actual Behavior

When you add new row to the mat table in random place ViewChildren always adds it to the end

#### Environment

- Angular: Google
- CDK/Material: Google
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Google Chrome

**Comment by crisbeto** [comment]
I've looked into it and the short answer is that it's how the framework works and there's not much we can do about it.

The longer answer needs a bit of context: the way `mat-table` renders rows is by taking the `TemplateRef` from the `matRowDef` and stamping it out for each row of data in the data source via `ViewContainerRef.createEmbeddedView`. Views/templates like this that are declared in one place, but instantiated in another one are called "transplanted views" and Angular always puts them at the end of the `QueryList`. Because these views can be inserted into different containers at the same index, the framework can't maintain the same index in the `QueryList` as in the DOM so it falls back to using the insertion order. I'm closing the issue, because we most-likely can't work around this without rethinking how `mat-table` is set up. If the order is important for your use case you can sort the results yourself afterwards based on the DOM order.
