### ISSUE TITLE
mat-tab-header-pagination appears when last item is removed

### ISSUE THREAD

**Issue by SergiuIlciucAssist** [angular/components#17943]
#### Reproduction

Link to StackBlitz: https://stackblitz.com/edit/components-issue-f4qk18

Steps to reproduce:
1. Put the mat-tab-group inside a div with "display: flex"
2. Select the last item in the group.
3. Remove the last item that is also selected.
 
#### Expected Behavior

The pagination arrows should not appear because there is enough space.

#### Actual Behavior

Pagination arrows are shown

#### Environment

- Angular: 8.2.14
- CDK/Material: 8.2.3
- Browser(s): Chrome, Opera
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

#### Observation

If I remove the mat-ink-bar, this does not reproduce anymore.

**Comment by JGSolutions** [comment]
Getting the same issue

**Comment by jelbourn** [comment]
The issue here is that, by putting the tabs in a flex container, you're changing the width calculation for the tab group. In this case, the width of the tab group exceeds the size of its container. If you set the tab group to be the width of its container (e.g. `width: 100%`), that would resolve the problem.
