### ISSUE TITLE
cdkDragPlaceholder acting weird when display is none inside cdkDropListGroup

### ISSUE THREAD

**Issue by maddy25** [angular/components#18149]
#### Bug, feature request, or proposal:
{cdk-drag-placeholder display: none}  is  adding extra animation when added inside cdkDropListGroup

#### What is the expected behavior?
It should hide the target placeholder without moving the dragged element somewhere else first.

#### What is the current behavior?
Currently when trying to move an item from one list to other, the item first flies on top or side and then drops to target. It only happens when 
```<div *cdkDragPlaceholder style="display: none"></div>``` is placed inside cdkDropListGroup

#### What are the steps to reproduce?
Providing a StackBlitz reproduction is the *best* way to share your issue. <br/>
StackBlitz starter: https://goo.gl/wwnhMV<br/>
https://stackblitz.com/angular/qoljprkjkok?file=src%2Fapp%2Fcdk-drag-drop-disabled-sorting-example.html

#### What is the use-case or motivation for changing an existing behavior?
Not changing exisiting behavior

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 8

**Comment by maddy25** [comment]
For some reason the unable to save and share stackblitz. Plz add
<div *cdkDragPlaceholder style="display: none"></div>
inside <div cdkDrag></div> for both the lists.

**Comment by matthewerwin** [comment]
@maddy25 that's because you're removing the "placeholder" from the display. Which means when you let go of the item has no calculated return position (browser cannot find position/size of a hidden element). You would get similar behavior if you added [hidden] or *ngIf="false" to it --possibly they could add a ::after or ::before to mitigate like .placeholder::before {content: ''} to avoid flying to 0, 0 when trying to get position of a hidden element though that also has side-effects.


To obtain your desired behavior (collapsing down the whitespace instead of a blank white area) you can just change to a non-block tag like so:

`<span *cdkDragPlaceholder></span>`

However, since it's both a source & target placeholder for the dragged item you will also not see any indicator of it being moved into the target list. Perhaps a future enhancement would allow placeholders to be defined by the drop target and drag source separately.

**Comment by crisbeto** [comment]
Closing since there hasn't been any activity in a while and there's a workaround.
