### ISSUE TITLE
mat-slider: disable special styling on minimum value

### ISSUE THREAD

**Issue by dmarku** [angular/components#18298]
#### Feature Description

If a `<mat-slider>` is set to its minimum value, it adds a special class (`.mat-slider-min-value`) that changes the styling of the slider thumb. It would be useful to disable this behavior or adjust the value where this "resting state" occurs.

#### Use Case

In our scenario, the slider ranges from negative to positive values, so the minimum value is not semantically different to other values (except maybe the zero position). It would be nice to visually represent this equality.

**Comment by devversion** [comment]
This will be fixed in the MDC-based implementation of the slider we are working on. At first glance, it looks like the Material Design specification no longer has special styles for the minimum value.

**Comment by thw0rted** [comment]
Would you consider leaving the existing styling in place and instead separating out the "min" and "default" values?  So, `<mat-slider min="-10" max="10" default="0">` would show the same special styling as the `.mat-slider-min-value` class currently provides, but only when the slider is positioned at the value zero -- i.e., the exact middle of the range.  That would also neatly solve the case that led me to find this issue: I want a slider that runs from 20-100, with a falsy "default" so that it never uses the `min-value` styling.

**Comment by hannounf** [comment]
Hello,
Any updates or other suggestions to solve this?

**Comment by zreptil** [comment]
Why is there this special behavior? As @sdalexandre stated, the only meaningful usage for this feature is that the minimum value has a speacial meaning like empty or invalid. But when i use a slider, my normal usecase is to give the user the possibility to select a value from a range of values, where the minimum is equal in value to all the other values up to the maximum. The case that angular states as the normal case is in my opinion the special case that should be enabled with an attribute or at least be possible to disable with an attribute.

**Comment by ger-benjamin** [comment]
With a bigger thumb-label, the min-value class is useful to set the label placement. But sadly, there is no equivalent for "max-value".
This inconsistency is annoying. Please, add max-value, or replace min-value by default value, or remove min-value to be consistent.
The more flexible would have a class info for each tick.

**Comment by Mateusz19021996** [comment]
exactly, why we can't set special style / color on min / max value? specially for min

**Comment by wagnermaciel** [comment]
Hi folks! The new MDC slider came out in v15 and I believe this is no longer relevant since there's no special styling on the minimum value anymore

For additional context, this is not something we plan to bring back because 1. it diverges from the latest Material design spec and 2. this seems really trivial to add back in if you really want it

E.g.

```html
<mat-slider
    [color]="mySliderThumb.value === mySlider.min || mySliderThumb.value === mySlider.max ? 'warn' : 'primary'"
    #mySlider>
        <input #mySliderThumb="matSliderThumb" matSliderThumb>
</mat-slider>
```
