### ISSUE TITLE
matDatepickerFilter calls filter function even if the date is not withing min and max inputs

### ISSUE THREAD

**Issue by chandrasagarjain** [angular/components#18411]
#### Reproduction

Use StackBlitz to reproduce your issue: https://stackblitz.com/edit/angular-mat-datepicker-jajkwy

Steps to reproduce:
1. Click on date viewer
2. Check the console 
 
 
#### Expected Behavior

What behavior were you expecting to see?
That matDatepickerFilter function is not called if the date in calender is not within min and max values

#### Actual Behavior

What behavior did you actually see?
matDatepickerFilter function is called for all dates 

#### Environment

- Angular: (8.3.8)
- CDK/Material:8.1.2
- Browser(s):Chrome
- Operating System (e.g. Windows, macOS, Ubuntu):   Windows

**Comment by mimedo** [comment]
Based on the [documentation](https://material.angular.io/components/datepicker/overview) you use either `min/max` or `matDatepickerFilter` validation, and not combined.
Because you don't have any validation implemented in your `myFilter` function, it will output you for any date in console.
To find the solution to your initial idea, can you please explain in more detail?
