### ISSUE TITLE
Mat-option div being generated dynamically outside app-root and makes component unit testing difficult

### ISSUE THREAD

**Issue by Ahnert1** [angular/components#18452]
My component uses `<mat-option>`s to display some options from an API call. The `<mat-option>` div(s) appear at the root level of the application, instead of being nested in the component which it was declared.  **This makes testing extremely difficult.**  

As a workaround, I am using `document.querySelectorAll("mat-option")` to locate the element(s). I'm not sure if this is good practice, and I'm also not sure how to interact with the element after that. Ideally, I would prefer to use my component's `fixture` for locating the `<mat-option>` divs.

Also now that Angular 9 is out which supports `Harnesses` for testing, I would prefer to use the following line of code for retrieving `<mat-option>s`:
`const options = await loader.getAllHarnesses(MatOptionHarness);`
I don't see how its possible for this line of code to **ever** work if the `<mat-option>` divs are being generated dynamically outside of the component in which it was declared (and the component being tested).

**Comment by crisbeto** [comment]
We have to put the overlays at the end of the body in order to avoid issues with `overflow: hidden` and to simplify focus management. Closing the issue since it has always been this way and it's unlikely to change.

As for getting the options that belong to a select or autocomplete, the `MatAutocompleteHarness` and `MatSelectHarness` expose the options that belong to them already.
