### ISSUE TITLE
isInsideClientRect() logic in drop-list-ref.ts is incorrect

### ISSUE THREAD

**Issue by Anton2478** [angular/components#18505]
Current logic is:

```javascript
function isInsideClientRect(clientRect, x, y) {
    var top = clientRect.top, bottom = clientRect.bottom, left = clientRect.left, right = clientRect.right;
    return y >= top && y <= bottom && x >= left && x <= right;
}
````

but should be `y < bottom` and `x < right` because `right === left + width` and `bottom === top + height`.
This function is used many times in D&D checks and always adds 1 wrong pixel in each direction.

**Environment:**
angular: 8.2.13
material/CDK: 8.2.3

**Comment by crisbeto** [comment]
I guess it depends on the point of view. When I wrote it my thinking was that as soon as it overlaps one of the edges, it's considered as being inside. Either way, this probably won't be noticeable anyway, because we extend the area around the drop container by 5% of its size to make it easier to drop into.
