### ISSUE TITLE
PeerDependency bug

### ISSUE THREAD

**Issue by rcketscientist** [angular/components#18536]
#### Reproduction

Use StackBlitz to reproduce your issue: https://stackblitz.com/fork/components-issue

Steps to reproduce:
1. `ng update packageThatDependsOnMaterial8`
 
#### Expected Behavior

What behavior were you expecting to see?
It updates `packageThatDependsOnMaterial8`, as well as updating Material/CDK to 8.

#### Actual Behavior

What behavior did you actually see?
```
                  Package "@keysight/alloy" has an incompatible peer dependency to "@angular/common" (requires "^8.1.1", would install "9.0.1")
                  Package "@keysight/alloy" has an incompatible peer dependency to "@angular/core" (requires "^8.1.1", would install "9.0.1")
                  Package "@keysight/alloy" has an incompatible peer dependency to "@angular/cdk" (requires "^8.2.3", would install "9.0.0")
                  Package "@keysight/alloy" has an incompatible peer dependency to "@angular/material" (requires "^8.2.3", would install "9.0.0")
                  Package "@keysight/alloy" has an incompatible peer dependency to "@angular/cdk" (requires "^8.2.3", would install "9.0.0").
                  Package "@keysight/alloy" has an incompatible peer dependency to "@angular/material" (requires "^8.2.3", would install "9.0.0").
                  Package "@angular-devkit/build-angular" has an incompatible peer dependency to "typescript" (requires ">=3.1 < 3.6", would install "3.7.5").

Incompatible peer dependencies found.
Peer dependency warnings when installing dependencies means that those dependencies might not work correctly together.
You can use the '--force' option to ignore incompatible peer dependencies and instead address these warnings later.
```

#### Environment

- Angular: 8
- CDK/Material: 8

Alloy `peerDependencies`:
```
    "peerDependencies": {
        "@angular/common": "^8.1.1",
        "@angular/core": "^8.1.1",
        "@angular/cdk": "^8.2.3",
        "@angular/material": "^8.2.3"
    },
```

This seems to be the culprit (Material peerDependencies):
```
  "peerDependencies": {
    "@angular/animations": "^8.0.0 || ^9.0.0-0",
    "@angular/cdk": "8.2.3",
    "@angular/core": "^8.0.0 || ^9.0.0-0",
    "@angular/common": "^8.0.0 || ^9.0.0-0",
    "@angular/forms": "^8.0.0 || ^9.0.0-0"
  }
```

Currently, we're instructing our consumers to remove Material, upgrade Alloy, then restore Material.

**Comment by devversion** [comment]
This seems to be something specific to the Angular CLI. Unless I misread this issue, it sounds like the issue is that the CLI should not try updating to version 9 of Angular, but rather just be satisfied with updating to version 8 of Angular. Right?

**Comment by rcketscientist** [comment]
Yes, but _why_ is Material upgrading beyond the version defined in the `peerDependency` and why is it the only library demonstrating this behavior?  As I mentioned I can remove Material and upgrade as expected.  Then manually handle the Material upgrade.  I suspect this is involved:

```
  "peerDependencies": {
    "@angular/animations": "^8.0.0 || ^9.0.0-0",
    "@angular/cdk": "8.2.3",
    "@angular/core": "^8.0.0 || ^9.0.0-0",
    "@angular/common": "^8.0.0 || ^9.0.0-0",
    "@angular/forms": "^8.0.0 || ^9.0.0-0"
  }
```

Why does material 8 have these loose version ranges, why is 9 acceptable (before it was even released)?

The following issue is not particularly helpful as it was closed without a true solution, but it's how I realized simply removing Material would allow me to `ng update` properly:

https://github.com/angular/angular-cli/issues/14980

**Comment by devversion** [comment]
The peer dependencies for `8.x` are set to `9.x` because it's totally possible to use a more recent major version of the Angular framework, while still using the older Angular Material/CDK version. This is part of the backwards compatibility that Angular guarantees. 

I'd recommend creating another issue on the CLI repository for this. We won't be able to do anything about this from our side I guess. Happy to discuss more if you think differently.

In summary, my thinking is still that it's a bug in the CLI. It should be able to find a version of the CDK, Material that satisfies all peer dependencies. i.e. in this concrete example:

1. It looks for peer dependencies in `alloy`. Figures out that it needs `@angular/*` 8.x.
2. It fetches package metadata for `@angular/*`. Recursively looks in peer dependencies for these packages.
   2.1. Finds peer dependencies in `@angular/material`.
   2.2. Compares these peer dependency ranges against the "to-be-installed" packages. All good. 
3. Applies update. All `@angular/*` packages will be updated to their latest `8.x` release.

**Comment by rcketscientist** [comment]
I see what you're saying.  Really frustrating that we have to describe such a quack work-around for consumers with CLI closing reports of these issues, but I'll whine over there again, lol.
