### ISSUE TITLE
mat-button-toggle-group [disable] input does not disable functionality, only greys out the buttons

### ISSUE THREAD

**Issue by GiedreUsaviciute** [angular/components#18563]
#### Reproduction

Steps to reproduce:
1. create mat-button-toggle-group component
2. add [disabled]="true" (dynamic input)
3. add (click) event function call on mat-button-toggle
 
 
#### Expected Behavior

What behavior were you expecting to see?

buttons should be disabled and not clickable, onclick would not fire an event

#### Actual Behavior

What behavior did you actually see?
buttons are displayed as disabled but are also clickable and fires click event

#### Environment

- Angular: 8
- CDK/Material: 8.2.3
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu):  windows

**Comment by crisbeto** [comment]
The functionality that prevents event listeners from firing on disabled elements only applies to native elements (e.g. `button`, `input`), it's not something that Material has implemented. Since `mat-button-toggle-group` is a custom element, the browser won't know what to do with its events. Closing since handling the issue since this isn't something we're responsible for.
