### ISSUE TITLE
Parent does not scroll when dragging and dropping 

### ISSUE THREAD

**Issue by GitHubish** [angular/components#18671]
I have an app with boards like Trello. So I have a concept of board, column and card. 
If I reorder the columns by trying to move it out of the "screen" the board scrolls sideways.
If I try to move a card in a column out of the "screen", the board doesn't scroll. 
I thought adding withScrollableParents would solve my problem but it still doesn't work.

How does it work withScrollableParents? Thanks

Project structure:
Board component --> column component --> card component

**Comment by crisbeto** [comment]
Are you using any of the directives or the `DropListRef` directly? `withScrollableParents` is used to indicate which parents are able to scroll, but it might not be working as you'd expect if you're doing it through the directive.

**Comment by GitHubish** [comment]
Hi @crisbeto 

This is what I use in the column component:
`cdkDropList [cdkDropListData]="column?.cards" [cdkDropListConnectedTo]="connectedList"`

And this is what I use in the board component:
```
<div class="column" *ngFor="let column of board.columns" cdkDrag [cdkDragData]="column">
      <my-column [column]="column" [connectedList]="connectedList">my-column>
</div>
```

If I understand your question correctly, it seems that I use DropListRef, but I don't understand why that wouldn't work. And how can I make the desired behavior work?

Thank you

**Comment by GitHubish** [comment]
example: 
https://stackblitz.com/edit/angular-mzjxws?file=src%2Fapp%2Fapp.component.html

**Comment by GitHubish** [comment]
@crisbeto does my example and my explanations help you better understand my problem? Thanks

**Comment by Achilles1515** [comment]
@GitHubish 
The easiest way to add this ability is with the `cdkScrollable` attribute.

app.module.ts
```ts
// ...
import { DragDropModule } from '@angular/cdk/drag-drop';
import { ScrollingModule } from '@angular/cdk/scrolling'
// ...

@NgModule({
  imports: [/*...*/ DragDropModule, ScrollingModule],
  declarations: [AppComponent],
  bootstrap: [AppComponent]
})
export class AppModule { }
```

Then on your `col_container` div, add the cdkScrollable attribute.
```html
<div
  cdkDropList
  cdkDropListOrientation="horizontal"
  [cdkDropListData]="board.columns"
  (cdkDropListDropped)="onDrop($event)"
  class="col_container"
  cdkScrollable
>
    <!-- ... -->
</div>
```

The draggables will automatically pick up this `cdkScrollable` container as an element that can be auto-scrolled.

Note that [these recently merged commits](https://github.com/angular/components/commit/ca18f6d60e2273b4241a4203fafd2bf35f6f719f) will soon make it so you don't have to import the `ScrollingModule` and you'll just be able to do:

```ts
import { DragDropModule, CdkScrollableModule } from '@angular/cdk/drag-drop';
```

in order to get access to `cdkScrollable`.

Here is a fork of your StackBlitz.
[https://stackblitz.com/edit/angular-63q7b2?file=src/app/app.module.ts](https://stackblitz.com/edit/angular-63q7b2?file=src/app/app.module.ts)

**Comment by GitHubish** [comment]
It works ! Thanks very much !
