### ISSUE TITLE
bug(MatSidenavModule): ExpressionChangedAfterItHasBeenCheckedError if check is before <mat-drawer>

### ISSUE THREAD

**Issue by DanielHabenicht** [angular/components#18764]
#### Reproduction

https://stackblitz.com/edit/angular-im8vk6?file=src%2Fapp%2Fsidenav-drawer-overview-example.html
Steps to reproduce:
 - Use `drawer.opened` outside of `<mat-drawer-container>`
 - Use `drawer.opened` before  `<mat-drawer>`
 
 
 
#### Expected Behavior

What behavior were you expecting to see?
No Error.

#### Actual Behavior

What behavior did you actually see?
```
Error: ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: 'ngIf: false'. Current value: 'ngIf: true'.
```

#### Environment

- Angular: 9.0.5
- CDK/Material: 9.0.5
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Windows 10

Might be related: https://github.com/angular/components/issues/18431

**Comment by RemyAlves** [comment]
Expresion changed after it has been checked error with the drawer on my side too

**Comment by crisbeto** [comment]
This is one of the differences between Ivy and ViewEngine [described here](https://angular.io/guide/ivy-compatibility-examples#forward-references-to-directive-inputs-accessed-through-local-refs-are-no-longer-supported). Closing since it's at the framework level and there isn't much we can do about it on our end.
