### ISSUE TITLE
bug(mat-dialog): First click in mat-dialog not working

### ISSUE THREAD

**Issue by DomJo** [angular/components#18808]
#### Reproduction

Use StackBlitz to reproduce your issue: https://stackblitz.com/edit/angular-pefszd

Steps to reproduce:
1. Click to open dialog.
2. Click big button in dialog.
3. click handler is executed only on second click
 
 
#### Expected Behavior

Alert from (click) handler

#### Actual Behavior

Alert opens only the second time the button is pressed.

It works fine if any of these changes are done:
- ngFor over an array field, instead of a method returning the array.
- element in the array is a number instead of an object
- remove the ok button

#### Environment

- Angular: 9.0.6
- CDK/Material: 9.1.2
- Browser(s): Chrome 80
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

**Comment by crisbeto** [comment]
It's because you're returning a new array every time `fun` is called. This means that whenever any event happens, you get a completely new button. The first time the click doesn't work, because moving focus causes it to be recreated in the middle of the click sequence. Closing since this isn't an issue in Material.
