### ISSUE TITLE
fr(cdk/coercion): coercion decorators

### ISSUE THREAD

**Issue by klemenoslaj** [angular/components#18840]
#### Feature Description

Instead of repetitive

```ts
@Input()
set disabled(disabled: boolean) {
  this._disabled = coerceBooleanProperty(disabled);
}
get disabled() {
  return this._disabled;
}
private _disabled = false;
```

We could write:

```ts
@Input()
@CoerceBoolean()
disabled = false;
```

#### Use Case

Describe the use case(s) that the proposed feature would enable.

I think the coercion methods the CDK provides are super useful as they are for anyone writing serious libraries. I do however find myself writing the same setters and getters over and over again, and in conjunction with `strictTemplates` and `ngAcceptInputType_*` this get's a bit cumbersome.

So I am wondering now if maybe we could get some decorators in place instead? Are there any serious downsides to it that I fail to see at the moment?

A first POC `CoerceBoolean` decorator:

```ts
function CoerceBoolean() {
  return function(target: object, propertyKey: string, descriptor?: PropertyDescriptor) {
    let _value = false;

    return Object.defineProperty(target, propertyKey, {
      set(value: BooleanInput) {
        _value = coerceBooleanProperty(value);
        descriptor?.set?.(_value);
      },
      get() {
        return descriptor?.get?.() ?? _value;
      },
      configurable: descriptor?.configurable,
      enumerable: descriptor?.enumerable,
    });
  };
}
```

**Comment by crisbeto** [comment]
This would have to happen at the framework level, because the Angular compiler strips away its decorators during compilation.

**Comment by devversion** [comment]
Correct. View Engine does not strip decorators away at all. Ivy only strips Angular-known decorators away. Angular build-optimizer only strips known Angular decorators either. 

So that definitely could work. If I recall correctly though, there were implications in terms of tree-shaking. I think we can track this as an upstream issue as the components team believes in this being something that should be addressed at framework level.

* https://github.com/angular/angular/issues/8968.
* https://github.com/angular/angular/issues/14761
