### ISSUE TITLE
bug(mat-checkbox): Checkbox ngModel bind not working if there's a form in the page

### ISSUE THREAD

**Issue by Nephyron** [angular/components#18889]
#### Reproduction

https://stackblitz.com/edit/components-issue-jvfsjf?file=src/app/example-component.html

Steps to reproduce:
1. add a checkbox to a page
2. add a form to a page
 
 
#### Expected Behavior
mat-checkbox value should match ngModel value

#### Actual Behavior

mat-checkbox matches the ngModel value only if it has a unique name when there's a form in the page, works well even without name when there's no form

#### Environment

- Angular: 8+
- CDK/Material: 8+
- Browser(s): any
- Operating System (e.g. Windows, macOS, Ubuntu): any

**Comment by crisbeto** [comment]
The problem example isn't the `name` of the `form`, it's that you have a reference to the form called `test` (`#test="ngForm"`) which you're passing further down into the `formControl` of the checkbox. That's invalid since the `formControl` input expects a `FormControl` object.

Another issue is that you aren't supposed to have both `ngModel` and `formControl` on the same element. You're supposed to use one or the other.
