### ISSUE TITLE
bug(dialog): JSONEditor inputs not working in material dialog

### ISSUE THREAD

**Issue by Luminoth** [angular/components#18984]
#### Expected Behavior

Angular Material dialog with a JSONEditor (https://github.com/josdejong/jsoneditor) object embedded in it would allow editing of text fields in the JSON editor.

#### Actual Behavior

Angular Material dialog with a JSONEditor object embedded in it no longer allows editing of text fields. Non-text fields work correctly.

The JSONEditor object uses a contenteditable div as such:

```
<div contenteditable="true" spellcheck="false" class="jsoneditor-value jsoneditor-string" title="">my text</div>
```

rather than an HTML input field. Keyboard input currently is ignored and dragging to select text instead drags the dialog around the window. The JSONEditor object's search field, which is an HTML text input, functions as expected so it's likely some interaction between Material and the contenteditable div that is the problem.

#### Environment

- Angular: 9.1.0
- CDK/Material: 9.2.0
- Browser(s): Chrome 80.0.3987.149
- Operating System (e.g. Windows, macOS, Ubuntu): Windows 10

**Comment by devversion** [comment]
Hello! would you be able to provide a small reproduction? I don't think we have the resources to build up these demos on our own. That would be great. Thanks!

**Comment by Luminoth** [comment]
Yeah definitely, sorry it took a couple days to get back. I think it might actually be related to using cdkDrag on the dialog, going through building out the example here. There repo here: https://github.com/Luminoth/jsoneditor-dialog should be able to reproduce it.

Basically click the button to open the dialog, append a field to the object, give the field a name and value and then click outside of it so it de-selects the text input. From that point on, any attempt to interact with the field fails - dragging to select text drags the dialog rather than selecting, clicking inside the text won't move the cursor, probably some other issues but those are the most observable ones.

**Comment by Luminoth** [comment]
Does that example cover the issue well enough @devversion ?

**Comment by devversion** [comment]
@Luminoth Sorry for the delayed response on my end (lots of things going on). Thanks for getting back with a reproduction! I've looked into it and moved it over to a StackBlitz (missing icons though): https://stackblitz.com/edit/github-ynaqqd?file=src/app/json-editor-dialog/json-editor-dialog.component.ts

It looks like you applied `cdkDragHandle` to the same element that has `cdkDrag` applied. This means that `cdkDragHandle` will be a noop and the whole dialog container (drag root element) is used as handle for dragging (causing selection to be broken and other effects).

The  `cdkDrag` directive can and will only match `CdkDragHandle` instances through content children. That means that the currently placed `cdkDragHandle` is a noop (as said). If you'd create a child element that has the drag handle, everything should work as expected.

_Note_: This worked differently in View Engine as `CdkDrag` could match the drag handle on its host element. This behavior was due to a bug and has been fixed: https://github.com/angular/angular/issues/10098

**Comment by devversion** [comment]
Can you let me know if that works for you? I don't think there is anything we could do from our side.

**Comment by Luminoth** [comment]
Awesome, thank you for moving it to the stackblitz. I checked out a solution there and it worked perfectly. I'll be able to apply that to our codebase either tomorrow or the day after, but I'm pretty confident it's going to work out. I appreciate you taking the time to look at that for me!
