### ISSUE TITLE
bug(matDialogActions): Button with type="button" triggers submit

### ISSUE THREAD

**Issue by jkossis** [angular/components#19005]
#### Reproduction

https://stackblitz.com/edit/components-issue-q9j6kz

Steps to reproduce:
1. Open the modal
2. Click the 'Clicking should not trigger form validation' button in the modal
 
#### Expected Behavior

Form validation should not be triggered. Normally, providing type="button" allows for a button to be clicked in a form and not act as a submit.

#### Actual Behavior

Form validation is triggered.

#### Environment

- Angular: 9.0.2
- CDK/Material: 9.1.0
- Browser(s): Chrome 80.0.3987.163
- Operating System (e.g. Windows, macOS, Ubuntu): macOs 10.14.6

**Comment by crisbeto** [comment]
The validation is displayed, because the input is focused as the first focusable element in the dialog and it gets blurred when you click the button. Furthermore, the button isn't even in the form so there's no way for it to trigger the submit. You can either [change when the validation is shown](https://github.com/angular/components/blob/master/src/material/input/input.md#changing-when-error-messages-are-shown) or set the initial focus in the dialog to a different element using `cdkFocusInitial`.
