### ISSUE TITLE
help([CDK]): [enter is deprecated: No longer being used. To be removed]

### ISSUE THREAD

**Issue by ngohungphuc** [angular/components#19059]
#### What are you trying to do?
Implement drag and drop

#### What troubleshooting steps have you tried?
Already go through to document

#### Reproduction

https://stackblitz.com/edit/components-issue-wr1x6g?file=src%2Fapp%2Fexample-component.ts
 
#### Code snippets
```ts
import {Component,OnInit, ViewChild} from '@angular/core';
import {
    CdkDropList,
    CdkDropListGroup,
    CdkDrag,
    CdkDragMove,
} from "@angular/cdk/drag-drop";

@Component({
  selector: 'example-component',
  templateUrl: 'example-component.html',
  styleUrls: ['example-component.css'],
})
export class ExampleComponent implements OnInit {
    @ViewChild(CdkDropList, { static: true }) placeholder: CdkDropList;

    ngOnInit() {
        
    }

   public dropListEnterPredicate = (drag: CdkDrag, drop: CdkDropList) => {
     // enter is deprecated: No longer being used. To be removed
        this.placeholder.enter(
            drag,
            drag.element.nativeElement.offsetLeft,
            drag.element.nativeElement.offsetTop
        );
        return false;
    }
    
}
```
#### Environment

- Angular: 9.1.1
- CDK/Material: 9.2.0

My question is there any replacement for the enter method since it will be removed in v10.0

**Comment by crisbeto** [comment]
These APIs (`enter`, `start`, `drop` etc.) are a leftover from when all of the logic was directly inside the directives. We ended up moving it out into `DragRef` and `DropListRef` since it provides a bit more flexibility so the recommendation for when you're doing something custom is to create your own directive and wrap the references returned from the `DragDrop` service. You can see how it's being consumed in the [drag](https://github.com/angular/components/blob/master/src/cdk/drag-drop/directives/drag.ts#L197) and [drop list](https://github.com/angular/components/blob/master/src/cdk/drag-drop/directives/drop-list.ts#L168) directives.

**Comment by crisbeto** [comment]
Closing since this is working as expected and the deprecated APIs have been removed.
