### ISSUE TITLE
bug([mat-date-picker]): [Material Datepicker misbehaves randomly]

### ISSUE THREAD

**Issue by ArulRozario** [angular/components#19070]
Date picker shows up empty. 

![Screenshot from 2020-04-14 13-38-01](https://user-images.githubusercontent.com/33756400/79201189-4ef1a280-7e55-11ea-9966-dcca46cd0178.png)
![Screenshot from 2020-04-14 13-37-43](https://user-images.githubusercontent.com/33756400/79201230-5d3fbe80-7e55-11ea-92e2-d2cb90ec6e14.png)

**Comment by crisbeto** [comment]
This isn't a lot of information to go on. It seems like whatever is formatting the date is throwing an error. Also what browser is the error being thrown on?

**Comment by ArulRozario** [comment]
It's in chrome. Ok in Edge

**Comment by crisbeto** [comment]
Judging purely from the stack trace, it looks like it's throwing because `Intl.DateTimeFormat` is undefined. The problem is that it has been supported in Chrome since v24 which was released back in 2013 so it's unlikely that you're on an earlier version. We'll need a reproduction case in order to investigate this further.

**Comment by ArulRozario** [comment]
@crisbeto  Thanks for your quick responses

**Comment by wagnermaciel** [comment]
Closing because this issue has been inactive for 2 weeks or more after follow up was requested.
