### ISSUE TITLE
bug(mat-sort-header): Cannot center the header text perfectly

### ISSUE THREAD

**Issue by YoungCatChen** [angular/components#19082]
#### Reproduction

Use StackBlitz to reproduce your issue: https://stackblitz.com/edit/angular-mat-sort-header-cant-center

Steps to reproduce:
1. Click on table header "Name" to make it active.
 
#### Expected Behavior

Both the active header and inactive headers should align vertically with the <td> cells, like "Hydrogen" and "1.0079".

#### Actual Behavior

Active header ("Name") aligns with <td> cells below, but inactive headers ("Weight", "Symbol", etc.) don't. The invisible arrow icons take around 18 pixels to the right of the header text, pushing the header texts to the left.

#### Environment

- Angular: 9.1.1
- CDK/Material: 9.2.1
- Browser(s): Chrome 81
- Operating System (e.g. Windows, macOS, Ubuntu): macOS 10.15.4

**Comment by Totati** [comment]
Just a missing css magic.
https://stackblitz.com/edit/angular-mat-sort-header-cant-center-nm6bag

**Comment by andrewseguin** [comment]
Rather than adding in negative margins, which can have unexpected consequences, it would be easier to add padding to the left of the sort button. 

```csss
::ng-deep .mat-sort-header-button {
  padding-left: 12px;
}
```

The reason to add 12px is because that is the width of the sort indicator (arrow). By adding 12 pixels to the left, you balance out the button's text.

https://stackblitz.com/edit/angular-mat-sort-header-cant-center-gygghq?file=src/app/table-sorting-example.css
