### ISSUE TITLE
bug(schematics): An unexpected error occurred: EPERM: operation not permitted, unlink

### ISSUE THREAD

**Issue by splincode** [angular/components#19110]
#### Reproduction

Steps to reproduce:
1. git clone https://github.com/ngxs-labs/data.git
2. ng add "@angular/material"

#### Expected Behavior

I use only devDependencies, but if I run `ng add "@angular/material"`, we have in package.json after

```
,
    "dependencies": {
        "@angular/animations": "^8.0.0 || ^9.0.0-0",
        "@angular/cdk": "~8.2.3",
        "@angular/forms": "^8.0.0 || ^9.0.0-0",
        "@angular/material": "~8.2.3",
        "hammerjs": "^2.0.8"
    }
```

which means
what is wrong

#### Actual Behavior

Correct add to section to devDependencies

#### Environment

- Angular: 8.2.14
- CDK/Material: 8.2.3
- Operating System (e.g. Windows, macOS, Ubuntu):  Windows

**Comment by jelbourn** [comment]
(revisiting older issues as part of a triaging fix-it)

Not sure what this issue is about since the title and the content seem to be talking about different things. Adding to `dependencies` is intended; `devDependencies` are generally used for development tools. I also just ran `ng add` with the latest version on Windows and everything worked. Feel free to file a new issue with more details if some problem persists.
