### ISSUE TITLE
bug(material/menu): EventListeners are not working when using getter for obtaining iterable

### ISSUE THREAD

**Issue by himanshugarg574** [angular/components#19205]
#### Reproduction

https://stackblitz.com/edit/angular-u6zmcr?file=src%2Fapp%2Fapp.component.ts
Steps to reproduce:
1. Just click on button
2. Click on an menu item 
3. nothing will be logged to console
 
 
#### Expected Behavior

Menu Items should be clickable. (click listener should receive events)

#### Actual Behavior

Menu Items are not clickable.

#### Environment

- Angular:
- CDK/Material: 9.2.1
- Browser(s): Chrome 81
- Operating System (e.g. Windows, macOS, Ubuntu):  Windows

**Comment by crisbeto** [comment]
That's because you're returning a new array on every change detection. This means that as soon as you put your pointer down, you actually get a completely new button element which will interrupt the click event. In general this is a bad practice, because it leads to excessive change detection and memory leaks.

**Comment by himanshugarg574** [comment]
Thank you for your explanation
