### ISSUE TITLE
Event delay when using material components inside web components

### ISSUE THREAD

**Issue by akshaybhat30** [angular/components#19269]
#### What are you trying to do?

The events in the dialog are delayed when material components are used inside web components.
eg. When using mat datepicker inside a kendo-ui grid, it works fine when we try to open it from a normal flow but when the same datepicker is accessed from a web component it misbehaves and 
does not open sometimes and sometimes it just appears as an empty white rectangle. 

In some cases, eg while clicking on a close icon inside a matDialog it takes some 5-10 seconds to close the dialog when opened inside a web component otherwise it works properly.

#### What troubleshooting steps have you tried?

Initial thought was that this might be an issue with the event detection in angular as we are running some code outside zone.js so tried to run this outside zone as well but did not work. Not sure about the exact issue.

What are you seeing that does not match your expectations? 

Would just need your insight to figure out if this is a known issue or something that we might be doing wrong.

  
#### Environment

- Angular: 8
- CDK/Material: 8.0.0
- Browser(s): google chrome
- Operating System (e.g. Windows, macOS, Ubuntu):  windows

**Comment by jelbourn** [comment]
This issue doesn't have enough information for the team to investigate. Please include:
* A reproduction of the issue (preferably via StackBlitz)
* Any relevant errors and stack traces
* Any relevant details about your build environment

That said, it _sounds like_ the problem is that something is running outside of the zone that should be *in* the zone.
