### ISSUE TITLE
_theming.scss: add !default to global vars to allow customization

### ISSUE THREAD

**Issue by yinonov** [angular/components#19302]
#### Feature Description

When creating a new theme object we are able to control part but not all colors. 
e.g. $dark-dividers which are part of a $foreground map are not customizable by default and needs a little workaround to actually make changes to it.

with sass new module system this can be achieved way more declaratively and easily, but variable such as $dark-dividers will need a _!default_ attribute

#### Use Case

// _theming.proxy.scss
```
@forward "~@angular/material/theming" with (
  $dark-dividers: #979797
);
```

will apply the new color to dividers and provide a better customization options.

**Comment by jelbourn** [comment]
See https://github.com/angular/components/issues/3152#issuecomment-298454851

We have no plans to ever publish our internal Sass variables to npm or otherwise make them a public API. FWIW, the practice of overriding Sass variables is also forbidden in Google's internal Sass style guide because the pattern is brittle and hard to reason about; we prefer always exposing explicit mixin and function APIs for customization.
