### ISSUE TITLE
bug(MatSnackBar): Snackbar not completly removed if there is a binding error

### ISSUE THREAD

**Issue by JeremyMahieu** [angular/components#19344]
This is an app with an intentional wrong binding. myCar is null and therefor the binding with myCar.make gives errors.

#### Reproduction
https://stackblitz.com/edit/components-issue-vj4qee

Steps to reproduce:
1. Wait 10 seconds
 
#### Expected Behavior
Snackbar should dismiss and be completly removed from DOM and create a new snackbar. Even if there is a binding error with something unrelated.

#### Actual Behavior
Snackbar's texts disappears but the background and shadow remains. Stays in the DOM. After a while there are many copies in the DOM and on screen. The text of new snackbars are never displayed.
No amount of dismissing or setting dismiss times fixes this.
![image](https://user-images.githubusercontent.com/23409814/81817573-3694a680-952d-11ea-95c2-8dc61708e05e.png)

#### Environment
- Angular: 9.0.2
- CDK/Material: 9.1.0
- Browser(s): Chrome, Firefox
- Operating System (e.g. Windows, macOS, Ubuntu): Windows 10

**Comment by lukaonik** [comment]
whenever you called snack-bar twice, it waits for the previous one to finish, so the new one could appear. 

```
  if (this._openedSnackBarRef) {
      // If a snack bar is already in view, dismiss it and enter the
      // new snack bar after exit animation is complete.
      this._openedSnackBarRef.afterDismissed().subscribe(() => {
        snackBarRef.containerInstance.enter();
      });
      this._openedSnackBarRef.dismiss();
    }
```
here you can see that the overlay is already created (that's why you see black boxes) and it waits the previous one to finish, to show you the message (call enter() function).
enter function just changes _animationState, from hidden to visible.
so whenever you have an exception in change detection cycle, animation which should hide the previous snackbar, never get's fired ( that's why snackbar is not cleared at all), and also the animation which should show your the message also never get's fired ( that's why you can't see the content).
SOLUTION: there is not easy way to find a workaround for this I think, the best way to solve this, is fixing binding error :P

**Comment by crisbeto** [comment]
I don't think we can do much about this case, because the error is happening in a component completely outside of the snack bar.

**Comment by AStove** [comment]
And what's reason to make the overlay before the other one is dismissed?

**Comment by lukaonik** [comment]
I don't think there is any special reason for that. They are using cdk/overlay internally and maybe not to waste any time for creation. it's already there and just animated.

**Comment by crisbeto** [comment]
I spent some time investigating this, but forgot to post my findings. Recovering from these errors is tricky without sprinkling `try/catch` around the entire snack bar module. The most practical solution is to fix your error.
