### ISSUE TITLE
`MatSelect` respects `disabled` input with reactive form control while `MatInput` does not

### ISSUE THREAD

**Issue by Ninad99** [angular/components#19437]
#### Reproduction

Here's the issue on Stackblitz: https://stackblitz.com/edit/angular-ivy-mdin4v?file=src%2Fapp%2Fapp.component.html

Steps to reproduce:
1. I'm using the `formInputs` array to dynamically generate form fields using an `*ngFor` directive in the html
2. The `[disabled]` property on the `matInput` doesn't get applied for normal inputs. It does however get applied for other components like `<mat-select>`.
 
 
#### Expected Behavior

The `matInput` should be disabled

#### Actual Behavior

The `disabled` property wasn't applied on the input field (`matInput`).

#### Environment

- Angular: 9.1.4
- CDK/Material: 9.2.4
- Browser(s): Brave
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

**Comment by devversion** [comment]
Thanks for the issue. I think this is working as expected as with reactive form controls, the `disabled` input is supposed to be a noop. This is the same for native inputs. See [the form control logic](https://github.com/angular/angular/blob/master/packages/forms/src/directives/reactive_directives/form_control_name.ts#L99). The warning is also printed in the StackBlitz.

Interestingly enough though, `mat-select` behaves differently as you noted. This is because select implements a control value accessor and does not prioritize the value from potential controls (as done in `MatInput` or native inputs) It might be worth making this consistent.

**Comment by crisbeto** [comment]
The fix for this ended up breaking a lot of apps internally and it appears to be against the convention in the `ReactiveFormsModule` based on this warning https://github.com/angular/angular/blob/master/packages/forms/src/directives/reactive_directives/form_control_directive.ts#L75. Closing since reactive form controls should be disabled using the form control itself, not the `disabled` binding.

**Comment by Achilles1515** [comment]
@crisbeto Can you reopen this issue?
In https://github.com/angular/components/pull/19705 you stated
> It ended up being quite breaky and it looks like the forms module logs a warning against usages like this

This warning message is occurring with how the `MatSelect` component is **currently** structured; that PR solves the warning message and keeps it from appearing.

Please correct me if I am wrong, but there is currently no way to have the `FormControl` disable the `MatSelect`.

A separate binding to `MatSelect`'s `[disabled]` input allows us to disable the `MatSelect`.
```html
<mat-select formControlName="selectControl" [disabled]="false">
    <mat-option value="option1">Option 1</mat-option>
    <mat-option value="option2">Option 2</mat-option>
</mat-select>
```

...but as we've seen, this throws the "disabled attribute with a reactive form directive" warning message.
What the reactive forms module wants you to do is take that `[disabled]` binding out, like this:

```html
<mat-select formControlName="selectControl">
    <mat-option value="option1">Option 1</mat-option>
    <mat-option value="option2">Option 2</mat-option>
</mat-select>
```

...but now we can't disable the `MatSelect` because `MatSelect` doesn't care/honor if its backing `NgControl` is disabled.

You can obviously work around this by manually enabling/disabling the `matSelect.disabled`  property in code, but that is a pain.

The changes in https://github.com/angular/components/pull/19705 look like exactly what needs to be done, especially considering this is how `MatInput` works.

Can you provide an example(s) of the kind of code this change is breaking?

As a related sidenote, I might put in a PR to just completely remove this warning message. I feel like it was added with zero thought put toward `[disabled]` being an input property to a directive on the same HTML element as this `NgControl` and just assuming the user was always trying to bind to the `disabled` HTML attribute .

The disabled input on the `NgControl` directive should really be this:

```ts
@Input('disabled', 'But only if `disabled` is not an input for any other directives or if *all* these other directives respect the disabled state of this NgControl which I obviously can't check for')
set isDisabled(isDisabled: boolean) {
	if (typeof ngDevMode === 'undefined' || ngDevMode) {
	  console.warn(disabledAttrWarning);
	}
}
```

The whole vibe of the warning message is:
_"You don't know what you're doing!"_
When in fact, the answer is:
_"Yes, I do. Unfortunately, the MatSelect component doesn't check if you are disabled, which is why I am providing this input in the template. Please get off my back and leave me alone."_

**Comment by crisbeto** [comment]
> Please correct me if I am wrong, but there is currently no way to have the FormControl disable the MatSelect.

I'm not sure what you mean by this, because the select has respected the `disabled` state of a `FormControl` since we first released the component. Here's an example: https://stackblitz.com/edit/angular-n4azj3?file=src%2Fapp%2Fselect-overview-example.html

**Comment by Achilles1515** [comment]
@crisbeto It appears you are correct. Ignore my comments above about `MatSelect`.
I forked your example and made it closer to what we were doing, but it still works as you stated.

https://stackblitz.com/edit/angular-n4azj3-nfpryi?file=src%2Fapp%2Fselect-overview-example.ts

I'll just have to dig into our code further to figure out why the `MatSelect` isn't being disabled. Thanks for providing that example.
