### ISSUE TITLE
Themes in docs site do not match with prebuilt themes shipped to NPM

### ISSUE THREAD

**Issue by mizok** [angular/components#19442]
#### Reproduction

Use StackBlitz to reproduce your issue: https://stackblitz.com/fork/components-issue

Steps to reproduce:
1. just install the latest version ng mat and choose pink blue grey theme.
2. inspect element to check the difference.
 
 
#### Expected Behavior

What behavior were you expecting to see?

color set which is downloaded via ng add stuff should be the same as which is mentioned on official site 

#### Actual Behavior

What behavior did you actually see?
Downloaded version primary color: #c2185b
Official site version primary color: #e91e63
Downloaded version accent color: #b0bec5
Official site version accent color: #607d8b

#### Environment

- Angular:
- CDK/Material:
- Browser(s):
- Operating System (e.g. Windows, macOS, Ubuntu):

**Comment by Splaktar** [comment]
The docs [just use the defaults](https://github.com/angular/material.angular.io/blob/3d6e0a59816c59dd835571e48ecbf1f7ac495a39/src/styles/custom-themes/pink-bluegrey.scss#L5-L6).

> Official site version primary color: #e91e63

That's the official pink default:
https://github.com/angular/components/blob/924494d8f87993bd7904ceb0ea04709d461ac6a6/src/material/core/theming/_palette.scss#L78

> Downloaded version primary color: #c2185b

This comes from the customized pre-built themes, which override quite a few hues:
https://github.com/angular/components/blob/6095e29f4692c4b8fa0bb3b11509435c52d5d0c7/src/material/core/theming/prebuilt/pink-bluegrey.scss#L8-L9

These overrides for the pre-built themes go all the way back to 2016 via @jelbourn in https://github.com/angular/components/commit/10eea20feb97bf0d86118c202ac9923d4aff547e.

> Can confirm that themes are different in the docs, and do not match the prebuilt themes. For example: https://github.com/angular/material.angular.io/blob/master/src/styles/custom-themes/deeppurple-amber.scss. Notice how we update default hues here.

Those actually match what's used in the pre-built themes:
https://github.com/angular/components/blob/6095e29f4692c4b8fa0bb3b11509435c52d5d0c7/src/material/core/theming/prebuilt/deeppurple-amber.scss#L8-L9

**Comment by Splaktar** [comment]
The question is, should we update the pre-built themes to remove overrides or update the doc themes to use the same overrides (and then re-evaluate a11y across the app to ensure compliance with contrast requirements)?

Given that this issue was transferred to this repo, is the thought that we should remove the overrides from the pre-built themes?

**Comment by devversion** [comment]
I guess there is different understanding on what the defaults are. My thinking is that the docs _should_ use the themes as provided in the NPM package currently.

**Comment by devversion** [comment]
@Splaktar I just moved it to the docs repo and back because we should keep it here for triage tracking.

My thinking is that we should simply update the docs to use the actual prebuilt themes from the NPM package. In the past we chatted about overhauling the prebuilt themes, so that might be related.

**Comment by Splaktar** [comment]
The docs can't just use the pre-built theme CSS from the library due to [the need to pass the $theme into the material-docs-app-theme() mixin](https://github.com/angular/material.angular.io/blob/53965ba3b8d271e4b7b29a8923f2c2ddba5dc488/src/styles/custom-themes/pink-bluegrey.scss#L10).

The library doesn't ship the SCSS in `prebuilt-themes/` or in `core/theming/prebuilt/`. So it doesn't look like we have access to the SCSS that we need. That seems to be the driver for copying the SCSS files into [`src/styles/custom-themes/`](https://github.com/angular/material.angular.io/tree/53965ba3b8d271e4b7b29a8923f2c2ddba5dc488/src/styles/custom-themes).

Should we be bundling the pre-built theme SCSS into the library for this kind of use case? or is it bundled somewhere that I'm missing?

**Comment by devversion** [comment]
Good point @Splaktar. I didn't realize that we'd need to pass the `$theme` object to the docs theme.

That's a good question. I would say no, as these files cannot be consumed conveniently and we most likely do not want to provide them as a public API. It might be best to just sync the docs themes with the prebuilt ones then (and adding comments in both places to ensure future sync).

**Comment by alexandrecanuto** [comment]
Just my two cents, if we're syncing the colors somehow, the docs look better than the shipped themes.

**Comment by jelbourn** [comment]
Closing this since, while these two are different, it's not a big priority to align them. The expectation is that most people will define a custom theme anyway.
