### ISSUE TITLE
Proposal to make MatOption (its value) typed

### ISSUE THREAD

**Issue by Wilt** [angular/components#19456]
#### Feature Description

Make `MatOption` class typed

#### Use Case

When using `MatOption` the value is typed `any`, would be great if it would be possible to make `MatOption` type specific, could by default be falling back to `any`:

#### Proposed solution:

````
export class MatOption<T = any> implements FocusableOption, AfterViewChecked, OnDestroy {

  //...

  @Input() value: T;

  //...

}
````

Could provide a PR if that is preferred.

**Comment by jelbourn** [comment]
I actually have this on our backlog for _all_ valued components (radio, select, etc).

**Comment by Wilt** [comment]
@jelbourn Sounds good! 
Any idea on when will it move from the backlog to a sprint? Typed components would be very useful for checking application/code consistency.

**Comment by jelbourn** [comment]
It's hard to say. It's currently number 23 on the backlog behind the remaining work for MDC-based components and test harnesses, but the MDC work is pretty large in scope since it involves updating a lot of Google code internally. We might be able to accept PRs if the changes are strictly non-breaking.
