### ISSUE TITLE
bug(Mat-expansion-panel): The panel which is already in expanded state gets collapsed when openAll( ) method is triggered

### ISSUE THREAD

**Issue by ThilakrajSelvam** [angular/components#19481]
#### Reproduction

https://stackblitz.com/edit/components-issue-mat-expansion-panel

Steps to reproduce:
1.  Open the above url
2. Expand any one of the expansion panel
3. Now click "Expand All" button
 
 
#### Expected Behavior

All Expansion panels should be expanded

#### Actual Behavior

The panel which is already in expanded state gets collapsed

#### Environment

- Angular:
- CDK/Material:
- Browser(s):
- Operating System (e.g. Windows, macOS, Ubuntu): 

#### Proof

![Bug-proof-gif](https://user-images.githubusercontent.com/26435204/83226611-fb86aa00-a19f-11ea-9b78-2610240b3d75.gif)

**Comment by crisbeto** [comment]
It looks like the issue comes from the fact that you also have an `expanded` binding on each panel. The binding will get re-evaluated on each change detection and will override the value set by `openAll`. Here's a working example: https://stackblitz.com/edit/components-issue-mat-expansion-panel-5p7ryd?file=src/app/example-component.ts

Since `openAll` is basically just a shortcut to setting `expanded = true` on all the panels, you can change your binding to something like `[expanded]="step === 1 || step === null"` and then set the `expanded` to `null` when you want a particular panel to be open.
