### ISSUE TITLE
Support hiding/showing tabs instead of destroying/creating

### ISSUE THREAD

**Issue by jelbourn** [angular/components#19480]
This request for tabs comes up some some frequency. `MatTabGroup` uses `ngIf` to show the current tab, meaning that tab content is torn down when switching between tabs. Sometimes people want to preserve uncommitted state across tab changes (e.g. #17034 and #17391), which this prevents.

**Comment by crisbeto** [comment]
I think this should be covered by https://github.com/angular/components/issues/17391.

**Comment by jelbourn** [comment]
@crisbeto let's track it here since this is the root of the issue.

**Comment by afillion** [comment]
Hi @crisbeto
I just ran into this issue cause i need your input 'preserveContent'. ( I need to mat-tab content not disappear from DOM when offscreen.)
I saw your commit is in a merge request since november 2020.
I would like to know if it's still relevant ? And if it is, when do you think the merge will be done ?
Cordially ! :)

**Comment by btvanhooser** [comment]
Any updates on when this might be merged in? Looks like it's ready to go and I'd personally like access to this.

**Comment by calvinjc** [comment]
Can you please provide an update on the status of issue?  This is a significant problem for using an iframe in a tab, but there has been no movement in a long time.  We would really like to see this fixed.

**Comment by bharathmuppa** [comment]
Could you please update on this

**Comment by PandaCodeAng** [comment]
i also need this feature
