### ISSUE TITLE
Neither checkbox or slide toggle change form touched state

### ISSUE THREAD

**Issue by alvipeo** [angular/components#19496]
See this - [https://stackblitz.com/edit/ng9-material-checkbox](https://stackblitz.com/edit/ng9-material-checkbox) .

If you click on slide toggle the `touched` does not change. But if you then click anywhere else outside it DOES change!

**Comment by alvipeo** [comment]
On my real project where the form is far more complex even clicking outside of the toggle does not help.

**Comment by crisbeto** [comment]
`touched` means that the user is done interacting with it, which is basically the same as listening for a `blur` event on the element. Material works this way, because it's consistent with how the native checkboxes work (see https://stackblitz.com/edit/ng9-material-checkbox-vesz7j?file=src/app/app.component.html). If you want something that changes as soon as the user has changed the value, you can use `dirty` instead.

**Comment by alvipeo** [comment]
Thank you!
