### ISSUE TITLE
bug(MatInputHarness): error setting decimal value on input with type="number"

### ISSUE THREAD

**Issue by mischkl** [angular/components#19561]
#### Reproduction

Steps to reproduce:
1. Create a matInput with type="number" and step="0.01"
2. Get MatInputHarness for the input and attempt to set a decimal value on it, e.g.

```ts
await input.setValue('22.45');
```
 
#### Expected Behavior

The value is set to 22.45

#### Actual Behavior

What behavior did you actually see?

Chrome gives the error `The specified value "22." is not a valid number. The value must match to the following regular expression: -?(\d+|\d+\.\d+|\.\d+)([eE][-+]?\d+)?`

The actual set value is only the decimal part of the number, i.e. `45`.

#### Environment

- Angular: 9.1.9
- CDK/Material: 9.2.4
- Browser(s): Chrome 80.0.3987.149
- Operating System (e.g. Windows, macOS, Ubuntu): macOS 10.15.5

**Comment by crisbeto** [comment]
I believe this should be resolved by https://github.com/angular/components/pull/18812.

**Comment by tobiasschweizer** [comment]
I also experienced problems with a decimal value, see https://github.com/angular/components/issues/18790#issuecomment-635206117.

I think it would be good to add a test for a decimal value to make sure it is fixed by https://github.com/angular/components/pull/18812(https://github.com/angular/components/issues/18790#issuecomment-635213365).

**Comment by crisbeto** [comment]
Closing since the related fix was merged in.
