### ISSUE TITLE
bug(Dialog): Cannot find lazy loaded entry component when using it as a dialog

### ISSUE THREAD

**Issue by PierreDuc** [angular/components#19616]
#### Reproduction

Use StackBlitz to reproduce your issue: [stackblitz](https://stackblitz.com/edit/angular-material-dialog-lazy-bug?file=src%2Fapp%2Flazy.component.ts)

Steps to reproduce:
1. Create a lazy loaded module
2. Navigate to it and open a dialog which is declared as entry component in that lazy module
 
#### Expected Behavior

To have no error

#### Actual Behavior

An error:

```
No component factory found for LazyDialog. Did you add it to @NgModule.entryComponents?
```

I actually started creating the stackblitz, because I was having an issue with unresolved providers inside a component which is using another component in its template, which is imported from a `NgModule`, and where the service is provided in the providers array of this `NgModule`. Hard to explain, but I could not reproduce that issue, because of the current error. I think it's related to #19335 and perhaps this issue is as well.

#### Environment

- Angular: ^9.0.0
- CDK/Material: ^9.0.0.
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

**Comment by jelbourn** [comment]
Potentially related to or the same thing as #19335

**Comment by PierreDuc** [comment]
Found a fix, even though this got introduced with ivy. From where the dialog is opened, you need to pass in a `componentFactoryResolver` and a `viewContainerRef`. Apparently both are necessary:

```
@Component({
  template: `<button (click)="openDialog()">Open dialog</button>`
})
export class LazyComponent {
  constructor(private dialog: MatDialog, private vc: ViewContainerRef,
              private ngRef: NgModuleRef<LazyModule>) {}
  
  openDialog(): void {
    this.dialog.open(LazyDialog, { 
      viewContainerRef: this.vc,
      componentFactoryResolver: this.ngRef.componentFactoryResolver 
    });
  }
}
```

Question remains why this is necessary all of the sudden

**Comment by crisbeto** [comment]
If you're using Ivy, the `entryComponents` shouldn't be necessary in first place.

**Comment by devversion** [comment]
It looks like the issue is that the `MatDialogModule` is imported in the app root injector while the dialog module is not added to the lazy module. This means that the lazy component, when it accesses `MatDialog` will get the instance from the root module, so that the `ComponentFactoryResolver` is not the one from the lazy module when the content component is resolved.

Adding the `MatDialogModule` to your lazy module fixes the issue. See: https://stackblitz.com/edit/angular-material-dialog-lazy-bug-yzmexm?file=src%2Fapp%2Flazy.module.ts

It might make sense to not provide `MatDialog` directly in the module, but through `providedIn: 'any'` so that each lazy-module and root get their own instance of the service (based on usage).

**Comment by devversion** [comment]
I think we should revisit the use of `providedIn: 'any'` for the dialog when we consider making it tree-shakable/lazy. This is tracked with #18944. For now, this is working as expected though. The lazy module should declare imports for services/components it uses.
