### ISSUE TITLE
bug(Mat-vertical-Stepper + Mat-Tabs): Combination of Mat-tabs and Vertical stepper BUG

### ISSUE THREAD

**Issue by SK-Commit** [angular/components#19697]
# Reproduction

Steps to reproduce:
1. https://github.com/SK-Commit/angular-stepper-tabs-bug
2. Clone
3. NPM Install + NPM start
4. Go to localhost:4200
5. Go to next tab on page
6. Go back to first tab
 
 
#### Expected Behavior

What behavior were you expecting to see?

First tab, only ONE step in Mat-vertical-stepper is open. When navigating to new tab and back i expect, only that the ONE step i still open.

#### Actual Behavior

What behavior did you actually see?
https://github.com/angular/components/issues/10965
When navigating back to first tab with Mat-Vertical-Stepper, all steps are open, and behaviour is broken.

Note: The project is generated through the generator: "NGX-Rocket".

I still get the bug, after deleting node_modules, package-lock.json, and updating package.json to newest angular versions of all packages in a fresh project, then NPM install.

"@angular/animations": "9.1.11",
"@angular/common": "9.1.11",
"@angular/compiler": "9.1.11",
"@angular/core": "9.1.11",
"@angular/forms": "9.1.11",
"@angular/platform-browser": "9.1.11",
"@angular/platform-browser-dynamic": "9.1.11",
"@angular/router": "9.1.11",
"@angular/service-worker": "9.1.11",
"@angular/cdk": "9.2.4",
"@angular/material": "9.2.4",
"@angular/flex-layout": "^9.0.0-beta.31",

#### Environment

- Angular: 9.1.11
- CDK/Material: 9.2.4
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): WIndows

**Comment by andrewseguin** [comment]
You can do two things to workaround this issue, which is unfortunately due to how Angular renders dynamic views.

1. Use lazy-loading tab content

```
<mat-tab-group>
  <mat-tab label="Planning">
    <ng-template matTabContent>
      <mat-vertical-stepper>
      ...
      </mat-vertical-stepper>
    </ng-template>
  </mat-tab>
```

That will keep the stepper from bugging out when it you transition back to it.

2. Store where the user is in their steps. The stepper will be re-initialized when you come back to it, so whatever data it should initialize with should be stored by the app. This includes any data the user has entered and the current step you are on
