### ISSUE TITLE
Provide way to use select in MDC-based form-field

### ISSUE THREAD

**Issue by seeiuu** [angular/components#19847]
Hello folks, I hope that all going good! I need your help. 
Thanks to @devversion 's suggest I have succeeded with my first test with MDC angular component. 
So far, so good... 

Nevertheless now I am crossing some problems, I would like use "mdc-form-field" with "mdc-input" and "mdc-select"... but "mdc-select" is not implement yet... so I used the normal material "select"... but angular say me that: 

`More than one component matched on this element.Make sure that only one component's selector can match a given element.Conflicting components: MatFormField,MatFormField`

This because "select" import her "MatFormField"... is there a workaround for this? 

Thanks in advance for your help!

**Comment by devversion** [comment]
The problem here is that the `MatSelectModule` always provides the `MatFormFieldModule`. This then conflicts with the form-field module from MDC as they use the same selectors. Ideally select would not provide the form-field module (though that will be breaking; and we do this for common convenience), or we'd temporarily expose an experimental select entry-point with a form-field independent select module (that would seem easiest for now).

**Comment by mmalerba** [comment]
MDC-based select exists now, closing this
