### ISSUE TITLE
bug(YouTube Player): Can't play youtube videos on iOS with playsinline

### ISSUE THREAD

**Issue by JoseDRojasA** [angular/components#19868]
#### Reproduction

Use StackBlitz to reproduce your issue: https://stackblitz.com/edit/angular-youtube-player

Steps to reproduce:
1. In iOS, try to play the video inline (Not fullscreen)
 
#### Expected Behavior

What behavior were you expecting to see?
Play youtube video inline.

#### Actual Behavior

What behavior did you actually see?
If I play the video, the video only plays in fullscreen mode. I have read on the Internet that adding playsinline should solve this issue but I don't see how to set this property in the youtube-player component.

#### Environment

- Angular: 8.0.0
- CDK/Material:8.2.0
- Browser(s): Safari
- Operating System (e.g. Windows, macOS, Ubuntu): iOS

**Comment by crisbeto** [comment]
It looks like you can pass in the `playsinline` value yourself through the `playerVars` input ([see the docs](https://developers.google.com/youtube/player_parameters.html?playerVersion=HTML5#playsinline)). I'll close the issue since we try to avoid deviating from the default values when the user has the ability to change it themselves.

**Comment by JoseDRojasA** [comment]
Hi @crisbeto, Could you give me an example of how can I pass the playsinline property in the youtube-player component? Please
