### ISSUE TITLE
bug(*): Update documentation woth infromation from Angular 10

### ISSUE THREAD

**Issue by Akxe** [angular/components#19948]
I am not sure how out of date it is, but I found it is true for `entryComponents`.

From https://update.angular.io/#9.0:10.0l3:
> If you have specified any `entryComponents` in your NgModules or had any uses of `ANALYZE_FOR_ENTRY_COMPONENTS`, you can remove them. They are no longer required with the Ivy compiler and runtime.

#### Expected Behavior

https://material.angular.io/cdk/portal/overview (and dialog and possibly others)

Used to create a portal from a component type. When a component is dynamically created using portals, it must be included in the `entryComponents` of its `NgModule`.

#### Actual Behavior

I would expect it not to be there as it clearly is not true anymore. (just tested for dialog)

#### Environment

- Angular: 10
- CDK/Material: 10
- Browser(s): *
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

**Comment by crisbeto** [comment]
`entryComponents` aren't required if you're running Ivy which is the default now, but they're still necessary for ViewEngine. Since we support switching between the two, we can't remove the entry from the docs yet. Once `core` removes ViewEngine completely, we'll remove the mentions of `entryComponents` from our docs as well.
