### ISSUE TITLE
tree: importing MatIconModule and MatButtonModule is necessary

### ISSUE THREAD

**Issue by tom-richter** [angular/components#20239]
It would be helpful to mention in the API reference for Angular Material tree that besides the **MatTreeModule** also **MatIconModule** and **MatButtonModule** must be imported into the **app.module.ts.**
(eg. when you use a "Tree with flat nodes")

```
import {MatButtonModule} from '@angular/material/button';
import {MatIconModule} from '@angular/material/icon';
import {MatTreeModule} from '@angular/material/tree';
```

**Comment by crisbeto** [comment]
For what it's worth, the icon and button modules aren't mandatory for the tree to work, but they are needed if you wanted to replicate the demo from the docs.

**Comment by romualdnave** [comment]
@crisbeto I was just passing by and read this issue then your comment. Considering most of the components usage examples are using `mat-icon-button` directive or `<mat-icon>` selector would this still be relevant ? Should some kind of global mention to these necessary imports be considered in the documentation then ?

**Comment by tom-richter** [comment]
Yes, for me as an Angular Material beginner I copied the code from the documentation and spent half an hour debugging until I found out why the material tree style is not applied. There is no descriptive error message. The tree just looks strange like in this issue:
https://stackoverflow.com/questions/57527296/material-tree-style-not-being-applied/63174068#63174068

**Comment by zarend** [comment]
Closing this because importing the mat button and icon modules are not required for the tree to work. In the case of the flat tree example, we are directing using `MatButton`, and we directly use `MatIcon` inside the button. It's the direct usages that require the `MatIconModule` and the `MatButtonModule`. In other cases where a component is used inside another (like MatTreeNode), the dependencies are already imported in the appropriate NgModule.
