### ISSUE TITLE
feat(testing): puppeteer TestElement and HarnessEnvironment

### ISSUE THREAD

**Issue by davidjgoss** [angular/components#20320]
#### Feature Description

I've built implementations of `TestElement` and `HarnessEnvironment` for use with puppeteer. I'm trialling it at work (there are a few bits left to do) but wanted to ask if this is something you'd be interested in having in this repo.

Also, is there anything like a test suite to measure a harness environment's completeness?

#### Use Case

e2e testing using [puppeteer](https://pptr.dev/) as the browser driver (outside of the CLI tooling, at the moment).

**Comment by mmalerba** [comment]
I don't think its something we would want to include in this repo because the team doesn't have the capacity to maintain it. However, it does sound like it would be a good thing to publish as a separate repo so others can use it in their projects.

We have some tests for the environments in our repo which would probably be a good starting point for testing your new environment. https://github.com/angular/components/tree/master/src/cdk/testing/tests

**Comment by crisbeto** [comment]
Closing since it looks like something that we won't be doing ourselves.
