### ISSUE TITLE
About MatProgressSpinnerDefaultOptions#_forceAnimations definition

### ISSUE THREAD

**Issue by dev054** [angular/components#20327]
#### Expected Behavior
I'd expect a clarification whether it's really public or a private.

1. If it's public, I'd recommend to get rid of the "_".
2. If it's private, I'd recommend to mark it with `@docs-private` because right now it appears on [docs](https://material.angular.io/components/progress-spinner/api#MatProgressSpinnerDefaultOptions).

#### Actual Behavior
`MatProgressSpinnerDefaultOptions` have a private (?) property: https://github.com/angular/components/blob/a6f1a33998af82db7fa960a66fc851058bf60c98/src/material/progress-spinner/progress-spinner.ts#L60

I was about to use it to disable animation globally, but the `_` confused me, as this symbol tends to mark as a private API and, therefore, can change at any time, without respecting the depreciation period.

**Comment by crisbeto** [comment]
This is something that was added for a very specific use case in an internal app. By default the spinner will stop animating if it's inside a module that imports the `NoopAnimationsModule`, but this option will allow you to still have spinner animations while everything else is disabled. I'm not sure whether we should be documenting it since we didn't really think it through very well when it was added.

That being said, I think it's a bug in the docs generation script that it shows up in the docs, because we have a convention where underscored symbols are excluded from the docs automatically.
