### ISSUE TITLE
datepicker different behavor for Chrome and IE browsers

### ISSUE THREAD

**Issue by aaltotsky** [angular/components#20332]
#### Reproduction

Steps to reproduce:

1. Use the https://material.angular.io/components/datepicker/overview page.
2. Open page in both IE11 and Chrome browser
3. Scroll to the "Basic datepicker"
4. Enter the following: 10/10/20
5. Observe that IE change date to 10/10/1920
6. Observe that Chrome change date to 10/10/2020 
 
#### Expected Behavior

Both browsers should behave the same and convert the 10/10/20 to 10/10/2020

#### Actual Behavior

IE11 browser switch to the last century. 

#### Environment

- Angular: 10.0.6
- CDK/Material: 10.1.3
- Browser(s): Internet Explorer v11
- Operating System (e.g. Windows, macOS, Ubuntu): Windows 7

**Comment by travisbashor** [comment]
The problem is that different browsers parse ambiguous formats differently. Since the '/20' is an ambiguous year, the difference will show in that case.

When the `DateAdapter`'s `.parse()` method is called ([here](https://github.com/angular/components/blob/23d3c216c65b327e0acfb48b53302b8fda326e7f/src/material/core/datetime/native-date-adapter.ts#L186)) it invokes the `new Date()` constructor straight from JavaScript. While that will produce consistent values _within_ browsers, across browsers the value varies.

You can test by opening up a console in Chrome and IE and typing
```bash
$ new Date('10/10/20')
```
You'll see that IE gives last century, and Chrome gives this century. There are other differences, too. Some are documented [here](http://dygraphs.com/date-formats.html). That link is a little out-dated, but it paints the picture.

One option would be to use a configurable text mask that defaults to something reasonable, but allows any ISO-compliant date format. However, that would require an implementation of ControlValueAccessor and there's already one on the input by way of the `matDatePicker` directive. So, unless I'm overlooking something, that would not be doable.

Another option would be to put an additional layer of parsing in before the date is instantiated. You could normalize dates across browsers as a first step, and then invoke `new Date()`. That may be the way to go, but it would have to be done across all inputs, so that there wouldn't be inconsistent parsing of dates between different inputs (i.e., something with `matInput` reads 2020 in IE, but a plain `<input>` element right next to it still reads `1920`). So then you're down to needing to be browser-aware every time `new Date()` or `Date.parse()` (and probably some others) are used. You could inject a transient, browser-aware date service, but that feels heavy.

A third option would be to let the browsers be different and wait until they are out of their rebellious, non-conforming phase.

**Comment by aaltotsky** [comment]
Thank you @travisbashor for your answer. So, is there an event, I can catch, prior to the Date conversion, to add my own validation?
For example, a user typed the value "10/10/20" into the calendar control. The calendar control raises an event. I change the user-entered value to "10/10/2020". Control parses the value using the Date object.

**Comment by travisbashor** [comment]
I may be wrong, but I don't think there is anything you can do to know what the original input was. Because the directive uses ControlValueAccessor, the only value you'll have access to is the mapped value after the directive has handled it. At that point, it will be impossible to know whether it was typed in deliberately or mapped from an ambiguous date.

What could be cool is if the `DatePickerInputBase` class exposed a pre-processing hook in its [write value](https://github.com/angular/components/blob/23d3c216c65b327e0acfb48b53302b8fda326e7f/src/material/datepicker/datepicker-input-base.ts#L292) implementation for its derived classes to use, which they could expose to the user for pre-processing.
So instead of:
```typescript
  writeValue(value: D): void {
    this.value = value;
  }
```

the base class would have
```typescript
// In the base class
  protected abstract _getInputPreProcessor();

  // ...

  writeValue(value: D): void {
    const process = this._getInputPreProcessor();  
    this.value = process(value);
  }
```
And the child class could use it to hook in:
```typescript
// In the child class

/** Gets the input's pre-processor function. */
_getInputPreProcessor() {
  return this._inputPreProcessor;
}
}
```

At that point, the user would just have to supply that function to the directive with some kind of context object and you'd be off to the races.

I'm not sure if the Angular team wants to expose that much control, but it does seem like a common-enough scenario that people want to do some kind of formatting or processing on input over and above the binding with the calendar.

**Comment by aaltotsky** [comment]
I found a solution with the implementation for MatDateFormats:
https://stackoverflow.com/questions/48762645/material-datepicker-parses-incorrectly-if-user-write-date-in-input.
This is not an easy approach to fix IE/Chrome differences. However, this could be a temporary fix.

**Comment by jelbourn** [comment]
Yeah, this behavior is expected if you use native date parsing. We recommend using an alternate `DateAdapter` implementation, such as the MomentJS one
