### ISSUE TITLE
bug(mat-form-field): Incorrect placing for outlined form input without a label

### ISSUE THREAD

**Issue by hunhejj** [angular/components#20417]
#### Reproduction

https://stackblitz.com/edit/angular-v1zbur-eob8nl?file=src/app/form-field-example.html

<img width="478" alt="Screenshot 2020-08-26 at 11 28 40" src="https://user-images.githubusercontent.com/15079374/91287023-7ce5dc80-e78f-11ea-9251-3cb64678f0d9.png">

#### Given
- a form field
- with appearance set to `outline`
- without a label, i.e. no `mat-label`

#### Expected Behavior

The text in the input field is centered vertically correctly.

#### Actual Behavior

The text in the input field is not centered vertically.

**Comment by crisbeto** [comment]
This is working as expected. If we were to move the text up, it wouldn't be centered anymore next to other form fields with labels that are next to it. In general, it's a good idea to have a `mat-label`, because it allows for it to be read out by screen readers. In this case, you may be better off putting the text from the `placeholder` attribute into a `mat-label` since it'll behave the same as a placeholder when it's empty, but float up once there's a value.
