### ISSUE TITLE
bug(MatExpansionPanelHeader): Component visibly resizes after initialization

### ISSUE THREAD

**Issue by rileypb** [angular/components#20450]
#### Reproduction

Use StackBlitz to reproduce your issue: https://components-issue-asfxnf.stackblitz.io

Steps to reproduce:
1. Create component containing a mat-expansion-panel with a mat-expansion-panel-header
2. Set collapsedHeight to 20px.
3. Load the component in your angular app.
 
#### Expected Behavior

What behavior were you expecting to see?
The panel should appear collapsed, with a header height of 20px.

#### Actual Behavior

What behavior did you actually see?
The panel was initially rendered at a larger height, and then shrunk to 20px.

#### Environment

- Angular: 7.2.16
- CDK/Material: 7.3.7
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): macOS

**Comment by rileypb** [comment]
Note this doesn't happen in the StackBlitz, using the same code it is occurring with in my app.

**Comment by crisbeto** [comment]
We can't do much without a reproduction. Since it isn't breaking on Stackblitz, there are a couple of things to check out:
1. There might be some global styles in your app that are interfering with the expansion panel.
2. You're using an old version of Material. Have you tried updating it? It's possible that the issue was fixed in a later version.

**Comment by rileypb** [comment]
Yes, in the latest version of Material it's fixed. Thanks!
