### ISSUE TITLE
bug(icon): custom directive cannot set svgIcon for mat-icon

### ISSUE THREAD

**Issue by klemenoslaj** [angular/components#20470]
#### Reproduction

_`svgIcon` does not seem to work with Stackblitz, providing repo instead._

Steps to reproduce:
1. Clone https://github.com/klemenoslaj/mat-icon-svg-not-applied
2. Install dependencies using `yarn`
3. Execute `ng serve`
 
 
#### Expected Behavior

I tried to create a custom directive that would programmatically assign some icon name to the `svgIcon` input of `mat-icon`, depending on some global icon mapping configuration.
This normally works for any component and I'd expect it should for `mat-icon` too.

Example:
```html
<mat-icon [iconFor]="object"></mat-icon>
```

```ts
@Directive({
  selector: 'mat-icon[iconFor]',
})
export class IconForDirective {
  @Input()
  set iconFor(obj: SomeInterface) {
    this._matIcon.svgIcon = _iconMap[obj.type];
  }

  constructor(
    @Inject(ICON_MAPPING_TOKEN)
    private readonly _iconMap: SomeIconMapping,
    private readonly _matIcon: MatIcon,
  ) {}
}
```

#### Actual Behavior

The behavior described above does not work with `mat-icon`, because the relevant logic is in `ngOnChanges` hook of `mat-icon`, which does not get triggered, unless at least one `Input` is present on the host component.

https://github.com/angular/components/blob/4f1238f84791f4193b5dfc8d9cbef76f04ee36d6/src/material/icon/icon.ts#L229-L264

##### Workaround (ugly):

Instead of
```html
<mat-icon [iconFor]="object"></mat-icon>
```

add dummy/empty `svgIcon`
```html
<mat-icon [iconFor]="object" svgIcon></mat-icon>
```

#### Environment

- Angular: 10.0.14
- CDK/Material: 10.1.3
- Browser(s): any
- Operating System (e.g. Windows, macOS, Ubuntu): any

---

NOTE: I can submit the PR for this, but would like some thoughts on that, maybe it's expected like this for some reason.

**Comment by jelbourn** [comment]
Looking at the code, it seems like we should extract the code in `ngOnChanges` that actually performs the DOM update into its own function, and then call that from both `ngOnChanges` and `ngOnInit` if the value has been changed. @crisbeto thoughts on this since you've touched the icon code most recently?

**Comment by crisbeto** [comment]
The only way would be to define a setter for `svgIcon`. I know that in the past we've decided not to handle cases like this, but in this one I think it's fine since we're already "paying" for the setters on `fontIcon` and `fontSet`. I've submitted a PR to support it and we can discuss any concerns there (#20509).
