### ISSUE TITLE
MatChipList chipRemoveChanges event doesn't fire

### ISSUE THREAD

**Issue by emrahyigit** [angular/components#20526]
Steps to produce:

```
@ViewChild(MatChipList) chipList: MatChipList;

ngAfterViewInit(): void {
   this.chipList.chipRemoveChanges.subscribe(event => {
        debugger;
   });
}
```
Environment:

`Angular and Angular Material version: 9+`

**Comment by devversion** [comment]
Thanks @emrahyigit for this issue. Please provide a StackBlitz for issues you're seeing, otherwise we won't be able to help.

I've tried reproducing this in a StackBlitz but it seems to fire as expected: https://stackblitz.com/edit/angular-zzbbvm?file=src/app/chips-input-example.ts.

Closing, please resubmit with a StackBlitz showing the issue if this still happens for you.

**Comment by emrahyigit** [comment]
Thank you for your answer. But did you add a new fruit and try to remove it again?
