### ISSUE TITLE
bug(map-circle): Not show

### ISSUE THREAD

**Issue by danieldflrss** [angular/components#20557]
I am trying to show maps circles but they are not showing on the map

Html code:

<google-map width="100%" [center]="center" [zoom]="zoom">
                <map-circle [center]="circleCenter" [radius]="radius"></map-circle>
 </google-map>

Component vars:
center: google.maps.LatLngLiteral = {lat: 24, lng: 12};
  zoom = 4;
  circleCenter: google.maps.LatLngLiteral = {lat: 24, lng: 12};
  radius: 1000;

Angular:

   "@angular/animations": "~10.0.14",
    "@angular/cdk": "^10.1.3",
    "@angular/common": "~10.0.14",
    "@angular/compiler": "~10.0.14",
    "@angular/core": "~10.0.14",
    "@angular/google-maps": "^10.2.0",

Result:
![Captura de pantalla 2020-09-13 204933](https://user-images.githubusercontent.com/6857967/93038599-a95c7e00-f602-11ea-9f07-d1c184314eab.png)

**Comment by jelbourn** [comment]
@danieldflrss can you provide a reproduction on stackblitz?

**Comment by crisbeto** [comment]
@danieldflrss your problem is that you didn't actually initialize the `radius` to `1000`, but you _typed_ it as `1000`. It should be `radius = 1000` instead of `radius: 1000`. Also it's worth noting that 1000 is fairly tiny for the zoom level that you've set on the map so it's a little hard to see, but it's definitely there once you zoom in.
