### ISSUE TITLE
Moment becomes legacy project

### ISSUE THREAD

**Issue by LoganDupont** [angular/components#20569]
Hellow,

I just want to inform that Moment became a legacy project in maintenance mode. See [project status](https://momentjs.com/docs/#/-project-status/). This could have an impact on different datepicker which are using moment for Internationalization and using imports from `@angular/material-moment-adapter`

**Comment by bbarry** [comment]
moment is a little annoying to use from more strict typescript projects and adds significant costs to user code that isn't mentioned in the documentation. Instead the documentation says:

> Please note: `MatNativeDateModule` is based off the functionality available in JavaScript's native `Date` object. Thus it is not suitable for many locales. One of the biggest shortcomings of the native `Date` object is the inability to set the parse format. We highly recommend using the `MomentDateAdapter` or a custom `DateAdapter` that works with the formatting/parsing library of your choice.

I feel like the documentation should be a little less opinionated and provide an example custom date adapter instead of recommending moment up front. Perhaps after a bare-bones custom adapter some sort of "by the way `MomentDateAdapter` exists if you want it" language and consider opening a PR issue for a `LuxonDateAdapter` (is a new package considered major api even when it is such a minor feature?) for a more modern api.

**Comment by jelbourn** [comment]
Tracking this in #20599
