### ISSUE TITLE
add BLUR to MatCheckbox

### ISSUE THREAD

**Issue by cosminv6u** [angular/components#20600]
MatCheckbox has only FOCUS method, not BLUR.

I want to control from keyboard the focus & blur of my checkboxes.
Please provide Blur method, not only Focus.

https://material.angular.io/components/checkbox/api#MatCheckbox

**Comment by crisbeto** [comment]
We kind of set the precedent for this by adding a `focus` method in the first place. For future reference, we'd have to do the same in all the other components where we have `focus` methods.

**Comment by cgatian** [comment]
@crisbeto we recently ran into this with one of our internal (non Angular Material) components. The consumer wanted us to add a blur method. However, blur is much harder to do than focus because when you blur default browser puts focus on the body. This is terrible for accessibility (screen reader situations and users using a keyboard). We opted **not** to provide a blur method because it generally made poor UX. We advised the consumer of the component to focus whatever they felt was the most appropriate UI element in order to blur the current component.

**Comment by cosminv6u** [comment]
Focus also puts 2 classes on the checkbox component: cdk-focused cdk-keyboard-focused
I need these to be removed as well when I press ESC.

**Comment by cgatian** [comment]
Why don't you listen for ESC and focus the body or other container element?

**Comment by cosminv6u** [comment]
I did that. But the 2 classes 'cdk-focused cdk-keyboard-focused' remained on the checkbox and it appeared as it's still focused.

I even tried to add a dummy mat-checkbox to focus that instead and it worked, but if I make the checkbox display: none;, it doesn't work anymore.

So I would need to get the focused checkbox and manually remove those 2 classes and it already feels too much ..

**Comment by cgatian** [comment]
@cosminv6u if you make a stackblitz I can try to assist

**Comment by crisbeto** [comment]
For what it's worth, you should be able to do `document.activeElement.blur()`. Note that doing so will kick the user's focus back to the `body` which can be confusing if they're navigating with a screen reader.

**Comment by cosminv6u** [comment]
@crisbeto thanks, it worked!

**Comment by andrewseguin** [comment]
Closing since we don't think adding a `blur` method would be an encouraged accessibility pattern here
