### ISSUE TITLE
Angular Material Mat-Dialog Content Need to Scroll down automatically Whenever its content grows.

### ISSUE THREAD

**Issue by GnanaJeyam** [angular/components#20606]
#### My Mat-dialog looks like this:

![Screenshot (41)](https://user-images.githubusercontent.com/59681280/93662061-acc88d00-fa7a-11ea-963f-7bac3e9cded5.png)

#### The issue I faced

![Screenshot (42)](https://user-images.githubusercontent.com/59681280/93662134-5b6ccd80-fa7b-11ea-8e46-0a6e0f850f68.png)

#### Code For Reference

```
<ng-template #filterTemplate>
  <mat-dialog-content [formGroup]="advancedSearchForm">
    <div *ngFor="let data of metaData" class="ui form">
      <dynamic-form [filterForm]="data" [form]="advancedSearchForm" ></dynamic-form>
    </div>
  </mat-dialog-content>
  <mat-dialog-actions>
    <div class="two centered text no min height rows">
      <div class="no min height row">
        <button class="ui button" (click)="save()">Search</button>
        <button class="ui button" (click)="clear()">Clear</button>
      </div>
    </div>
  </mat-dialog-actions>
</ng-template>

```
[StackOverflow Question Link](https://stackoverflow.com/questions/63966115/angular-material-mat-dialog-content-need-to-scroll-down-automatically-based-on-d)

**Comment by crisbeto** [comment]
Closing, because this would be impractical to do on our end due to the following reasons:
1. We'd have to listen to any change in the DOM in order to do it, which would be expensive and likely inaccurate.
2. Even if we did have an efficient and accurate way of knowing when to scroll down, the behavior seems very arbitrary and likely doesn't won't apply to most apps.

You'd be better off doing it yourself since you know exactly when a dropdown has been opened.
