### ISSUE TITLE
bug(Table): Observable `dataSource` with `trackBy` works unexpectedly on first change inside callback

### ISSUE THREAD

**Issue by JounQin** [angular/components#20634]
#### Reproduction

Use StackBlitz to reproduce your issue: https://stackblitz.com/edit/angular-ivy-3wsjyf

Steps to reproduce:
1. Open console panel
2. click `reverse` button, `xxx` logged without table content changes
3. click `reverse` button again, `xxx` logged and table content changes
4. If we remove `trackBy` or `setTimeout`, it will work as expected
 
 
#### Expected Behavior

What behavior were you expecting to see?

Table content should change along with `xxx` logged

#### Actual Behavior

What behavior did you actually see?

Table content does not change at the first time.

#### Environment

- Angular: 10.1.2
- CDK/Material: 10.2.2
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): macOS

**Comment by JounQin** [comment]
Workaround: use `async` pipe to transform `dataSource` into normal collection.

**Comment by wagnermaciel** [comment]
@JounQin This is working as expected. Because you are using the OnPush change detection strategy, you'll need to call `markForCheck`. See this stackblitz on how to set that up.

https://stackblitz.com/edit/angular-ivy-kafnao?file=src%2Fapp%2Fapp.component.ts

**Comment by JounQin** [comment]
@wagnermaciel Thanks for reply, but I'm not sure to understand, why it works as expected when I remove `trackBy` or add `async` pipe?

**Comment by wagnermaciel** [comment]
`trackBy` allows you to optimize your table by controlling the check for differences in data changes. In your implementation, you are returning `item.id` which never changes, thus the table does not trigger an update. If you want the change to happen when `item.name` changes, you should return `item.name` from `trackBy`.

What is more surprising here is that the table updates at all on subsequent clicks. I suspect it has something to do with the `setTimeout`, but it would require more digging to confirm what is the root cause of this behavior.

**Comment by JounQin** [comment]
@wagnermaciel Or can we call `rowView.markForCheck()` inside at https://github.com/angular/components/blob/master/src/cdk/table/table.ts#L629 on record changes? (It would work.)

**Comment by wagnermaciel** [comment]
While that would work, it would defeat the purpose of using `trackBy`. You'd be updating on every change regardless of what you are returning from `trackBy`.
