### ISSUE TITLE
bug(DRAG&DROP): The cdkDropList should be accessible when moving an element

### ISSUE THREAD

**Issue by GitHubish** [angular/components#20647]
I have a kanban board (like Trello) with columns that are collapsable. If a column is collapsed and I hover it when I move a card, I make it uncollaplle. However, at that point the `cdkDropListContainer` does not allow me to "drop" the card from within. 

Initially the `cdkDropList` element was "masked" with an `*ngIf` directive, I replaced it with the `hidden` attribute and then I tested with just a css style to set the size to 0 but none of these solutions worked. The result is always the same.

How is this done? How do I do it? 

I use : "@angular/cdk": "^10.0.1".

Thanks

**Comment by Achilles1515** [comment]
The hidden attribute/class would be the better way to go here versus an `ngIf` completely destroying/recreating a drop list mid-drag.

I believe there are no out-of-the-box ways to accomplish what you need. So you'll have to call some private APIs to refresh the client rects of the drop container(s) since you changed their dimensions/locations on page.

Perhaps running something like this immediately after the connected drop container has been unhidden:
```ts
// cdkDrag is reference to the `CdkDrag` directive currently being dragged
cdkDrag._dragRef._dropContainer._cacheParentPositions();
cdkDrag._dragRef._dropContainer._siblings.forEach(sibling => sibling._cacheParentPositions());
```

**Comment by crisbeto** [comment]
I believe this is covered by https://github.com/angular/components/issues/14703.
