### ISSUE TITLE
Angular Material's component harnesses support for Jest and Cypress

### ISSUE THREAD

**Issue by oscarlagatta** [angular/components#20648]
What support is available out of the box for Jest and Cypress as I can only see support for Karma unit tests and Protractor.
https://material.angular.io/guide/using-component-harnesses

**Comment by mmalerba** [comment]
Unfortunately the Angular Team does not have the capacity to maintain official support for these, but the component harness framework has been written in a way that allows users to plug in support for additional test environments. It is our hope that the community will share their implementations for test frameworks like the ones you mentioned so that others may benefit. We have some [documentation on how to author plugins for other environments](https://material.angular.io/cdk/test-harnesses/overview#api-for-harness-environment-authors), and the official environments should serve as good examples:
- [TestbedHarnessEnvironment](https://github.com/angular/components/tree/master/src/cdk/testing/testbed)
- [ProtractorHarnessEnvironment](https://github.com/angular/components/tree/master/src/cdk/testing/protractor)
