### ISSUE TITLE
Form field examples don't set an explicit `appearance` which is not super discoverable 

### ISSUE THREAD

**Issue by manu-058** [angular/components#20663]
#### Reproduction

StackBlitz to see the issue: https://stackblitz.com/edit/angular-2eacrh?file=src/app/form-field-appearance-example.html

Steps to reproduce:
1.  create a simple input control.
2.  for the mat-form-field, do not provide any value to the 'apperance' attribute. 

![Screenshot (498)](https://user-images.githubusercontent.com/38914354/94372947-8ca26900-011f-11eb-8cff-ed5b897e21d5.png)

#### Expected Behavior

What behavior were you expecting to see?
apperance : legacy , style must be applied ,
or 
updating the documentation , 

#### Actual Behavior

What behavior did you actually see?
apperance: fill , style is being applied

#### Environment

- Angular: 10
- CDK/Material: 10.2.2
- Browser(s): chrome
- Operating System : Windows

**Comment by crisbeto** [comment]
I believe that's the case, because we have this in the generated Stackblitz template:

```
providers: [
  { provide: MAT_FORM_FIELD_DEFAULT_OPTIONS, useValue: { appearance: 'fill' } },
]
```

I'm guessing the reason was that we want to discourage people from using the `legacy` appearance, because it's deprecated. @mmalerba is this something we should address? It feels like the examples should reflect the defaults accurately, instead of coming with their own defaults.

**Comment by manu-058** [comment]
my bad.
I did not observed that.
