### ISSUE TITLE
help(mat-calendar): Inline calendar with range selection

### ISSUE THREAD

**Issue by slaviki** [angular/components#20697]
#### What are you trying to do?

I want to have an inline mat-calendar (without mat-input) to be able to select a range of dates

#### What troubleshooting steps have you tried?

Binding to a date range works fine however, selectedChange gives back a single date. I've tried to provide MAT_RANGE_DATE_SELECTION_MODEL_PROVIDER, but it still doesn't work. 

#### Reproduction

[Stackblitz](https://stackblitz.com/edit/angular-lujqhwqw)

#### Environment

- Angular: 10,1,3
- CDK/Material: 10.2.3
- Browser(s): Google Chrome 85
- Operating System (e.g. Windows, macOS, Ubuntu): Win 10 2004

**Comment by crisbeto** [comment]
The calendar isn't responsible for assigning the value to the model. Usually it's the responsibility of `MatDatepickerContent`, but since you aren't using a datepicker, you'll have to assign the value yourself. See https://github.com/angular/components/blob/master/src/material/datepicker/datepicker-base.ts#L175.

**Comment by slaviki** [comment]
Thank you, I got it working
