### ISSUE TITLE
bug(slider): JAWS incorrectly announces MatSlider value changes 

### ISSUE THREAD

**Issue by eforbes** [angular/components#20701]
#### Reproduction

Default slider with no modifications: https://angular-cxwukz.stackblitz.io

Steps to reproduce:
1. Enable JAWS
2. Focus on the slider, and hold down left or right arrow to move slider.
 
Does not repro with NVDA or ChromeVox.
 
#### Expected Behavior

Slider will move while button is pressed and stop when it is  not. JAWS will announce the slider values as the slider is moved.

#### Actual Behavior

The slider keeps moving, and JAWS says nothing.  When the slider stops moving, JAWS repeats the value multiple times.  "79 79 79 79 79 79".

#### Environment

- Angular: Google
- CDK/Material: Google
- Browser(s): Chrome 85
- Operating System (e.g. Windows, macOS, Ubuntu): Windows 10 Pro

**Comment by crisbeto** [comment]
I believe that our slider is based on this example from the W3C https://www.w3.org/TR/wai-aria-practices-1.1/examples/slider/slider-1.html. There are a couple of other approaches we could take, but they have their own drawbacks:
1. We could have an internal `input[type="range"]` that we proxy all events and focus to. This is problematic, because we can't do a multi-handle slider in the future.
2. We could have the value inside an `aria-live` element, but that may generate more noise to the user.

I don't have JAWS available, but I wonder if debouncing the `aria-valuenow` assignments would help with it.

**Comment by jelbourn** [comment]
Unfortunately we don't have access to JAWS while Google is working remotely, so we might not be able to look at this for a while.

**Comment by jelbourn** [comment]
The upcoming MDC-based slider will use an internal `<input type="range">` that will likely fix this problem.

**Comment by amysorto** [comment]
For the new MDC based slider coming soon in v15, JAWS correctly says the updated value. I also tested the current slider component (v14), this is working correctly now too.
