### ISSUE TITLE
Ripple is being triggered when scrolling <mat-selection-list> on mobile

### ISSUE THREAD

**Issue by paco76** [angular/components#20711]
#### Reproduction

[link to stackblitz](https://stackblitz.com/edit/angular-material-lists-scrolling-triggers-ripple?file=src/app/app.component.html)

Steps to reproduce:
1.  open on mobile and scroll
2.  ripple is triggered while scrolling
 
 
#### Expected Behavior

when I scroll ripple should not be triggered !!

#### Environment

- Angular: 10.0.9
- CDK/Material: 10.1.3
- Browser(s): chrome
- Operating System (e.g. Windows, macOS, Ubuntu): ubuntu

**Comment by crisbeto** [comment]
I don't think that we can do much about it, because the ripple has to start as soon as you put your finger down. At that point we don't know whether you're going to tap the item or start scrolling. If we defer the ripple for too long it'll feel unresponsive and if we do it too little, it'll trigger for some slower scrolls, but not the quicker ones. 

Alternatively, you can turn off the ripples on that specific list like this: `<mat-selection list disableRipple></mat-selection-list>`.

**Comment by paco76** [comment]
can you please explain how does Whatsapp do it on their app?

**Comment by crisbeto** [comment]
I don't have an Android phone or access to their source code so I can't tell, but a way to work around it would be to only enable ripples after X amount of time after the last scroll event.
