### ISSUE TITLE
feat(table): MatCellDefWhen

### ISSUE THREAD

**Issue by jrel** [angular/components#20730]
#### Feature Description

Like matRowDefWhen, it was interesting to have this capability for MatCellDef as in the example below.

#### Use Case

```html
<table cdk-table [dataSource]="dataSource">
  <ng-container cdkColumnDef="name">
    <th cdk-header-cell *cdkHeaderCellDef> Name </th>
    <td cdk-cell *cdkCellDef="let element"> {{element.name}} </td>
    <td cdk-cell *cdkCellDef="let element;when:isFullname">{{element.firstname}} {{element.lastname}} </td>
  </ng-container>

  <tr cdk-header-row *cdkHeaderRowDef="displayedColumns"></tr>
  <tr cdk-row *cdkRowDef="let row; columns: displayedColumns;"></tr>
</table>
```

**Comment by mrmokwa** [comment]
For your scenario you could do something like

`<td cdk-cell *cdkCellDef="let element"> {{ isFullname ? element.firstname + ' ' + element.laastname : element.name }} </td>`

**Comment by jelbourn** [comment]
Yeah, like @mrmokwa points out, you'd be better off doing something within an expression for your example. 

I don't see us adding this feature since a table cell is a much more tightly scoped than a row; the row has configuration for all of the cells, so there's no other way to swap row templates than with the `when` predicate, but for a cell you can just use a standard `ngIf`, etc.
