### ISSUE TITLE
bug(mat-table): Filtering a mat-table with inputs using ngModel render the same row

### ISSUE THREAD

**Issue by gabra666** [angular/components#20731]
#### Reproduction

Use StackBlitz to reproduce your issue: https://stackblitz.com/fork/components-issue
https://stackblitz.com/edit/angular-ngmodel-material-table?file=app/table-basic-example.html

Steps to reproduce:
1. Type in the filter "Hello" > 2 entries should display with correct data
2. Add in the filter a number 2, the text "Hello2" should be in the filter > 1 entry should display in the table
3. Add in the filter letter 'x', the text "Hello2x" should be in the filter > no entries should display in the table
4. Delete 'x' and '2', the text "Hello" should be in the filter > 2 entries are shown displaying the same duplicated information, Filtered data json at the bottom shows the correct data, that is not displayed in the table. 
 
 
#### Expected Behavior
What behavior were you expecting to see?
The rendered data should be the same as the filtered data, displaying the 2 rows with the correct data

#### Actual Behavior
What behavior did you actually see?
The 2 entries displayed are a duplicated/wrong render version, while the filtered data shows the correct version.

#### Environment

- Angular:
- CDK/Material:
- Browser(s):
Chrome
Firefox
- Operating System (e.g. Windows, macOS, Ubuntu): 
Windows

**Comment by jelbourn** [comment]
Confirmed that `NgModel` behaves differently here than a plain text interpolation. Needs further investigation.

**Comment by gabra666** [comment]
Hi, thanks for taking a look at this, my end goal was to have a table where I could add and remove rows dynamically, the rows as in the example are inputs connected with ngModel, I aslo wanted to be able to filter and sort this table.
So far everything else worked except for this "duplication/render" issue, it would be great if someone can point to a possible workaround.

**Comment by garrettld** [comment]
This isn't an issue with the material or cdk table, but rather with the way you're using the ngModel directive. TL;DR: use a unique indentifier for the "name" input on the ngModel and it'll work.

I ran into this issue at work with the PrimeNG p-table, among other things. Essentially you can't use ngModel in a form with an index-based name if you expect the items to be rearranged. For some reason when you do this the ngModel directive gets out of sync with the ngForm. The fix is to use a "name" for the ngModel that uniquely identifies the object being bound instead of using the index.

I was never able to figure out why this happens, but if you inspect the ngModel directive and the ngForm directive at runtime you can see that their values don't match up. I've updated your StackBlitz example (https://stackblitz.com/edit/ngmodel-material-table-fix?file=app/table-basic-example.html) to show how binding the "name" property on ngModel to a unique identifier (the "position" property, in this case) fixes the problem, and to show how the form gets out of sync when using an index-based name.

If you use the button at the top of the StackBlitz example to toggle the fix off and walk through your reproduction steps while watching the form value below the table, you can see that the form value doesn't really make sense. When you get to Step 4 where there are just two rows ("Hello" and "Hello2") you might expect the form value to look like this:

```json
{
  "position-0": 11,
  "name-0": "Hello",
  "position-1": 12,
  "name-1": "Hello2"
}
```

But instead it'll look like something like this:
```json
{
  "position-1": 1,
  "name-1": "Hydrogen",
  "position-10": 10,
  "name-10": "Neon",
  "position-11": 11,
  "name-11": "Hello",
  "position-12": 12,
  "name-12": "Hello2",
  "position-0": 11,
  "name-0": "Hello"
}
```

**Comment by gabra666** [comment]
Thank you very much this hepled me a lot! In my case (similar but not the same as in the stackblitz) I have used an Id that comes from the backend, my next issue was to add new Items to the table, since they are created in the frontend they did not have a generated Id, I added a prefix and a counter for those new elements as an Id and it works as expected :) 

Thanks a lot! @garrettld
