### ISSUE TITLE
help(Mat Datepicker): Do not autocomplete date when focus is out

### ISSUE THREAD

**Issue by AcarMeel** [angular/components#20741]
#### What are you trying to do?

I've setup a datepicker and I want to type 1 and focus out the input and keep the 1. But instead the datepicker gets autocompleted with 1/1/2001. My client doesn't like that!!

`<mat-form-field appearance="fill">
  <mat-label>Choose a date</mat-label>
  <input matInput [matDatepicker]="picker">
  <mat-datepicker-toggle matSuffix [for]="picker"></mat-datepicker-toggle>
  <mat-datepicker #picker></mat-datepicker>
</mat-form-field>`

#### What troubleshooting steps have you tried?

Pressing tab or leaving the focus out of the input autocompletes the date and I dont want that

#### Reproduction

The issue is easily reproduced in the same page of Angular Material documentation in browsers like Chrome, Safari, IE11, etc
https://material.angular.io/components/datepicker/overview

Steps to reproduce:
1. Go to https://material.angular.io/components/datepicker/overview
2.  Find a datepicker
3. Type 1
4. Press tab or focus the input out
5. See how date gets autocompleted with 1/1/2001
6. My expectation is if I type 1 then leave it as 1. We take care of validations.
  
#### Environment

All browsers, All devices, All OS.

**Comment by crisbeto** [comment]
It works that way, because by default, the datepicker uses a date adapter that parses the value using `new Date`. The date constructor parses out the string `1` as January 1st 2001, you can test it out yourself by running `new Date('1')` in the console.

There are a couple of ways around it:
1. You can create a custom data adapter that either extends the `NativeDateAdapter` and customizes the parsing logic, or implements all of the date handling itself.
2. You can use the `MomentDateAdapter`. Note that it comes with a dependency on moment.js.

There's some more information in the docs: https://material.angular.io/components/datepicker/overview#choosing-a-date-implementation-and-date-format-settings

**Comment by AcarMeel** [comment]
Oh I see. Thanks for the clarification
