### ISSUE TITLE
bug(MatAnchor): cdk-focused class added on disabled MatAnchor button

### ISSUE THREAD

**Issue by darkoandreev** [angular/components#20756]
Hello everyone,
First, I have a question related to the disabled state of the buttons - if the button (no matter which type is) is disabled, it shouldn't be focused with FocusMonitor, right?

I found a problem with the MatAnchor button. The disabled state of the button also can be focused by clicking on it, which is not correct probably because every other button doesn't have this "feature".
I used your [stackblitz](https://stackblitz.com/angular/jrvkvbxxjon?file=src%2Fapp%2Fbutton-overview-example.ts) and I disabled the first anchor button.

This is the actual problem I'm talking about:

![image](https://user-images.githubusercontent.com/20442015/95562586-06422d00-0a25-11eb-8732-9ffc62f7b240.png)

Please let me know if this is a valid problem and how can be fixed. Thanks in advance!

**Comment by crisbeto** [comment]
The problem is that anchors can't actually be disabled. We simulate it on `mat-button`, because the selector matches both anchors and native buttons. There are a couple of ways around it, but neither of them is great:
1. Set `point-events: none` on the element when it's disabled. The problem with this is that it'll allow users to click on elements behind the anchor.
2. Stop monitoring focus if the link is disabled. While this will remove the `cdk-mouse-focused` class, it doesn't change the fact that the anchor still has focus.

**Comment by darkoandreev** [comment]
> The problem is that anchors can't actually be disabled. We simulate it on `mat-button`, because the selector matches both anchors and native buttons. There are a couple of ways around it, but neither of them is great:
> 
> 1. Set `point-events: none` on the element when it's disabled. The problem with this is that it'll allow users to click on elements behind the anchor.
> 2. Stop monitoring focus if the link is disabled. While this will remove the `cdk-mouse-focused` class, it doesn't change the fact that the anchor still has focus.

Thanks @crisbeto for your nicely explained answer!

However, do you have any plans of removing the `cdk-mouse-focused` class for the anchors, or this should be done by the dev using the material library?

**Comment by crisbeto** [comment]
We may end up removing it, but I can't give any guarantees. You may be better off adding `:not(.mat-button-disabled)` to your focus selectors.
