### ISSUE TITLE
bug(mat-button):  Button focus is imperceptible in high-contrast mode

### ISSUE THREAD

**Issue by mikzat** [angular/components#20820]
#### Reproduction

Open any page that has a MatButton while using High Contrast mode:

![image](https://user-images.githubusercontent.com/6393085/96312461-86860680-0fc0-11eb-86cb-1e1ac8cbf6fc.png)
 
 
#### Expected Behavior

Buttons should only receive an outline when a user has focused the button.

#### Actual Behavior

All buttons always have the outline, regardless of focus state.

#### Environment

- Browser(s): Firefox, Edge
- Operating System: Windows, MacOS

**Comment by crisbeto** [comment]
FWIW, buttons do have focus treatment specifically for high contrast mode, but I agree that it's difficult to see. It works this way, because we can't add another outline to the button and I'm not sure that I agree with the statement that "Buttons should only receive an outline when a user has focused the button". If buttons don't have an outline from the start, it'll be difficult to tell that they're buttons in the first place since it's usually background color that distinguishes them.

What we can do instead is to make the outline thicker on focus. I'll play around with it to see how it behaves.

**Comment by mikzat** [comment]
> If buttons don't have an outline from the start, it'll be difficult to tell that they're buttons in the first place since it's usually the background color that distinguishes them.

I haven't checked across all browser/OS combinations, but the native behavior of HTML buttons in high-contrast mode seems to be no outline unless focused, so Angular seems is doing something unique here which might be surprising to someone who is used to the native behavior. That said, a thicker outline would already be an improvement.
