### ISSUE TITLE
MatTabGroup animation goes the wrong way in RTL

### ISSUE THREAD

**Issue by ahmedkhairydev** [angular/components#20838]
#### Reproduction

StackBlitz to get my issue: https://stackblitz.com/edit/components-issue-yxyjcs?file=src/app/example-component.html

Steps to reproduce:
1. move between the tabs by clicking on it, you will find the animation way from left to right not right to left...
2. move between the tabs using the arrows, unacceptable behavior happens... 

#### Expected Behavior

What behavior were you expecting to see?
The animation should be from right to left when the RTL mode is active.
Pagination Arrow is not working correctly.

#### Actual Behavior

What behavior did you actually see?
the animation way from left to right in the RTL mode.
unacceptable behavior happens, when using pagination arrow... 

#### Environment

- Angular: **latest**
- CDK/Material: **latest**
- Browser(s): **chrome**
- Operating System (e.g. Windows, macOS, Ubuntu):  Windows

**Comment by crisbeto** [comment]
It's because you've placed the element with `dir="rtl"` outside of the Angular app. We only look for elements with `dir` inside the app and on the `body` and `html` tags. [Here's a working fork of your example](https://stackblitz.com/edit/components-issue-vcuxpm?file=src%2Fapp%2Fexample-component.html). The only change is that I moved the `dir="rtl"` to a `div` inside the app.

**Comment by ahmedkhairydev** [comment]
> The only cha

I think you should look also at `direction: rtl`, because I didn't know that before. Thanks, bro ❤
