### ISSUE TITLE
bug(mat-datepicker): value change firing on filter re assign

### ISSUE THREAD

**Issue by pgg** [angular/components#20967]
#### Reproduction

https://stackblitz.com/edit/angular-ivy-eaktsw?devtoolsheight=33&file=src/app/app.component.ts

Steps to reproduce:
open stackblitz, look at console output, value change triggered incorrectly
 
#### Expected Behavior
value change to fire only when value has changed, not when filter changes

#### Actual Behavior
value change firing for same values

#### Environment
- Angular: 10.2.1
- CDK/Material: 10.2.7
- Browser(s): Version 86.0.4240.111 (Official Build) (x86_64)
- Operating System (e.g. Windows, macOS, Ubuntu): macOS

**Comment by crisbeto** [comment]
We can't do a whole lot here, because we only tell the validator to revalidate and then it determines on its own whether to dispatch the change event. I've submitted #20970 which will prevent the event from firing if a new function with the same result is called, but that won't fix your example, because the validation state changes on each assignment (`false` -> `true` -> `false`).

**Comment by pgg** [comment]
still does not make sense that a change event is fired for the same value regardless of validation result? fyi (dateChange) event is not triggered for the same. as a side note: [matDatepickerFilter] does not work with the async pipe: Type '((date: Date | null) => boolean) | null' is not assignable to type 'DateFilterFn<Date | null>'

**Comment by crisbeto** [comment]
We have control over `dateChange` so we can dispatch it only when it changes, but the `valueChange` event is handled by `@angular/forms` so all we can do is tell it that the validation state has changed and then it decides which events to trigger. You can file an issue on [angular/angular](https://github.com/angular/angular) if you think the behavior should be changed.
