### ISSUE TITLE
bug(matTooltip): type should not just be string (null | undefined)

### ISSUE THREAD

**Issue by james-schwartzkopf** [angular/components#21038]
#### Reproduction

After updating to Angular 11 we started getting errors with [matTooltip].  Looking at the setter, it checks for != null which should cover both null and undefined, but the type only allows string. 

Use StackBlitz to reproduce your issue: https://stackblitz.com/fork/components-issue

I tried to reproduce with StackBlitz, but can't seem to replicate the errors there.  Does the strictTemplates flag not work with StackBlitz?

With strictNullChecks and strictTemplates set to true in tsconfig.json, we expect this template to compile:
```<div [matTooltip]="undefined">Testing</div>```
 
 Obviously in our real case we have a property that may or may not have a tooltip depending on the data.

#### Expected Behavior

We expect tooltips with null/undefined to compile

#### Actual Behavior
Type 'undefined' is not assignable to type 'string'

Errors compiling the template when using strictTemplates & strictNullChecks

#### Environment

- Angular: 11
- CDK/Material: 11
- Browser(s): N/A
- Operating System (e.g. Windows, macOS, Ubuntu): N/A (Windows)

**Comment by crisbeto** [comment]
From what I can tell, the type has always been just `string` since the component was implemented 4 years ago. Your error likely wasn't being flagged, because the old compiler's type checker wasn't as thorough as the one in Ivy. Making it nullable would be a breaking change at this point since apps reading the value would have to be updated. We can't change only the setter since TS requires the types of getters and setters to match. 

Closing the issue since changing the type won't be worth the churn of going through the breaking change process. You can work around it in your case by changing the `null` value to an empty string.
