### ISSUE TITLE
bug(MatSort): Selection the header text in a column in the Firefox / Chrome etc. browsers generates an event.

### ISSUE THREAD

**Issue by peteichuk** [angular/components#21093]
#### Reproduction

Usage Firefox / Chrome browser (any or latest version on your platform OS).

Use StackBlitz to reproduce your issue: https://stackblitz.com/angular/onqyardnexv?file=src%2Fapp%2Ftable-sorting-example.ts

Steps to reproduce:
1. Select header text in the table
 
 
#### Expected Behavior

Only select text without generating event sort

#### Actual Behavior

Selection text in the header column generate event sort

#### Environment

- Angular: 8.x, 9.x, 10.x
- CDK/Material: 8.x, 9.x, 10.x
- Browser(s): Firefox
- Operating System: Windows 10 (32x, 64x), macOS (Catalina latest), Ubuntu 16.04 (64x amd64 architecture).

**Comment by peteichuk** [comment]
Because I usage [angular-resizable-element](https://github.com/mattlewis92/angular-resizable-element) module to resize the column, I have a problem with sorting. Sorting generates an event when I resize the column in Firefox.

To highlight the text in the header and resize, no sorting event should be generated.

**Comment by crisbeto** [comment]
All the sort header has is a single `click` listener that changes the sort direction. Since a click is defined by "pressing down and releasing over the same element", it means that if you were to start selecting text on the header and then release your pointer over it, it would trigger a click. I don't think that we can do anything about it, aside from disable text selection, but that wouldn't be desirable either.
