### ISSUE TITLE
bug(datepicker): if given YYYY-MM-YY format, date picker can pick sometimes previous day because of timezone difference

### ISSUE THREAD

**Issue by ayhanyildiz** [angular/components#21104]
#### Reproduction

Use StackBlitz to reproduce your issue: https://stackblitz.com/fork/components-issue

Steps to reproduce:
1. copy paste 1970-12-23 into datepicker field
2. on blur datepicker sets selected date.
 
 
#### Expected Behavior

What behavior were you expecting to see?
always select pasted date

#### Actual Behavior

What behavior did you actually see?
based on timezone it sets to previous date

#### Environment

- Angular: 10
- CDK/Material: 10
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Win10

**Comment by crisbeto** [comment]
By default, our date parsing is limited to basically `new Date(value)` since handling all possible use cases and date libraries would be impractical. There's some [more information in the docs](https://material.angular.io/components/datepicker/overview#choosing-a-date-implementation-and-date-format-settings), but the options for resolving it are:
1. Implement your own date adapter, either by extending the `MatNativeDateAdapter` that Material comes with, or from scratch.
2. Use an existing date adapter like the `MomentDateAdapter`.

**Comment by ayhanyildiz** [comment]
Thanks for the response.
-since handling all possible use cases and date libraries would be impractical. 
I disagree. You have input field, either people select from date picker or write date. If you are taking user input and  selecting something wrong based on their input, date picker at least not let me enter that way.

Material UI got it right at least.
