### ISSUE TITLE
bug in lastPageIndex calculation

### ISSUE THREAD

**Issue by Ash-kosakyan** [angular/components#21133]
https://github.com/angular/components/blob/2c29265807a8da9c027205dea870cdb5bd5ebc15/src/material/table/table-data-source.ts#L307

In case of Math.ceil(paginator.length / paginator.pageSize) === 0, the value of lastPageIndex is -1

**Comment by crisbeto** [comment]
I spent a bit of time looking into this, but it turns out that it can't happen, because `MatPaginator` has some logic to guard against it here: https://github.com/angular/components/blob/master/src/material/paginator/paginator.ts#L136.

I'll close the issue, because the type of `MatTableDataSource` is set up only to accept `MatPaginator`.
