### ISSUE TITLE
feat(icon): mat-icon should have a size input

### ISSUE THREAD

**Issue by dpurp** [angular/components#21170]
#### Feature Description

Provide the ability to set the size of the mat-icon via input.

```html
<mat-icon size="24px">close</mat-icon>
```

#### Use Case
We frequently need to override the font-size, height, and width of the mat-icon via css in order to support alternate icon sizes.

**Comment by crisbeto** [comment]
This would basically be the equivalent of `[style.font-size.px]="24"` which isn't a whole lot more code. I'm not sure that it would make sense to bake it into the library, because different apps might have a different set of icon sizes and it's trivial to define a handful of classes that can be applied to an icon to change its size.
