### ISSUE TITLE
Is extending of cdk-table recommended / supported?

### ISSUE THREAD

**Issue by smnbbrv** [angular/components#21174]
Hi,

for one of the projects we need to use cdk tables with some of our logic on top.

While looking at mat-table, that extends cdk-table, we found out that the idea to extend the cdk-table might be not that bad.

However, the question is: is extension of cdk-table a valid approach?

It seems that there are some private injection tokens used https://github.com/angular/components/blob/4f776792d6a155b009ad410c63ded88a8a32af72/src/material/table/table.ts ; plus, generally the question of extending the classes that do not belong to you, might smell.

**Comment by crisbeto** [comment]
The CDK table is definitely meant to be extended since we've implemented the Material table on top of it. You're right that it currently references a couple of private injection tokens, but they're optional and the table should work correctly if you don't pass them in. The tokens are private while we're still figuring out how to support virtual scroll in the table, but once it's done, they'll become required and a public API. That'll happen in a major version so you'll have time to plan for it.

**Comment by smnbbrv** [comment]
Thank you @crisbeto
