### ISSUE TITLE
feat(cdk-drag-drop): Give a visual clue to which droplist can receive a specific dragged item.

### ISSUE THREAD

**Issue by adergham** [angular/components#21171]
#### Feature Description
Currently,
When dragging an item, the css class cdk-drop-list-receiving is displayed on all the droplists, even those that cannot receive the item due to the enterPredicate output.
This is misleading.

#### Use Case
Given that a dragged item is restricted to some drop lists, I want to display a visual clue about where I can drop this item

**Comment by crisbeto** [comment]
Looks it's because `isReceiving` [here](https://github.com/angular/components/blob/master/src/cdk/drag-drop/drop-list-ref.ts#L453) only looks at whether any connected siblings are active, but it doesn't account for the predicate. When fixing this, we have to be careful about performance, because `isReceiving` is invoked inside a data binding.
