### ISSUE TITLE
Angular Material Charts

### ISSUE THREAD

**Issue by vgb1993** [angular/components#21172]
#### Feature Description

I would like to propose Angular Material Charts, an integrated charting library built in Angular, ready to go!

As we all know, having the angular team providing components has a number of benefits, like compatibility, same day release, etc. Having to use another library for such an essential feature is a bit of a turn down.

#### Use Case

There is a growing need to display Analytic data, the potential use cases are infinite. 
I think the simpler apps could benefit from it specially.

I found a couple of issues regarding this topic #12867 #13940 . It's been 2 years now.

Any thoughts?

**Comment by jelbourn** [comment]
This is genuinely something I've wanted to pursue for years- I even had an intern slated to do some early explorations before COVID messed with internships this year. 

Despite wanting to do it, though, I don't see us realistically having the capacity for it any time remotely soon. Just off the top of my head, in no particular order, other projects that I'd want to tackle first:
* Promote mdc-based components to stable
* 2D drag-drop
* Promote auto-size virtual scroll to stable
* Integrate virtual scroll into other components (select, autocomplete, etc.)
* Promote cdk menu, listbox, combobox, and dialog to stable
* Create cdk tabs, progress
* Keyboard interaction manager for grid
* Revamp of cdk tree to make the API easier to use

Based on there being so much we want to do, I'm going to close this since it wouldn't see any real action in the near future.

**Comment by vgb1993** [comment]
I understand there's already a ton of work to do. Such a pity though.

There will always be new tasks for CDK and Material. Perhaps if a new team was made to look into this... in parallel with the other things you mentioned. I know, It's a long shot, and it does require a lot of effort. But the benefits..!

Anyway, thanks for the reply, enjoy your day!
