### ISSUE TITLE
mat-form-field with appearance outline incorrectly recalculate outline-gap when page dir is changed.

### ISSUE THREAD

**Issue by Serg-Mois** [angular/components#21177]
#### Reproduction

https://stackblitz.com/edit/material2-mat-form-field-outline-rtl-issue-mevppc?file=src/app/app.component.ts

Steps to reproduce:
1. Type any text to the input, click on FR, see on the input label.
 
 
#### Expected Behavior
outline gap at least fits its label position.

#### Actual Behavior
What behavior did you actually see?
![image](https://user-images.githubusercontent.com/37027173/100654774-fecb4000-3352-11eb-80d5-9ad656b67a7c.png)

formField.updateOutlineGap() doesn't help.

What is the correct way to change the direction (rtl or ltr ) for all material components in runtime in one place?
Because the similar problem with the mat-dialog, when you must explicitly indicate the direction in all places in the dialog.open() config, even if the root HTML tag has an appropriate dir attribute. 

#### Environment

- Angular: 11.02
- CDK/Material: 11.01
- Browser(s): Chrome 86
- Operating System (e.g. Windows, macOS, Ubuntu):  Windows

**Comment by mmalerba** [comment]
The expected way to change the direction on the app is to have a `[dir]="direction"` binding on the root element. However this does not change the direction for dialogs because they are inserted under the `<body>` element. The best way to handle this currently is to inject the `Directionality` in the component that opens the dialog and pass the current value along to the dialog. I'll leave this open as a feature request to make this more automatic.

**Comment by jelbourn** [comment]
Closing since I don't think we'll change anything here- if the `dir` changes outside of the Angular context we don't have a way of knowing about it, and changing `dir` at run-time is a relatively niche case
