### ISSUE TITLE
bug(cdk-virtual-scroll-viewport): Inexplicable scroll when removing item in mat-checkbox click handler

### ISSUE THREAD

**Issue by ctusch** [angular/components#21197]
#### Reproduction

https://stackblitz.com/edit/cdk-virtual-scroll-bug?file=src/app/app.component.html

Steps to reproduce:
1. Click on any of the numbered checkboxes.
 
 
#### Expected Behavior

The item should be removed (see `click` handler) and the scroll position should stay the same.

#### Actual Behavior

The item is removed but the container scrolls down more than a page.

#### Environment

- Angular: 10.2.3
- CDK/Material: 10.2.7
- Browser(s): Chrome 86
- Operating System (e.g. Windows, macOS, Ubuntu): Windows 10

#### Further Information

This behavior only happens when using the `click` handler of a `mat-checkbox`.

Using a `button`'s `click` handler works fine.

Executing the same handler in a `mat-checkbox`'s `ngModel` two-way binding (using a setter) also works fine.

I have found two workarounds:
1. Disable template caching in `*cdkVirtualFor` (`templateCacheSize: 0`).
2. Use `setTimeout` in the `click` handler.

**Comment by crisbeto** [comment]
Here's what I _think_ is happening: when an element receives focus, the browser will automatically scroll it into view. Since the virtual scroll container tries to reuse elements rather than create new ones, the element you just removed goes either to the end of or the start of the list and the browser tries to move it into the view since it received focus as a part of the click sequence. This isn't a problem with a regular `ngFor`, because the element is removed from the DOM and isn't able to receive focus.

I'm closing the issue, because I don't think that we can do much about it, without sacrificing part of the performance of the virtual scroll (e.g. pulling the element out of the DOM and putting it back in later).

**Comment by ctusch** [comment]
Thank you for the explanation. I think you are spot-on since I saw this behavior in some of my other tests. But what it doesn't explain is why this doesn't happen when using a two-way binding to `mat-checkbox`'s `ngModel` and removing the element in the setter. Maybe Angular introduces something like `setTimeout` which decouples the actual click from the remove?
