### ISSUE TITLE
bug(MatSelect): NVDA announce 'table' when select options opened 

### ISSUE THREAD

**Issue by exlnik** [angular/components#21480]
When opening `mat-select` element  NVDA screen reader announce `table` before announcing the `list`.

#### Reproduction

See the official example from material documentation. 

Steps to reproduce:
1. Click on the mat-select 
2. When the options opened NVDA announce `table` and then `list`.
 
 
#### Expected Behavior
`table` should not be announced.

#### More details

- This is a new issue. In Material V10 it's Ok. (checked also in the documentation of v10)
- Faced it with NVDA
- Happened in Chrome, not in Firefox.

#### Environment

- Angular: V11
- CDK/Material: V11
- Browser(s): Chrome
- Screen reader: NVDA

**Comment by nirkai** [comment]
Form what I can see it cause by the addition of the `aria-owns` [mentioned here](https://github.com/angular/components/blob/71b7b15958ee732fbe1398d68705143eb0e820e3/src/material/select/select.html#L2) and implemented there.

**Comment by crisbeto** [comment]
I can reproduce it as well. I think that @nirkai is correct, because I get the following structure in the "Accessibility" panel in the dev tools:

![Angular_Material_-_Google_Chrome_2021-01-04_14-31-32](https://user-images.githubusercontent.com/4450522/103535563-9ca5b380-4e99-11eb-8739-3d631cfd5ad3.png)

The `LayoutTable` from the screenshot points to `.mat-select-trigger`. While the element is a `div`, it has some CSS that is `display: inline-table`. I wonder whether that's not throwing the browser off?

**Comment by nirkai** [comment]
@crisbeto it is indeed.
If you remove that style it's gone from the Accessibility panel
