### ISSUE TITLE
bug(COMPONENT): Class name 'cdk-visually-hidden' should not have tab index = 0

### ISSUE THREAD

**Issue by kaydeejay** [angular/components#21565]
axe tool is throwing error for cdk: aria-hidden elements must not contain focusable elements

#### Expected Behavior

What behavior were you expecting to see?
- Elements with class cdk-visually-hidden should not have tabIndex or tabIndex should be equal to -1

#### Actual Behavior

What behavior did you actually see?
- Elements with class cdk-visually-hidden have tabIndex of 0

#### Environment

- Angular: 9
- CDK/Material: 9
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

**Comment by jelbourn** [comment]
I assume you're taking about the elements we render for focus traps in dialogs, etc. This is working as intended on our side, and is a false positive in axe. Axe's lint check assumes it's used in an application context and that its findings represent accidental tabbable + invisible elements. However, the focus trap elements are intentionally built this way in order to meet the requirements for dialog accessibility.
