### ISSUE TITLE
bug(menu): Disabled menu item won't show tooltip

### ISSUE THREAD

**Issue by Totati** [angular/components#21741]
#### Reproduction

https://stackblitz.com/edit/disabled-mat-menu-item-mat-tooltip?file=src/app/menu-overview-example.html

Steps to reproduce:
1. Open menu
2. Hover disabled menu item
 
#### Expected Behavior

Tooltip shows

#### Actual Behavior

Tooltip won't pop

#### Cause
https://github.com/angular/components/blob/master/src/material/menu/menu.scss#L53

#### Environment

- Angular: 10,11
- CDK/Material: 10,11
- Browser(s): Latest Chormium Edge
- Operating System (e.g. Windows, macOS, Ubuntu): Windows 10

**Comment by crisbeto** [comment]
This won't work even if we removed the `pointer-events: none`, because the browser doesn't dispatch `mouseenter` and `mouseleave` events on disabled `button` elements. Technically it would work if you put the `mat-menu-item` on a non-button element, but that has accessibility implications. I'm closing the issue, because removing the `pointer-events` would re-introduce the issue mentioned in the comment. Furthermore, the specificity is low enough that you should be able to override it in your app.
