### ISSUE TITLE
bug(cdk): positionStrategy of an Overlay only works with Zone.js

### ISSUE THREAD

**Issue by chrisguttandin** [angular/components#21786]
#### Reproduction

Steps to reproduce:
1. Create an Angular app without zone.js.
2. Create an `Overlay` with a `positionStrategy`.
 
 
#### Expected Behavior

The positionStrategy should be applied.

#### Actual Behavior

The positionStrategy gets not applied.

#### Environment

- Angular: 11.1.1
- CDK/Material: 11.1.1
- Browser(s): any
- Operating System (e.g. Windows, macOS, Ubuntu): any

I think the reason why this doesn't work is because the positionStrategy only gets applied after the zone became stable. However the [`NoopZone`](https://github.com/angular/angular/blob/a3b08644280fb43d9dfd037927c4e6a48a2c9a46/packages/core/src/zone/ng_zone.ts#L420-L448) that Angular uses when being configured to not use zone.js doesn't fire a stable event.

https://github.com/angular/components/blob/d3deb8b9c61f79f6a4ab75d74914aac3b43592bf/src/cdk/overlay/overlay-ref.ts#L124-L134

To save others some time debugging this as well I think it would be helpful to log at least a warning in dev mode when someone uses the `NoopZone`.

I'm not sure though what could be a good fallback for apps without zone.js.

There is also a very brought ticket for supporting zone-less apps (#9169) which is somehow related. I thought it still makes sense to create a specific ticket for this problem. Please feel free to close it if everything regarding zone-less support should be tracked with the other one.

**Comment by jelbourn** [comment]
This isn't really a bug, just an unfortunate fact that we currently have a hard dependency on zones right now. Without zones, we don't have an effective way to know when Angular finished rendering to perform the positioning. 

I do want to resolve this, but I don't see us being able to make any changes here in the components repo without making progress on making zoneless-Angular a better-supported option on the framework side. Closing since this is already tracked in #9169.
