### ISSUE TITLE
bug(cdk/cdkTextareaAutosize): size is not properly set with display none

### ISSUE THREAD

**Issue by vtertre** [angular/components#21866]
#### Reproduction

https://stackblitz.com/edit/components-issue-pnodhc?file=src%2Fapp%2Fexample-component.html

Steps to reproduce:
1. Hover the blue area
 
#### Expected Behavior

The textarea should have the size matching 3 rows without having to edit the field.

#### Actual Behavior

The textarea shows up on a single line even though `cdkAutosizeMinRows="3"` is set and the value has a line break.

#### Environment

- Angular: 11.1.0
- CDK/Material: 11.1.1
- Browser(s): Chrome, Firefox
- Operating System (e.g. Windows, macOS, Ubuntu): macOS

**Comment by Totati** [comment]
Hi, instead of `display: none` use `visibility: hidden`. https://stackblitz.com/edit/components-issue-e6i9eg?file=src%2Fapp%2Fexample-component.css

**Comment by vtertre** [comment]
Hi, thanks for your answer.
That's my current workaround but it also forces to add hacky CSS rules to work with the fact that a `visibility: hidden` element still occupies space on the page.

**Comment by crisbeto** [comment]
Closing the issue, because unfortunately we can't do much about it. The way the it works is by measuring how tall the content is supposed to be and setting it to the `textarea` element. When the element is inside a `display: none` parent, the browser will return that the size is 0. It can be worked around by polling the DOM for size changes, but that will be really inefficient. Alternatively, you can get a hold of the `CdkTextareaAutosize` instance and call `resizeToFitContent` when you know that it's visible.
