### ISSUE TITLE
bug(Mat-Tab): Clicking a half-visible tab doesn't work with non-default animationDuration

### ISSUE THREAD

**Issue by LanderBeeuwsaert** [angular/components#21898]
#### Reproduction

See the video in attachment

Steps to reproduce:
1. setup a mat-tab with:
{ provide: MAT_TABS_CONFIG, useValue: { animationDuration: 1 } }
2. click a tab that is only half-visible. 
 
#### Expected Behavior

Tab should jump into view AND become selected.

#### Actual Behavior

The tab jumps into view, BUT it doesn't become selected.

#### Environment

- Angular: 11.2
- CDK/Material: 11.2
- Browser(s): chrome
- Operating System (e.g. Windows, macOS, Ubuntu):  windows & Ubuntu
[bug-2021-02-12_16.14.43.mkv.zip](https://github.com/angular/components/files/5976025/bug-2021-02-12_16.14.43.mkv.zip)

**Comment by crisbeto** [comment]
I can sort of see it happening here: https://stackblitz.com/edit/angular-9sk3pv?file=src/app/tab-group-dynamic-example.ts. What I _think_ is happening is that the we start scrolling the header on `focus` which is around the same time as `mousedown`. Since the element is being moved out from under the pointer before the `click` is finished, it sometimes gets interruped.

**Comment by LanderBeeuwsaert** [comment]
weird, if I try the stackblitz, the animation has the default duration

**Comment by crisbeto** [comment]
`animationDuration` only affects the animation of the content, not the one in the header.

**Comment by LanderBeeuwsaert** [comment]
ah, well, we use it in combination with NoopAnimationsModule instead of BrowserAnimationsModule.
If I add that to the stackblitz I reproduce the issue we have:
https://stackblitz.com/edit/angular-9sk3pv-px8i8g?file=src%2Fmain.ts
