### ISSUE TITLE
bug(form-field): value is outside of custom form-field

### ISSUE THREAD

**Issue by AlexElin** [angular/components#21927]
#### Reproduction

Use StackBlitz to reproduce your issue: 
https://angular-se8kla.stackblitz.io/

Steps to reproduce:
1. Open [StackBlitz example](https://stackblitz.com/angular/pxgvxrxpbeqn?file=src%2Fapp%2Fform-field-custom-control-example.ts) for a custom form field from [the docs](https://material.angular.io/components/form-field/examples)
2. In the template add `<span class="example-tel-input-spacer">&ndash;</span>` before and after the last `input`.
3. Click on the field
 
 
#### Expected Behavior

The last span's value is inside the field

#### Actual Behavior

The last span's value goes beyond the field
![form](https://user-images.githubusercontent.com/13061803/108122476-645add00-70b5-11eb-992c-72a542f32b8c.jpg)

#### Environment

- Angular: 11.0.0
- CDK/Material: 11.2
- Browser(s): Google Chrome
- Operating System (e.g. Windows, macOS, Ubuntu):

**Comment by jelbourn** [comment]
@AlexElin I believe the issue here lies in the custom control css in the stackblitz you provided. `example-tel-input-container` is `display: flex` with `overflow: visible`, so when its children grow larger than the content of `.example-tel-input-container`, they overflow the element instead of making it larger.
