### ISSUE TITLE
Add input to control map marker icon

### ISSUE THREAD

**Issue by mattstarkey** [angular/components#22097]
I am struggling to find a way to update the MapMarker icon using @angular/google-maps.

Here is a Stackblits example of what I am trying to do:
[Link to stackblits](https://stackblitz.com/edit/angular-u7vsmu?file=src/app/app.component.ts)

So every 3 seconds I would like to change the marker to either green or blue, this is just simulating a real world scenario.

The documentation states that MapMarker component wraps the google.maps.Marker class, so I should be able to use the .setIcon() method, but I am unsure of how to access the google.maps.Marker class in this case.

In this issue: [https://github.com/angular/components/issues/21068](https://github.com/angular/components/issues/21068)

The response comments notes that in this case I should not have to create the google.Maps.Marker object which makes sense, but when I change the MapMarker object inside my markers array I also get no change.

Does anyone have any experience with this that could share a solution or point me in the right direction?

**Comment by crisbeto** [comment]
It's because you have to provide a new `options` object when you want to swap out the icon. Here's a working example: https://stackblitz.com/edit/angular-2jlrcu?file=src%2Fapp%2Fapp.component.ts.

That being said, I think that it makes sense to control the icon independently from the `options` so I'll turn this into a feature request.
