### ISSUE TITLE
bug(cdk/scrolling): CDK performance degrades for large lists

### ISSUE THREAD

**Issue by yonyk** [angular/components#22109]
I noticed that using the CDK virtual scroll directive to render large lists (e.g., 1-2M lines) suffers from severe performance degradation. This was surprising because the virtual scroll only renders a handful of lines (that's the whole point of using virtual scrolling!). After some investigating I noticed that if my component gets the list of items to render as an input parameter, performance degrades. However, if the list of items is defined internally, performance is great.

For example, this gives me great scrolling performance ([StackBlitz](https://stackblitz.com/edit/angular-wezvuh-enusa1?file=app/cdk-virtual-scroll-overview-example.ts)),

```ts
@Component({
  selector: 'long-list',
  template: `
    <cdk-virtual-scroll-viewport itemSize="15">
      <div *cdkVirtualFor="let item of items">{{item}}</div>
    </cdk-virtual-scroll-viewport>`
})
class LongListComponent {
  items: string[] = Array.from({length: 2e6}).map((_, i) => `Item #${i}`);
}
```

This gives me poor performance ([StackBlitz](https://stackblitz.com/edit/angular-wezvuh-bywb25?file=app/cdk-virtual-scroll-overview-example.ts)),

```ts
@Component({
  selector: 'long-list',
  template: /* Same as above */,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
class LongListComponent {
  @Input() items: string[] = [];
}

@Component({
  selector: 'my-app',
  template: `<long-list [items]="appItems"></long-list>`
})
class MyApp {
  appItems: string[] = Array.from({length: 2e6}).map((_, i) => `Item #${i}`);
}
```

You'll see what I mean if you scroll down/up quickly in either example. Of course when the component template is more complex and the view hierarchy is deeper the performance difference is much more pronounced. In my case it makes virtual scroll hardly usable.

Looking at the performance profile, it seems like change detection is kicking in as I scroll and doing processing that apparently scales up along with the size of the list. If that's true, it means that even modestly long lists are suffering from excessive processing.

**Comment by jelbourn** [comment]
@mmalerba or @crisbeto is there something we would be doing internally that would impact this?

**Comment by mmalerba** [comment]
Adding `changeDetection: OnPush` to the poor performance example fixes it: https://stackblitz.com/edit/angular-wezvuh-r8isep?file=app/cdk-virtual-scroll-overview-example.ts, but we can't just require everyone to have all `OnPush` components. 

I suspect this is the source of the issue: https://github.com/angular/components/blob/master/src/cdk/scrolling/virtual-scroll-viewport.ts#L415-L418

It was originally `markForCheck`, and then we changed it to `detectChanges` (https://github.com/angular/components/pull/12158), however that broke certain cases so we had to change it back (https://github.com/angular/components/pull/12329).

What we really need is not to trigger change detection on the root, but to trigger it for the items. Maybe we could do something like having the items inject their change detector and calling `detectChanges()` on that rather than the viewport's change detector?

**Comment by jelbourn** [comment]
@mmalerba could you set up some time to pair with Misko on this? I think he would be interested in this use-case and might have some insights on options

**Comment by mleibman** [comment]
This seems to be purely a result of debug checking from not running in prod mode (`enableProdMode()`).
In my testing, enabling prod mode brings each frame (`Animation frame fired`) in fast scrolling from **~122ms** to **~1.2ms**.

**Comment by mhevery** [comment]
Closing as this issue only shows up in dev mode.

In dev-mode Angular performs additional change detection in order to detect circular data flows and throw `ExpressionChangedAfterItHasBeenCheckedError`. This is done on the input levels of all components. Because developers often create new arrays which have same content, Angular can't just check the array identity, and instead Angular deep checks the array to make sure that the items in the array are stable. (In this case Angular has to deep checki array of 2M items)

If you run the example in the dev-tools performance and do buttom-up you will see that 75% of time is spent in `devModeEqual` functions which checks if current vs previous inputs are same and it does deep checking for arrays.  This check only happens in dev-mode.

As pointed out going to prod mode removes this checking and returns the performance to normal. 

I don't believe there is anything which needs to be done here and so I am closing this issue.

**Comment by yonyk** [comment]
Thank you for taking the time to look into this.

If I understand correctly, in dev mode Angular will do array deep checking while in prod mode it won't. Does that mean that in prod mode it only does an identity check? E.g., in prod mode if I want to add items to the array, I can't just push them, I have to construct a new array to force an identity change?
