### ISSUE TITLE
bug(datepicker): Harness is not working with readonly

### ISSUE THREAD

**Issue by csutorasr** [angular/components#22190]
#### Reproduction

https://stackblitz.com/edit/harness-issue-sk1bax

Steps to reproduce:
1. Try to openCalendar with readonly input.
 
 
#### Expected Behavior

What behavior were you expecting to see?

An open calendar.

#### Actual Behavior

What behavior did you actually see?

The input is readonly, so the keys are not sent to the input.

https://github.com/angular/components/blob/master/src/material/datepicker/testing/datepicker-input-harness.ts#L50

#### Environment

This is not working on any environment.

**Comment by crisbeto** [comment]
This is a valid bug, but unfortunately we can't do much about it, because the only way to open the calendar through input is using the alt + down arrow keys. The input has an internal check that won't allow it to open if it's `readonly`. You can work around it by adding a `mat-datepicker-toggle` and using the `MatDatepickerToggleHarness`.
