### ISSUE TITLE
bug(Datepicker): ISO date string in matStartDate/matEndDate input is changed.

### ISSUE THREAD

**Issue by Nightsphere** [angular/components#22535]
#### Reproduction

Steps to reproduce:
1. Use any example of the Datepicker on the Angular Material website, for example the [Date range picker forms integration](https://material.angular.io/components/datepicker/examples#date-range-picker-forms)
2. Click on the start date and enter in an ISO date string, e.g. `2021-04-20`.
3. Click anywhere else or tab to the end date input, and the start date display and value will both be set back a day.
4. Repeating steps 1-3 with another day on the end date input will produce the same result.
 
#### Expected Behavior

What behavior were you expecting to see?
When `2021-04-19` is given to the start date, and `2021-04-21` is given to end date, the datepicker value and display is set to
what was typed, and the range would be from April 19th, 2021 to April 20th, 2021 instead of April 18th, 2021 to April 20th, 2021.

#### Actual Behavior

What behavior did you actually see?

A day is being taken off. I've read in similar questions that is has to do with the fact that the time is midnight,
and therefore takes it as the day before, whereas if given `04/20/2021`, the time is somewhere in the middle of
the day. Is this intended?

What's confusing is the Selected range and shown range differ:
![image](https://user-images.githubusercontent.com/22484403/115629662-079bbe80-a2c0-11eb-957c-06c4690ec4e4.png)

If this is intended, is there a way to take the ISO given by the user and adding a day to it? I've tried some different
techniques, but the datepicker docs don't seem to be fully completed and I've had to make some guesses.

#### Environment

- Angular: 11.2.4
- CDK/Material: 11.2.4
- Browser(s): Google Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

**Comment by crisbeto** [comment]
Since it's difficult to account for all possible use cases, by default the datepicker uses the built-in `Date` constructor to parse and format dates which has some drawbacks. The example you posted above works for me, but it's likely because I'm a time zone closer to GMT. I'm closing the issue since it's working as expected. The recommended way to customize the date parsing behavior is to provide a different `DateAdapter`. See https://material.angular.io/components/datepicker/overview#choosing-a-date-implementation-and-date-format-settings.
