### ISSUE TITLE
bug(mat-sidenav-container): Right side scrollbar overlapped by fixed div in fullscreen sidenav-container

### ISSUE THREAD

**Issue by frct1** [angular/components#22578]
#### Reproduction

Here is [stackblitz ](https://stackblitz.com/edit/angular-juxu4i?file=src%2Fapp%2Fsidenav-overview-example.css)related to issue

Steps to reproduce:
1. Use [`fullscreen`] or absolute `mat-sidenav-container`
2. Add fixed to bottom div

 
#### Expected Behavior
As you can see at stackblitz fixed div is actually superimposed over right side scrollbar
Y-axis not being overlapped by fixed div

#### Actual Behavior

Y-axis scrollbar is overlapped by fixed to bottom div.

#### Environment

- Angular: 9+ 
- CDK/Material: 9+
- Browser(s): Chrome 89
- Operating System (e.g. Windows, macOS, Ubuntu):  Windows

**Comment by crisbeto** [comment]
Since you're projecting a custom `position: fixed` element on top of the sidenav container content, we can't do much about it. You can resolve it yourself by adding another wrapper div that is scrollable while the bottom black box remains inline. Quick example: https://stackblitz.com/edit/angular-juxu4i-usaqf1?file=src%2Fapp%2Fsidenav-overview-example.html.
