### ISSUE TITLE
Event outside form

### ISSUE THREAD

**Issue by leninsvg** [angular/components#22632]
#### Reproduction

Use StackBlitz to reproduce your issue: 
- Components: https://stackblitz.com/edit/angular-wvjmkt?file=src%2Fapp%2Fform-field-error-example.html

Steps to reproduce:
1. You need to have one control or form with reactive validations.
2. You make your html with a form tag an the put any handler that reset the form control or form group
3. When the button is outside of form works perfectly the form is resert, but when the button is on the form the erros of the form are not desapears.
4. For fix this problem I use div instead of a form. This problem has each component as mat-select, mat-form field, etc.
5. That is riddiculos because there are situations when you need work with forms no con divs for example submit when press key enter.
 
 
#### Expected Behavior

What behavior were you expecting to see?

#### Actual Behavior

What behavior did you actually see?

#### Environment

- Angular:
- CDK/Material:
- Browser(s):
- Operating System (e.g. Windows, macOS, Ubuntu):

**Comment by crisbeto** [comment]
What is the problem with the posted Stackblitz exactly? I didn't notice anything out of the ordinary and the issue description doesn't say either.

**Comment by Leningsv** [comment]
The problem is with events when you reset a form don't use a <form> </form>  these are reset, but when you use a form and submit reset event the <form> </form> elemens are not reset completely.  when you emit the reset event don't reset the styles error in a <form> </form> the inputs or elementos in the form has red color that is not normal .


________________________________
De: Kristiyan Kostadinov ***@***.***>
Enviado: jueves, 6 de mayo de 2021 13:48
Para: angular/components ***@***.***>
Cc: Lenin ***@***.***>; Author ***@***.***>
Asunto: Re: [angular/components] Event outside form (#22632)


What is the problem with the posted Stackblitz exactly? I didn't notice anything out of the ordinary and the issue description doesn't say either.

**Comment by wagnermaciel** [comment]
@leninsvg I believe the problem you are having is with form controls, not with the material form component. If this is still an issue, please file an issue under the angular/angular repository
