### ISSUE TITLE
bug(button): Opening sidenav with toolbar button leaves unwanted halo on button

### ISSUE THREAD

**Issue by steinrr** [angular/components#22653]
#### Reproduction

Use StackBlitz to reproduce your issue: 
- Components: https://stackblitz.com/fork/components-issue
- Harnesses: https://stackblitz.com/fork/harness-issue

Steps to reproduce:
1. Go to https://stackblitz.com/edit/angular-sh3y7i-1ydms4?file=src%2Fapp%2Fsidenav-overview-example.html
2. Click menu icon to open sidenav
3. Click outside left hand menu to close it again without selecting anything
4. Observe darker blue "halo" around menu button
 
#### Expected Behavior

What behavior were you expecting to see?
The menu button should be without darker blue halo.

#### Actual Behavior

What behavior did you actually see?
A darker blue color surrounds the menu button

#### Environment

- Angular: See stackblitz
- CDK/Material: See stackblitz
- Browser(s): Edge
- Operating System (e.g. Windows, macOS, Ubuntu): MacOs

**Comment by jelbourn** [comment]
This is working as intended- that is the button's focus style.

**Comment by PowerKiKi** [comment]
While the visual aspect of a focused button is intended to appear that way, I don't think the button should be in the focused state anymore.

That is not coherent with the normal usage of a button. Not only native browser buttons, but more specifically the Angular Material buttons. Ater they are *clicked*, they don't show the focused state anymore. And the menu button of the sidenav should behave in the same way.

You can reproduce the expected behavior in the first example of buttons on https://material.angular.io/components/button/overview. In the following screenshot, I just clicked on the button, and there is absolutely nothing that shows that, as expected.

If I click on the "same" button in a sidenav the visual aspect is different and thus incorrect.

![image](https://user-images.githubusercontent.com/72603/120971113-3d7cff80-c7a7-11eb-9971-d312dcfd04d4.png)

**Comment by Totati** [comment]
But that button was not clickked after sidenav closed, it got focused pogrammatically. When buttons are focused this way or via tab they get this halo effect.

**Comment by PowerKiKi** [comment]
Fair enough. Is there a way to prevent automatic focusing of that button when the sidenav is closed ?

**Comment by steinrr** [comment]
Have a look at the example named "Drawer with explicit backdrop setting" halfway down on this page linked here.

1. Set "Sidenav mode" to "over"
2. Click "Toggle drawer"
3. Click outside opened sidenav - e.g. in dark gray content area somewhere
4. See that the Toggle button keeps the "greyish color" that it had when it was clicked

Does this seem correct? To me this seems wrong.

Page:
https://material.angular.io/components/sidenav/overview
