### ISSUE TITLE
Support more meaningful options for dialog `autoFocus`

### ISSUE THREAD

**Issue by jelbourn** [angular/components#22678]
Currently, the `autoFocus` option of `MatDialogConfig` is a boolean, with the values meaning:
* `false` - default value, focused the `role="dialog`" element
* `true` - focuses the first tabbable element inside the dialog

This API is kind of confusing, since the dialog automatically focuses _something_ regardless of what you do, so `autoFocus: false` doesn't really make sense. 

Instead, we should change `autoFocus` to accept these values:
* `dialog` - focus the `role="dialog"` element
* `first-tabbable` - focus the first tabbable element
* `first-header` - focus the first header (h1 - h6) element in the dialog. It's still an open question whether this should force `tabIndex = -1`.
* A CSS selector- arbitrary CSS selector, the dialog would focus the first matching element (vis `querySelector`). Again an open question if this should force `tabIndex = -1`.

**Comment by zelliott** [comment]
I might call it `first-heading` instead of `first-header` (https://html.spec.whatwg.org/multipage/sections.html#the-h1,-h2,-h3,-h4,-h5,-and-h6-elements) (wouldn't want it to be confused with `<header>`).

I'll throw a vote in for forcing the element to be focusable. I feel like forgetting to add `tabindex` will otherwise be a super common gotcha and result in bug reports that these values aren't working as expected.

The logic could be something like:

1. If `tabindex` is specified, do nothing.
1. Else, set `tabindex` to -1, and add self-removing event listeners to remove the `tabindex` once the element is blurred or mousedown-ed. You don't want to keep the element focusable because it will mess with a user setting the sequential focus starting point via "click to move focus" (https://googlechrome.github.io/samples/focus-navigation-start-point/).

The logic to "force-focus" an element and revert it back to normal afterward could be pulled out into a common helper function.
