### ISSUE TITLE
@angular/google-maps version isn't updated when running ng update

### ISSUE THREAD

**Issue by Heatmanofurioso** [angular/components#22689]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [x] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [x] version
- [ ] doc

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....

No

### Description

 A clear and concise description of the problem...

When running `ng update` on an Angular project that has the dependency `@angular/google-maps` present, ng will not prompt, or update the google maps dependency.

`ng version` also doesn't seem to list `@angular/google-maps` in the list of Angular dependencies, but does show it in the list of packages.

## 🔬 Minimal Reproduction

1- Create a new Angular project with an outdated dependency version, and add an outdated version of `@angular/google-maps` to the project.
1- Or add an outdated version of `@angular/google-maps` to an existing project.

2- Run `ng update` and validate that there is no prompt indicating that `@angular/google-maps` has an available updated version.

## 🔥 Exception or Error

No exception is thrown

## 🌍 Your Environment

<pre><code>

Angular CLI: 12.0.0
Node: 15.10.0
Package Manager: npm 7.12.1
OS: win32 x64

Angular: 12.0.0
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, localize, material, platform-browser
... platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1102.12
@angular-devkit/build-angular   12.0.0
@angular-devkit/core            11.2.12
@angular-devkit/schematics      12.0.0
@angular/google-maps            11.2.12
@schematics/angular             12.0.0
rxjs                            7.0.1
typescript                      4.2.4
</code>
</pre>

**Anything else relevant?**

I've noted this issue since a few versions back. Unsure when it started, or if it is intended.

**Comment by Heatmanofurioso** [comment]
The issue also seems to persist with several `@angular-eslint` packages.
Should I add it to this issue, and change the title/description a bit, or should I open it as a separate issue?

It is effectively the same "bug"

**Comment by devversion** [comment]
@Heatmanofurioso It seems like this would fit more into a separate issue. I think one thing to acknowledge though is that `ng update` seems to only update packages which provide migrations. correct me if I'm wrong @alan-agius4.

I think there are two questions: 

1. Do we want to update packages like `@angular/google-maps` if someone runs `ng update @angular/material`. Those packages are not coupled together IMO (even though they all live under the `@angular` NPM scope).
2. Do we actually provide update migrations for packages like `google-maps` or the `youtube-player`.

I think for both the questions the answer is "No" currently, we could add the `ng-update` and `packageGroup` field to the `package.json` of the e.g. `@angular/google-maps` package so that `ng update` can update the package versions. There aren't any breaking changes planned AFAIK so that would be acceptable. If there will be breaking changes in the future though; we would need to consider adding migration code.

**Comment by alan-agius4** [comment]
>  @Heatmanofurioso It seems like this would fit more into a separate issue. I think one thing to acknowledge though is that ng update seems to only update packages which provide migrations. correct me if I'm wrong @alan-agius4.

Correct.
