### ISSUE TITLE
bug(cdk/overlay): Overlay has no border in high contrast mode, making it blend in with the background content

### ISSUE THREAD

**Issue by zelliott** [angular/components#22739]
#### Reproduction

Steps to reproduce:
1. Turn on Windows High Contrast mode.
1. Open any (?) Angular Material component that uses `CdkOverlay` under-the-hood.
1. Observe that the overlay has no border, making it blend in with the background content.

Examples:

![datepicker](https://user-images.githubusercontent.com/4220717/118986121-eae0be00-b933-11eb-90bb-fbb34ea653ee.PNG)

![menu](https://user-images.githubusercontent.com/4220717/118986189-f8964380-b933-11eb-8579-5731acdc831a.PNG)

Does it make sense to add a 1px transparent border or outline to `CdkOverlay`'s styles, so that all components get the fix for free?

#### Expected Behavior

I'd expect to see a 1px border around the overlay.

#### Actual Behavior

There is no border around the overlay.

#### Environment

- Angular: Latest
- CDK/Material: Latest
- Browser(s): Any browser compatible with Windows HC
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

**Comment by crisbeto** [comment]
Did you try refreshing after enabling high contrast mode? Here's what those two components look like for me:
![Datepicker__Angular_Material_-_Google_Chrome_2021-05-20_20-18-47](https://user-images.githubusercontent.com/4450522/119029251-afcca200-b9a8-11eb-9801-49ff4162ca78.png)
![Menu__Angular_Material_-_Google_Chrome_2021-05-20_20-18-59](https://user-images.githubusercontent.com/4450522/119029257-b22efc00-b9a8-11eb-954d-77e0ab07312b.png)

**Comment by zelliott** [comment]
Interesting, you're right that after refreshing the outline appears. This appears to be known then, due to https://github.com/angular/components/pull/22561? This came up in a11y testing for our app, I'm not sure yet if refreshing the page is a reasonable work-around (I think it is, but I'll need to double-check).

**Comment by zelliott** [comment]
I did some more digging, and it seems like the outline is added for specific Angular Material components (e.g. https://github.com/angular/components/blob/284bdaab5c4d01c89a3b27aa394806d9633f10ba/src/material/datepicker/calendar-body.scss#L198) but not directly on the overlay. It might make sense to add it directly on the overlay? That way, custom components that use the overlay get the outline for free?

**Comment by crisbeto** [comment]
The reason it needs a refresh is that the `HighContrastModeDetector` only runs the logic that applies the high contrast classes once. We try to reduce the calls as much as possible, because they have performance implications. I think that this isn't a problem, because real users are unlikely to be switching to and from high contrast mode in a single session.

As for the outline, we could apply it at the `cdk/overlay` level, but we've tried to keep the CDK very unopinionated so we can't assume what sort of overlay will be projected. E.g. there's nothing stopping a user from having two root overlay nodes.

**Comment by zelliott** [comment]
> We try to reduce the calls as much as possible, because they have performance implications.

Yeah this makes sense, I gleaned this from the PR itself.

> but we've tried to keep the CDK very unopinionated so we can't assume what sort of overlay will be projected

I think as a general principle this makes sense as well. I noticed the overlay is already _slightly_ opinionated w.r.t styles and high contrast behavior. For example, the overlay applies a default backdrop color + animation and overrides the backdrop opacity in the case of HC. I'm assuming this is done because in the _vast_ majority of cases - overlays should have backdrops. Each component that uses an overlay shouldn't have to worry about styling the overlay's backdrop. I'm wondering if we can apply the same logic to overlay HC outlines.

**Comment by crisbeto** [comment]
I think that it's easier to make assumptions about the backdrop, because they are provided with the CDK as well, whereas the overlay is completely unstyled. I agree with your that having this built into the overlay would help us cover more cases, but don't know if it won't be too aggressive. E.g. if an overlay already has a `border`, it won't need the `outline`.

**Comment by zelliott** [comment]
> E.g. if an overlay already has a `border`, it won't need the `outline`.

That's a good point. I'm going to close this out then. If anyone else has any additional thoughts feel free to re-open. Thanks @crisbeto!
