### ISSUE TITLE
help(Datepicker): How to insert a component or element into the date picker popup with Renderer2?

### ISSUE THREAD

**Issue by omaracrystal** [angular/components#22735]
#### What are you trying to do?

I would like to insert a component or element before the calendar within the Datepicker popup

#### What troubleshooting steps have you tried?

Currently, I am able to accomplish this with direct DOM manipulation. I would like to know the recommended way to do this. I have tried with Renderer2, however, it fails with a console error. Is there an input that Datepicker provides where we can insert html?

I asked this question on stackoverflow here --> https://stackoverflow.com/questions/67613075/how-to-use-renderer2-to-move-a-component-or-element-into-angular-material-datepi

Here you can find the code I put together =

https://stackblitz.com/edit/angular-hdrguh-frwr45?file=src/app/date-range-picker-selection-strategy-example.html

If you uncomment // this._moveShortcutsListWithDocument(); you will find this console error:

![Screen Shot 2021-05-19 at 8 01 43 PM](https://user-images.githubusercontent.com/11908147/118909472-4b461000-b8e0-11eb-84f0-ca56bdc4b210.png)

This is what I am trying to accomplish
![Screen Shot 2021-05-19 at 8 12 50 PM](https://user-images.githubusercontent.com/11908147/118909487-5305b480-b8e0-11eb-9cfb-4f27a970c3fb.png)

#### Environment

- Angular: 10.2.1
- CDK/Material: 10.2.4
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): macOS

**Comment by crisbeto** [comment]
I suspect that the problem comes from your usage of `Renderer2.selectRootElement` which both finds the passed-in element and clears its contents. Your working solution (`_moveShortcutsListWithDocument`) is the correct way of doing this. In general, you don't really need to use `Renderer2` anymore. It was introduced in the early days of Angular, because the APIs for server-side rendering weren't compatible with the DOM, but since Angular version 5 they are identical.

The only thing you may need to do to make `_moveShortcutsListWithDocument` compatible with server-side rendering is to get a reference to `document` using `constructor(@Inject(DOCUMENT) private _document)`, instead of referring to the global variable.

**Comment by omaracrystal** [comment]
Okay great so ``constructor(@Inject(DOCUMENT) private _document)`` will work with server-side rendering, great to hear!
