### ISSUE TITLE
Can't override "get-color-from-palette" function becuase of scss module systems

### ISSUE THREAD

**Issue by sandeeppatidar30** [angular/components#22822]
#### Reproduction

Use StackBlitz to reproduce your issue: 
- Components: https://stackblitz.com/fork/components-issue
- Harnesses: https://stackblitz.com/fork/harness-issue

Steps to reproduce:
1. Override get-color-from-palette function with your own defination
2. Check for any mat component like button, it takes color value from mat "get-color-from-palette" not from overriden "get-color-from-palette" function
 
 
#### Expected Behavior

What behavior were you expecting to see?
We have implemented css var in our application and to achieve that we override the "mat-color" function, so that returns the color in "var()" form, but after updating to v12 it is not working because of scss module system, now instead of "mat-color" we have to override "get-color-from-palette" but this function call is scoped to component only, so we are not getting the color in var() form. 

Is there any way to override the "get-color-from-palette" ?

#### Actual Behavior

What behavior did you actually see?
It does not override the `get-color-from-palette` function

#### Environment

- Angular: 12.0.1
- CDK/Material: 12.0.1
- Browser(s): chrome v90.0.4430.212
- Operating System (e.g. Windows, macOS, Ubuntu):  Windows10

**Comment by jelbourn** [comment]
This is something that only worked because of the extremely lax behavior of Sass in the past; Sass put every symbol in the global namespace, so if you defined something with the same name it clobbered it. It was never an intended behavior. 

With IE11 support being dropped in Angular v13, we're looking at switching our theming system to be based on CSS variables, but we don't have something explicitly supported today.
