### ISSUE TITLE
Angular Material Source Code doesn't follow best practices/the Angular Style Guide

### ISSUE THREAD

**Issue by mfish0005** [angular/components#22858]
#### Feature Description

I would like to see Material's source code follow the [Angular style guide](https://angular.io/guide/styleguide) or another well established design pattern.  Or at the least make note in the documentation of why decisions were made to stray from the style guide/best practices.

#### Use Case

Developers are using this project's source code as a guideline on how to structure their projects.  As an architect I've worked on several projects and libraries that implement Angular Material and most of them had major architectural problems.  I think the architecture of Angular Material plays a part in that because the library itself doesn't follow best practices or the [Angular style guide](https://angular.io/guide/styleguide).  I've had multiple developers from different projects point to Material's source code as a reason for why they made a design decision.

#### Example 1: Angular Material doesn't follow the style guide's naming conventions(or any established naming convention). 

The style guide states [here](https://angular.io/guide/styleguide#naming): "Do follow a pattern that describes the symbol's feature then its type. The recommended pattern is feature.type.ts."

Angular Material names files like this instead: "feature.ts".  Inside [src/material/autocomplete](https://github.com/angular/components/tree/master/src/material/autocomplete) you can see files like autocomplete.html which should be autocomplete.component.html.  There is also autocomplete-module.ts which should be autocomplete.module.ts

#### Example 2: Angular Material doesn't follow the SRP(Single Responsibility Principle)
The style guide states we should follow the SRP [here](https://angular.io/guide/styleguide#single-responsibility): "Do define one thing, such as a service or component, per file."
Angular Material doesn't follow this guideline.  For example if we look at [autocomplete.ts](https://github.com/angular/components/blob/master/src/material/autocomplete/autocomplete.ts) we see that it defines multiple classes, interfaces, a directive, and a component all in the same file.  This sets a really bad example for developers.  Structuring a larger project like this makes it extremely difficult to maintain and opens the door to circular dependencies

#### Conclusion
I'm sure there are more examples but these are most prominent(especially number two).  I know architecture is often overlooked on the front end but if we all tried a little bit harder I think it would make everyone's lives easier.  Thanks :)

**Comment by jelbourn** [comment]
To be honest, I disagree with the file naming guidance in the style guide and have been advocating for changing it for years. We do not use this convention inside Google (or even in Angular itself). In particular, that guidance may make sense for an _application_, but it is super redundant for a component library. `autocomplete-trigger.ts` is perfectly understandable, while `autocomplete-trigger.directive.ts` provides no additional value. Ultimately, a style guide is a recommendation, but projects can also decide to do something different that's more tailored to their use-case.

As for the large files- sometimes this is unfortunately necessary to avoid circular dependencies. 

Closing this since we don't intend on making any changes here.

**Comment by mfish0005** [comment]
I can't say I'm surprised it was closed.  Usually codebases like this are a direct reflection of workplace culture. 

I'm confused by your answer to the second example. Defining everything in one file *creates* the risk of circular dependencies.  Defining them separately and using a barrel file to export them achieves the same result without the plethora of problems the current approach creates.

**Comment by jelbourn** [comment]
We have to be pretty aggressive about closing issues to have even some semblance of keeping on top of the backlog. Commenting is still welcome after closing. Closing this is a reflection that I don't realistically see us changing file naming schemes at this point in the project, or doing a major refactoring of the existing components. It's more likely that we'll change the style guide with more nuanced guidance for application vs. library. 

The circular dependency issue is related to Angular's DI and Query system. There are cases where we can avoid adding things in the same file by introducing tokens and interfaces, but we chose not to do so because this added a level of indirection in the code that makes things harder to maintain that just having a handful of big files.

**Comment by mfish0005** [comment]
@jelbourn Ah ok makes sense there are tons of issues in here.  Also understandable because I didn't expect the library to be changed at this point.  Changing the documentation to fit Material also seems risky considering there are many other projects and libraries following the style guide already.

It's actually libraries where I've seen example #2 most often.  Not all libraries are as simple as Material.  I've worked on a couple that housed 100+ components specifically tailored to business use cases that were used for internal projects. They became extremely difficult to maintain and showcased some of the other problems highlighted in the style guide.

Just my two cents.  I apologize if I was a bit short this morning I was up late refactoring a library that followed this pattern haha.
