### ISSUE TITLE
bug(mat-datepicker): DatePicker incorrectly displays dates inputted as ISO 8601

### ISSUE THREAD

**Issue by holdenrohrer** [angular/components#23045]
#### Reproduction

Use StackBlitz to reproduce your issue: 
- https://stackblitz.com/edit/components-issue-qvykwk?file=src%2Fapp%2Fexample-component.html

Steps to reproduce:
1. Manually input 2020-01-01 (in en_US locale)
 
 
#### Expected Behavior

What behavior were you expecting to see?

I expected that the component would display 01/01/2021 after modifying it to a localized date.

#### Actual Behavior

What behavior did you actually see?

The component displays 12/31/2019.

#### Environment

- Angular: 10 (tested)
- CDK/Material: 10
- Browsers: Firefox 89, Chromium 91 (tested)
- Operating System: Arch Linux 2020-06-21

**Comment by holdenrohrer** [comment]
This is an issue with time zones, I think. 2020-01-01 is interpreted as GMT/UTC whereas 01/01/2021 is interpreted as local time. Not sure if this is an issue with js Date and whether it could be fixed or not.

**Comment by crisbeto** [comment]
By default the datepicker uses the built-in `Date` object in order to avoid bringing in dependencies. You can try using the Moment.js date adapter or write your own. There's more information in the docs https://material.angular.io/components/datepicker/overview#choosing-a-date-implementation-and-date-format-settings.
