### ISSUE TITLE
bug(cdk/scrolling): table inner component is not recreate on new reference, but only updated

### ISSUE THREAD

**Issue by KrakenTyio** [angular/components#23080]
Have issue where i create example
https://stackblitz.com/edit/angular-oaewqc?devtoolsheight=33&file=src/app/app.component.ts

when you click on any row its generate new lines (with new ref lines and also new ref array), always new trackBy id, but on create new array ref and new object inner, its call on inner component `[row-component]` only `ngOnChanges`
When you replace `*cdkVirtualFor` by regular `*ngFor` its call expectable.
Also is ok when you have `templateCacheSize` on zero, but its not sollution for big list.

Its expected or exist any workaround? bc. i try few older version but its happen on any of older scrolling versions.

Issue start rasing in our application, bc we have in every row inputs for editing, but after change first line, we regenerate whole array, and focus jump to latest row. 
It bc. last line has on no reason same refenrece as previous 1 row in previous array.

**Comment by mmalerba** [comment]
If I understand correctly, are you talking about the fact that it does not create new views wen you click? This is actually intentional. The purpose of `templateCacheSize` is to allow it to save some of the already created templates for reuse later. For some components, reusing them may not work, in which case you can set the `templateCacheSize` to 0.
