### ISSUE TITLE
Datepicker shows one day behind in Angular 12

### ISSUE THREAD

**Issue by PierreKoung** [angular/components#23132]
When I select a date in datepicker it selects the date fine. But when I click the save button. the selected time shows a behind date. I'm working on Angular 12. How do I solve this issue?

i am converting the date in UTC but even with that I can't be able to get the right date in the picker

**Comment by jelbourn** [comment]
This issue doesn't have enough information for the team to investigate. Please include:
* A reproduction of the issue (preferably via StackBlitz)
* Any relevant errors and stack traces
* Any relevant details about your build environment

(this is a canned response)



In addition to the canned response, this is almost certainly an i18n issue due to using the NativeDateAdapter, see https://material.angular.io/components/datepicker/overview#internationalization

**Comment by PierreKoung** [comment]
Hey @jelbourn Here is a short video of how it is doing 

https://user-images.githubusercontent.com/44596656/125050385-339a3500-e0a2-11eb-9b0e-46f8fa476558.mp4

About errors, there are no errors on the component everything looks nice but this problem still persist.

> About my build environment : 
**OS**: Windows 10
**Angular Version**: 12
