### ISSUE TITLE
Input elements are leaking as Detached DOM nodes

### ISSUE THREAD

**Issue by rajibhasan11** [angular/components#23229]
In my application I am using some material form fields with input element when I navigate to next route and I observe taking heap snapshot I see left over DOM nodes as detached DOM nodes from the first route. If I do the same navigating back and forth between these two routes the leaked nodes are increasing.

**I did the same steps with https://material.angular.io/components/input/overview and the result is the same.**
![dom-nodes-leakage](https://user-images.githubusercontent.com/5672879/126739649-6acb6ae3-ec47-4464-90de-883d94a5df1b.png)

Browser: Google Chrome - Version 92.0.4515.107 (Official Build) (64-bit)

**Comment by crisbeto** [comment]
I tried this out against our local development app and the inputs seemed to be cleaned up as expected. Checking this against material.angular.io can be misleading, because we have to create a bunch of `input` element in memory and keep them around in order to facilitate the "Open in Stackblitz" functionality. See https://github.com/angular/material.angular.io/blob/master/src/app/shared/stack-blitz/stack-blitz-writer.ts#L131.

Also could this be related to https://github.com/angular/angular/issues/41047?

**Comment by rajibhasan11** [comment]
@crisbeto `input` elements are leaking when you keep focus on it once, if you never focus on it is not leaking as detached DOM nodes.

**Comment by crisbeto** [comment]
ok, this sounds like https://github.com/angular/angular/issues/41047. I'll close this issue since we can't do much about it on our end.
