### ISSUE TITLE
bug(cdkTextareaAutosize): Resize in firefox seems to mess up scroll position

### ISSUE THREAD

**Issue by felhag** [angular/components#23233]
#### Reproduction
1. open with firefox: https://stackblitz.com/edit/angular-fymbfd?file=src/app/form-field-overview-example.css
2. scroll to bottom
3. type something on the first line of the textarea
  
#### Expected Behavior
The scroll position shouldn't change.

#### Actual Behavior
When the textarea is at the bottom of the page scroll position changes.

#### Environment
- Angular: 12.1.3
- CDK/Material: 12.1.1
- Browser(s): Firefox
- Operating System: Windows 

Seems like it is caused by #16629. When removing the height: 0 the issue is gone (but the autosizing doesn't work anymore of course). 

#### Related
#8992
#16629

**Comment by felhag** [comment]
I think the issue could be resolved by saving the height of the parent element of the textarea. Something like this (pseudo code): 
```
  private _measureScrollHeight(): number {
    if (isFirefox) {
      // save current height to parent so it wont shrink
      parent.style.height = parent.clientHeight;
    }

    // calculate scroll height

    if (isFirefox) {
      // reset parent height
      parent.style.height = '';
    }
    return scrollHeight;
  }
```

It's kind of hacky solution for quite a minor issue, so I understand if you don't want to pollute your code with this crap. Let me know what you think. I'm happy to create a pull request for it if you think this solution fits.

**Comment by crisbeto** [comment]
I can reproduce it from the provided Stackblitz, but I wasn't able to reproduce against our dev app. I'm wondering if it depends on which element is scrollable.

**Comment by felhag** [comment]
It's only possible to reproduce when the textarea is at the bottom of the page. I was able to reproduce it there as well when I moved the textarea to the bottom.

**Comment by crisbeto** [comment]
Ah, I see. It's because the page becomes shorter for a split second.

**Comment by felhag** [comment]
Correct. Not sure why it's only an issue in Firefox though. I changed the code so it will always use the `cdk-textarea-autosize-measuring-firefox` class but still couldn't reproduce the issue in a Chromium browser. 

Also I don't really know what the best way is to fix it. Preserving the height of the parent element seems to work fine when the textarea is inside a mat-form-field but not necessarily for a regular textarea (when the parent element is `display: inline` for example).

**Comment by crisbeto** [comment]
I spent some time investigating it and I found 3 possible solutions, but none of them are perfect:
1. Saving the scroll position before measuring starts and then restoring it afterwards. The problem with it is that we can't know which parent element is scrollable. E.g. it could be the window, but it could also be a random element with `overflow: auto`.
2. Calling `scrollIntoView` on the `textarea` after measuring is done. The problem here is that it may not end up on the exact same scroll position before measuring started. E.g. if I have the page scrolled just above the bottom, the browser ends up shifting it a little bit.
3. Creating a temporary `div` with the same height as the `textarea` and adding it to the DOM so the page doesn't change size. It works, but it feels excessive, especially when you consider that this will be called once per key press.

**Comment by felhag** [comment]
At first I thought option 2 would be the best solution, but I think this could cause undesired behavior when the textarea is changed programmatically instead of user input. 

Option 1 and 3 would both be work I guess. For the first option it should be possible to traverse upwards and find the first scrollable element. But this would also become a little excessive as you mentioned for option 3..
