### ISSUE TITLE
bug(tabs): ink-bar on not aligned on label initially

### ISSUE THREAD

**Issue by AmitMY** [angular/components#23241]
#### Reproduction

Use StackBlitz to reproduce your issue: 
- Components: https://stackblitz.com/edit/components-issue-j5sn8l?file=src/app/example-component.html

Failed to reproduce in StackBlitz.

Steps to reproduce:
1. Clone https://github.com/sign-language-processing/playground
2. Open the `/translate` router page (Online it is https://sign-language-processing.github.io/playground/translate)
3. Look at the spoken language selector
 
 
#### Expected Behavior

I expect the selected tab to be perfect with the ink (this is after clicking the tab)
![image](https://user-images.githubusercontent.com/5757359/126879000-74c31c43-d5bd-43d6-a022-06657a040c77.png)

#### Actual Behavior

This is how it actually is (before clicking the tab)
![image](https://user-images.githubusercontent.com/5757359/126878988-4e2bb62b-a233-4ffa-bbe6-046f377d52a3.png)

#### Environment

- Angular:
- CDK/Material: tried 11.2.12, tried 12.1.3
- Browser(s): Chrome, iOS Safari
- Operating System (e.g. Windows, macOS, Ubuntu): Windows, iOS

**Comment by AugustZellmer** [comment]
This could be confirmation bias, but is your issue the same issue as my issue?
<https://github.com/angular/components/issues/23244>

My hypothesis is that, in both our cases, the width of the various components is being calculated based on the browser's default font before our custom fonts are being downloaded. But if the custom font is already in the browser's cache, the issue will not manifest.

**Comment by AmitMY** [comment]
Your hunch is right!
If I set the mat-label font to be Arial or Tahoma, which I have installed, It works perfectly.

**Comment by crisbeto** [comment]
The linked Stackblitz worked for me, but based on the discussion, it sounds like something that has come up in the past. In order to measure where to put the ink bar, we may end up triggering a reflow which can be expensive. That's why we try to do it only when we're sure that the content has changed (e.g. the number of tabs changed or the page was resized). I'll close the issue since we can't do much about it without sacrificing performance, but there are a couple of things you can do on your end:
1. There's a method called `realignInkBar` on `MatTabGroup` which you can use to tell the ink bar to re-align.
2. We have a new implementation of tabs coming up in `material-experimental/mdc-tabs` which uses a different way of positioning the ink bar which avoids this problem completely. You can try to switch to it. The public API and behavior are exactly the same (they extend off the same base classes as the current tabs), but the CSS is a little bit different. To use it, you have to change your import for `MatTabsModule` from `@angular/material/tabs` to `@angular/material-experimental/mdc-tabs`.

**Comment by AmitMY** [comment]
Thanks
Except for not respecting the forground text color in dark mode, it worked well
https://github.com/sign-language-processing/playground/commit/06dde3721d792fb693dcdbc8c362a55b80a945a5

**Comment by crisbeto** [comment]
Ah, I forgot to mention that the new tabs implementation also has a separate theme mixin that you have to import from `material-experimental`. There's more info here: https://github.com/angular/components/blob/master/src/material-experimental/mdc-tabs/README.md

**Comment by shammy8** [comment]
@AmitMY just wondering how did you get that arrow down button next to your tabs? And what does the button do?
