### ISSUE TITLE
docs-bug(mat-form-field): `required` does not work in the custom form field control guide

### ISSUE THREAD

**Issue by AlexElin** [angular/components#23352]
#### Documentation Feedback

I need to lock a Submit button when a custom form-field control is empty.
I slightly changed the [source Stackblitz example](https://run.stackblitz.com/api/angular/v1?file=src%2Fapp%2Fform-field-custom-control-example.ts) by adding a Submit button (s/b disabled when a form is invalid) and a Name control + setting `Validators.required` in the form model.

**Current behavior**: When filling only Name (the Phone number is empty) the form transits to valid state and the button is enabled.
![image](https://user-images.githubusercontent.com/13061803/129194566-8948ee54-e4ae-4871-b061-55063f9cb2cc.png)

**Expected behavior**: the button must be disabled because the Phone number is empty.

My Stackblitz: https://stackblitz.com/edit/angular-mdsmxs?file=src%2Fapp%2Fform-field-custom-control-example.html

**Affected documentation page:** https://material.angular.io/guide/creating-a-custom-form-field-control
https://run.stackblitz.com/api/angular/v1?file=src%2Fapp%2Fform-field-custom-control-example.ts

**Comment by AlexElin** [comment]
If I fill and then clear the phone number field, the validation works.

![enter_and_clear](https://user-images.githubusercontent.com/13061803/130314922-b53e8d23-244f-4145-93fe-0e0e678eddab.gif)

**Comment by Captainnik53** [comment]
Hey, there. @AlexElin 

The problem here is not related to **required**.

The MatFormFieldControl in the above example returns value only if the **parts** formGroup is valid, otherwise returns null value. But on the other hand, initial value of **tel** formControl is not null which bypasses the required validator and hence it remains valid unless changed.

`get value(): MyTel | null {
    if (this.parts.valid) {
      const {
        value: { area, exchange, subscriber },
      } = this.parts;
      return new MyTel(area, exchange, subscriber);
    }
    return null;
  }`


Solution - Make initial value of **tel** formControl null, which makes it invalid from the start itself.

Here, is a working stackblitz - https://stackblitz.com/edit/angular-mdsmxs-rgjbrh?file=src%2Fapp%2Fform-field-custom-control-example.ts

Hope this solves your problem. Also, have raised a PR for correcting the documentation.
