### ISSUE TITLE
bug(datepicker): error when starting typing the value zero, example 01/08/2021

### ISSUE THREAD

**Issue by GlauberF** [angular/components#23478]
#### Reproduction
When trying to type the date, starting with 0, returns an error, but I haven't finished typing the value.
example date in brazil DD/MM/YYYY, so if I want to type day first, I would type 01.
However, doing this gives an error, after having previously typed other values in the field and erased it.
Also, after I type 01/08/2021, it transforms to 1/8/2021, like keeping the default 01/08/2021.
 
 
#### Expected Behavior
![vokoscreen-2021-08-27_15-25-09](https://user-images.githubusercontent.com/11314585/131172551-f549b262-0c3c-4c6f-915d-390e2a70726a.gif)

in the gif, you can see that typing 0 gives an error and typing a second value after zero, it suggested a date, but didn't let me type what I really wanted

error that appears to me is
`matDatepickerParse { text: "0" }`

#### Environment
```
Angular CLI: 12.2.2
Node: 14.16.1
Package Manager: npm 6.14.12
OS: linux x64

Angular: 12.2.2
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, language-service, material, material-moment-adapter
... platform-browser, platform-browser-dynamic, platform-server
... router, service-worker

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.1202.2
@angular-devkit/build-angular     12.2.2
@angular-devkit/build-optimizer   0.1101.4
@angular-devkit/core              12.2.2
@angular-devkit/schematics        12.2.2
@angular/flex-layout              12.0.0-beta.34
@nguniversal/builders             12.1.0
@nguniversal/express-engine       12.1.0
@schematics/angular               12.2.2
rxjs                              6.6.7
typescript                        4.3.5
```

**Comment by crisbeto** [comment]
What happens is that by default Material shows errors when the control is invalid, and it is `touched` or the parent form has been submitted (see https://github.com/angular/components/blob/master/src/material/core/error/error-options.ts#L24). The first time you type something and click away the control becomes `touched` which means that errors will be displayed for all subsequent key presses. You can customize it by providing your own `ErrorStateMatcher`. See https://material.angular.io/components/input/overview#changing-when-error-messages-are-shown.

Closing since it works as expected.

**Comment by Andrashynets** [comment]
https://github.com/angular/components/issues/23478
