### ISSUE TITLE
help(mat-icon): How to register and sanitize svg icons globally for use by lazy-loaded components?

### ISSUE THREAD

**Issue by memee** [angular/components#23536]
#### What are you trying to do?

What are you trying to do?

I'm trying to use custom svg icons in lazy loaded components.
Icons are registered inside root `app.component.ts`. They work in `app.component.html` but not inside lazy loaded component. I get an error: 
```
Error: Error retrieving icon :camera! Unable to find icon with the name ":camera"
```

#### Reproduction

Steps to reproduce:
1. Register custom icon in `app.component.ts` like: ```this.matIconRegistry.addSvgIcon(
      "camera",
      this.domSanitizer.bypassSecurityTrustResourceUrl(
        "../assets/svg/camera.svg",
      ),
    );```
2. Use your custom icon in lazy loaded component like that: `<mat-icon svgIcon="camera"></mat-icon>`
  
#### Environment

- Angular: 12.2.3
- CDK/Material: 12.2.3
- Browser(s): Brave (version 1.29.77 Chromium: 93.0.4577.63 (official version) (x86_64))
- Operating System (e.g. Windows, macOS, Ubuntu): MacOS Big Sur

**Comment by crisbeto** [comment]
The `MatIconRegistry` is a regular `@Injectable` so you can provide it in the same way you would provide your other cross-module injectables (e.g. by having a common module). Closing since GitHub is meant primarily for bug reports, rather than help requests. StackOverflow or the Angular Discord would be better place to ask for help.
