### ISSUE TITLE
[mat-sort-header] customize aria-label via an input/api

### ISSUE THREAD

**Issue by Cabbageboy** [angular/components#23549]
Currently, there's no entry for a **mat-sort-header button** to have **customized aria-label**. 
The default one falls to the id (e.g. id), which doesn't make sense to users when announced. 

We hope to make it announce with customized aria-label like '**users sorted by ${id} in direction ${direction}**'.

**Comment by jelbourn** [comment]
@andrewseguin or @crisbeto do you remember why the setting to customize the button's label was removed from the intl class?

**Comment by crisbeto** [comment]
I think that we deprecated it, because it wasn't necessary anymore after we started adding `aria-sort` to the headers. It was done in https://github.com/angular/components/pull/13297.

**Comment by Cabbageboy** [comment]
While the problem is the screenreader would get really confused about the button itself, since it can only announce the header name.

**Comment by jelbourn** [comment]
I'm reasonably certain that the button should still have a label that contains the word "Sort", e.g. "Sort by name". Just having the button with the column header text doesn't sufficiently convey the action that will occur via assistive technology.  Based on the spec, having `aria-sort="none"` is supposed to communicate that a column is currently unsorted but sortable, but [none of the screen-readers support this](https://a11ysupport.io/tech/aria/aria-sort_attribute). I tried myself in VoiceOver, ChromeVox, and NVDA, and all three communicate that it's a button, but not what it does (NVDA even just says "Clickable").

Going even further, we should probably add additional text for ascending and descending because VoiceOver announces "sort up" and "sort down", which is objectively terrible (but maybe a lower priority issue since it at least announces _something_).

**Comment by crisbeto** [comment]
It's worth noting that the main reason we did #13297 was because the `aria-label` also caused screen readers to read out the header label while navigating the cells.

**Comment by jelbourn** [comment]
@Cabbageboy I did some investigation here and it looks like we probably don't want to let people change the _label_ for the button, but there is an issue that it doesn't convey its action. However, adding a description with `aria-describedby` ([hacky prototype](https://github.com/jelbourn/components/commit/5fd03c965fb77938dc6c6aa05554af7e8ed38aaa)) seems to get the job done.

**Comment by jelbourn** [comment]
Resolved by #23633
