### ISSUE TITLE
bug(MatDatepicker): Updating FormControl value with `emitEvent: false` still trigger valueChanges

### ISSUE THREAD

**Issue by csvn** [angular/components#23551]
#### Reproduction

Use StackBlitz to reproduce your issue: https://stackblitz.com/edit/angular-ivy-ad4d4j?file=src/app/app.component.ts

Steps to reproduce:
1. Use `<mat-date-range-input>` to create a date range picker
2. Wait until the view has rendered
3. Update the value of start or end date for the `FormControl` when using `{ emitEvent: false }`
4. `FormGroup.valueChanges` will be triggered even though it should not 
 
```ts
// Using this code after the view has initialized should not emit a new value for `FormControl.valueChanges`
this.form.controls.start.setValue(new Date(), { emitEvent: false });
```
 
#### Expected Behavior

No value emitted on `FormControl.valueChanges`

#### Actual Behavior

A new value emitted on `FormControl.valueChanges`

#### Environment

- Angular: 12.2.5
- CDK/Material: 12.2.4
- Browser(s): Chrome v95
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

**Comment by csvn** [comment]
https://github.com/angular/components/issues/9295 seems slightly related to this, but not fully. As far as I could see, it seems likely that both issues are caused by re-running validation that triggers emission of new values.

**Comment by crisbeto** [comment]
I believe that this is the same root cause as #21875. The tl;dr is that the built-in start/end date validators require the opposite input to be change detected which means that have to trigger some changes manually, causing events to be emitted. I've added a topic for our next team meeting to discuss potentially removing these validators, because they've been a source for a lot of bugs.
