### ISSUE TITLE
docs-bug(COMPONENT): Documentation around pre-built themes is useless and always has been

### ISSUE THREAD

**Issue by Neutrino-Sunset** [angular/components#23647]
#### Documentation Feedback

The documentation [here](https://material.angular.io/guide/theming#using-a-pre-built-theme) and [here](https://material.angular.io/guide/theming-your-components) gives the impression that pre-built themes are a useful way to get started with Angular Material.

However the reality seems to be that the pre-built themes are utterly useless since they are distributed as css only and therefore provide no way to reference palette colours in any custom component you are attempting to theme, and the documentation on custom component theming uses variables like `$theme` which do not exist.

This issue has been raised many times over the years and I suspect many new users of Angular Material have wasted much time trying to work this out.

https://github.com/angular/components/issues/5152
https://github.com/angular/components/issues/8145
https://github.com/angular/components/issues/11804
https://github.com/angular/components/issues/13476

...and yet the documentation remains just as deficient as it has always been.

Please either provide a way to make the pre-built themes useful by providing the source so that the sass variables can be used to theme custom components, or update the documentation to highlight their severe limitations, or just remove them altogether.

**Comment by Nierusuki** [comment]
I'm a new user trying to understand the theming docs, but it's useless, not only it doesn't have any intellisense or autocomplete on VSCode, I didn't understand how to apply the prebuilt primary color to my custom footer using only the docs.

There are a lot of mat. scss functions that aren't documented, and since there isn't autocomplete on VSCode there is no way of learning the functions.
e.g: 
![image](https://user-images.githubusercontent.com/52475327/135565534-3384291e-6e6a-4c4b-a2b7-ac7913d69662.png)

**Comment by amysorto** [comment]
Closing this issue since the theming docs have been updated since this issue was created, and will be updated again soon with all the new theming updates coming in v19.
