### ISSUE TITLE
bug(google-maps): zoom, height and width are not synced with internal google maps properties

### ISSUE THREAD

**Issue by srnec** [angular/components#23824]
#### Reproduction

Steps to reproduce:
1. pass `zoom` value 17 to the google-maps via `[zoom]="zoom"`
2. interact with the map (zoom in/out using mouse)
3. pass again `zoom` value 17 in order to set the zoom level back as it was
 
#### Expected Behavior

Newly passed value (even though the same as the one passed at first) should set the zoom level in google-maps.

#### Actual Behavior

The newly passed value won't trigger `ngOnChanges()` thus `google.maps.Map.setZoom()` will not be called.
The problem is with the Angular check on `@Input` change where it uses `===` comparation. This means even though internal zoom value is different we cannot set it via `zoom` property because the new value equals to the same value as it was before.

My recommendation would be to sync values of the properties `zoom`, `height` and `width` on each particular change event (e.g. `zoomChanged`). This would mean in our case the `zoom`.
If this change will be applied then why to stop only here, we could already pass the actual zoom value via `zoomChanged` event to the consumers.

#### Environment

- Angular: 12
- @angular/google-maps: 11.2.13
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu):  Windows

**Comment by crisbeto** [comment]
Syncing the value internally isn't going to help, because as far as Angular's change detection is concerned, the value would still be 17. In order to fix it, we would somehow have to update the binding in the component that wraps the `google-map`, but we don't have access to do that. There are a couple of ways you can fix it on your end:
1. Sync the value yourself on the `zoomChanged` event.
2. Set the zoom programmatically by getting a hold of the `GoogleMap` component using `ViewChild` and calling `map.googleMap.setZoom(17)`.
