### ISSUE TITLE
Dense Theming

### ISSUE THREAD

**Issue by chhinsras** [angular/components#24020]
### Feature Description

Need for more compact theme

**Comment by wagnermaciel** [comment]
Needs more information

**Comment by chhinsras** [comment]
@wagnermaciel . I want more compact design for form, like input, select, button, list..l.

**Comment by wagnermaciel** [comment]
@chhinsras Creating a compact version of each component's styling would be a pretty massive undertaking. Also, we follow the design specs at https://material.io/design, so if you would like a new design for these components you will need to reach out to the material design team

**Comment by Totati** [comment]
Duplicate of https://github.com/angular/components/issues/4597

**Comment by chhinsras** [comment]
No update for 5 years old

**Comment by wagnermaciel** [comment]
Thanks @Totati! Yep, I'd assume #4597 has been sitting because other issues have been prioritized over adding this feature. I'll also add that this issue was created before the convergence of our components and the [Material Components Web](https://github.com/material-components/material-components-web/) components. If we want to implement this now, we'll need to get the Material Components Web team on board as well

**Comment by dirthsj** [comment]
Material Components Web [already supports density](https://github.com/material-components/material-components-web/tree/master/packages/mdc-density)

**Comment by wagnermaciel** [comment]
Ah, good to know @dirthsj . In that case, this feature may be implemented in the near future for the `mat-mdc-button` 👍🏽

**Comment by chhinsras** [comment]
any example how can I add to Angular Material Components

**Comment by Totati** [comment]
https://github.com/angular/components/tree/master/src/material-experimental/mdc-button
