### ISSUE TITLE
bug(CdkDragDrop): Drag placeholder is shown in the original place, while an index change is emitted on drag release

### ISSUE THREAD

**Issue by hodossy** [angular/components#24052]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

Drag and Drop placeholder is shown in the wrong place in some cases, and that causes confusion upon drag release.

I use DragListGroup and DragLists to support drag and drop in a wrapped flex environment.

### Reproduction

Steps to reproduce:
1.  Drag a chip (eg fourth) at the leftmost side of the text
2.  Move a bit forward, still dragging, until previous chip hover effect is shown. The chip placeholder should be in its original place (bit hard to find the sweet spot)
2.  Release the drag

Stackblitz: https://stackblitz.com/edit/components-issue-cdmhsa?file=src/app/example-component.ts

### Expected Behavior

expecting the dragged chip to be in its original place, ie event emitted with the same previous and current container.

### Actual Behavior

the dragged chip moves, event emitted with the `n` previous and `n-1` current container.

### Environment

- Angular: 12.2.9
- CDK/Material: 12.2.9
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

**Comment by crisbeto** [comment]
I think the problem here is that you're defining a drop list around each chip in order for the list to wrap. This breaks down at some point, because chips won't move over into the next list as you're dragging. We don't currently support mixed orientation drag and drop, but it's on our roadmap. See https://github.com/angular/components/issues/13372.
