### ISSUE TITLE
bug(COMPONENT): mat-grid-list does not show mat-grid-tile inside component

### ISSUE THREAD

**Issue by jayddaniels** [angular/components#24313]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

"mat-grid-list" list only shows "mat-grid-tile" if it is directly inisde it. It does not show it, if it is put into a child components html file.
This is inconsistent to how for example the "mat-nav-list" and "mat-list-item" works, which does show the "mat-list-item" even if it is put into a child component.

### Reproduction

Steps to reproduce:
1. https://stackblitz.com/edit/components-issue-21e7dn?file=src/app/example-component.html
2. see example component html and child component html

### Expected Behavior

Do show the "mat-grid-tile", even if the tile element is put inside a child component.

### Actual Behavior

Shows the "mat-grid-tile" only if directly inside the "mat-grid-list" element

### Environment

- Angular:12.2.9,  13.0.0 and other versions aswell
- CDK/Material:13.1.3
- Browser(s): Chrome
- Operating System Windows

**Comment by crisbeto** [comment]
This is more of a side-effect of how Angular queries and content projection works, rather than an issue with the grid list setup. The `ContentChildren` inside the grid list is only going to pick up tiles that are defined directly within the template, it isn't going to traverse down the component tree. Closing the issue since we can't do much about it.
