### ISSUE TITLE
bug(mat-radio-group): Programmatically updating a form property with the same object value unchecks its mat-radio-button option

### ISSUE THREAD

**Issue by ericmdantas** [angular/components#24559]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

When programmatically updating a form property that happens to be an object with the same previous value, the `mat-radio-button` gets unchecked. When the form property is a string or a number, there's no problem.

### Reproduction

Link: https://stackblitz.com/edit/angular-ivy-lxats5?file=src%2Fapp%2Fapp.component.ts

Steps to reproduce:

1. After the application is done loading, you can see the different options being programmatically selected after a couple seconds, except when data `{ id: 3 }` is set more than once;
2. Once this happens, the third option is unchecked, even though the form property still has the correct value;

### Expected Behavior

Expected the mat-radio-button option to be selected correctly, even when the form property is updated with the same value more than once. There should be no difference if the value is a string or an object, since the `[checked]=condition` is supposed to take care of the checking rule.

### Actual Behavior

The mat-radio-button option is unchecked when its form property is updated with the same value more than once.

### Environment

- Angular: 13.2.5
- CDK/Material: 13.2.5
- Browser(s): Chrome, Firefox
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

**Comment by AmitParekh1771** [comment]
![image](https://user-images.githubusercontent.com/86157892/158047174-ec89e829-0a52-4e44-8649-1b0cc6287699.png)
![image](https://user-images.githubusercontent.com/86157892/158046942-c19a94a8-ec07-4c9a-a09b-e4b7144a07dc.png)

Here is the bug.
- File location: src/material/radio/radio.ts
- Line: 177, 187, 260
- Function name: ``value`` setter, ``_checkSelectedRadioButton``, ``_updateSelectedRadioFromValue``
- What is causing problem? : whenever ``formControlName`` is applied to ``mat-radio-group``, ``writeValue`` is called which sets the value of field. Here, ``value`` setter checks if value is already set or not. In case of ``string`` or ``numeric`` data type, comparison works perfectly. But this is not the case with javascript ``object`` because two different ``objects`` that looks completely identical with respect to keys and values are not equal when we compare it using ``==`` or ``===`` (i.e. if ``a={id:1}`` and ``b={id:1}`` then ``a is not equal to b`` but we expect it to be equal). This is where above 3 function fail to work.
- Suggested solution: Implementing a utility function that perform ``deep comparison`` of objects or using ``isEqual`` function of ``lodash`` module - to compare two objects and set value of selected radio accordingly.

**Comment by crisbeto** [comment]
This is working as intended. We compare values by reference, not by shape. Also covered by https://github.com/angular/components/issues/10495.
