### ISSUE TITLE
feat(multiple): Components should throw an error if their theme styles are missing

### ISSUE THREAD

**Issue by andrewseguin** [angular/components#24643]
Components should check whether their theme styles are included on the page and throw an error if they are missing. It is easy for application authors to add a new component to their application without remembering to include the appropriate styles in their theme file.

**Comment by crisbeto** [comment]
We have the existing warning in the `MatCommonModule` that checks for the presence of a theme, but ask discussed, it's problematic to expand it into an error for the following reasons:
1. It isn't 100% reliable, because we don't know when the styles will be loaded. E.g. the theme could load after the app has been initialized.
2. The current approach only detects `mat.core`. If we wanted to expand it to all components, we'd have to add theme markers to all component themes which will increase bundle size.
3. We'd have to introduce `getComputedStyle` calls for each Material module which can be expensive.
