### ISSUE TITLE
Without locale how to translate material date picker?

### ISSUE THREAD

**Issue by harleenarora** [angular/components#25070]
### Feature Description

I am not using moment, how to translate the date picker.

Ref:: https://material.angular.io/components/datepicker/overview#datepicker-locale

**Comment by amysorto** [comment]
You don't need moment to be able to translate. If you just want to translate, you can use the MatDatePickerIntl service ([MatDatePickerIntl service docs link](https://material.angular.io/components/datepicker/api#MatDatepickerIntl)) to replace the strings. An example of how to do that for another component is the [stepper that uses the StepperIntl service example](https://material.angular.io/components/stepper/examples#stepper-intl).

Locale is helpful for translations since languages can differ in different regions. Although, In the docs for localization, we recommend using a adapter like moment over native date because it is better for localization: [Datepicker localization docs link](https://material.angular.io/components/datepicker/overview#internationalization). The example you linked above is going to be the best way of properly translating your datepicker.
