### ISSUE TITLE
bug(MAT-ICON): Overflow on mat-icon

### ISSUE THREAD

**Issue by richardsengers** [angular/components#25101]
### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

13*

### Description

IS there a reason mat-icon's have a overflow:hidden.
Since i've updated to angular 14 the overflow hidden causes issues when a mat-icon is within a flexbox

I sometimes end up with things like this

<img width="411" alt="mat-icon" src="https://user-images.githubusercontent.com/810038/174315382-20e00b9f-b7e1-41f0-a1f7-b73b2cfc24e5.PNG">

### Reproduction

https://stackblitz.com/edit/angular-rqxxzj?file=src%2Fapp%2Ficon-overview-example.html

### Expected Behavior

I don't think text or other elements should overlap a mat-icon

### Actual Behavior

Elements did not overlap mat-icons

### Environment

14.0.2

**Comment by andrewseguin** [comment]
In your example, the `mat-icon` element width is being squished to 18.47px, causing the issue you are seeing. To fix this, you can set `flex: none` to the icon to make sure it stays the intended size.

**Comment by MauricioFerraz** [comment]
@andrewseguin 
His point still stands, the css rule for `.mat-icon` was changed to include `overflow: hidden` on version 14 of angular material, and there is no mention of this change and/or others to the styles that came with the update.

Because of it, my system broke in a more spectacular way:

Angular 13
![image](https://user-images.githubusercontent.com/6719790/177805139-bdb79908-3708-4cdb-89a4-5271cdfbe71d.png)
![angular 13](https://user-images.githubusercontent.com/6719790/177802190-71041dfd-556d-4d93-9141-df0e93c3e2a2.png)

Angular 14
![image](https://user-images.githubusercontent.com/6719790/177805080-abd7038a-b6ed-456a-8590-eec8caf3a0ec.png)
![localhost_4200_ (2)](https://user-images.githubusercontent.com/6719790/177802479-ddb979bc-07ce-4d79-8ad9-2a1c5e44aa50.png)



The fix I found to return to the old behavior was to create the following rule in app.component.scss
`
:host ::ng-deep .mat-icon {
  overflow: unset;
}
`
And the result looks just like in version 13
![localhost_4200_ (3)](https://user-images.githubusercontent.com/6719790/177802518-1aa88380-55a1-4245-a600-f11a790fbd64.png)


Changes to style could be treated as breaking changes, or maybe just listed in the changelogs of the releases so users can more readily find the effects of updating this dependency.

**Comment by richardsengers** [comment]
Eventually I did the same: ```overflow: unset``` :-)

**Comment by adrogon** [comment]
I feel like this ticket should be reopened and the change reverted.

There really is no reason for the lib to describe how icons should overflow one way or the other.

[This](https://github.com/angular/components/issues/11826) seems like an overkill solution to a [minor problem](https://github.com/angular/components/issues/11826).
