### ISSUE TITLE
docs(cdk/drag-drop): Example for table.

### ISSUE THREAD

**Issue by infacto** [angular/components#25168]
### Documentation Feedback

Consider to add a [drag-drop](https://material.angular.io/cdk/drag-drop/examples) example with [tables](https://material.angular.io/components/table/overview).

- With `table` and `mat-table`.
- Keep row styling for drag preview. (May only work with mat-table instead of table[mat-table])
- Use handle icon and only drag the row on icon click. (cdkDragHandle issue with mat-table)

### Affected documentation page

https://material.angular.io/cdk/drag-drop (or vice versa on https://material.angular.io/components/table)

**Comment by galanggg** [comment]
Hi @crisbeto, can I take this issue? Thanks.

**Comment by gevorg-gevorgyan-saritasa** [comment]
@infacto @crisbeto Hi guys, currently working on project with Angular 16, and there is an issue: if we use drag and drop with material table using `<table mat-table>`, the drag preview's styles won't work correctly. But if we use `<mat-table>` everything is fine. So I guess we need to update current `table` style, since some of them do not apply if we use native `table`.

In this example you can see how it looks if we replace `<table mat-table>` with  `<mat-table>` using drag and drop - https://stackblitz.com/edit/xjkheu?file=src%2Fexample%2Ftable-basic-example.html

**Comment by Mahmoudibrahim03** [comment]
is some one working on this issue ?!

**Comment by maruthumj** [comment]
@crisbeto chris I will take  this issue. This is my first working on opensource. so I can work on this one.
