### ISSUE TITLE
error (Angular Material - datepicker): Type MatDatepicker is not assignable to type MatDatepickerPanel<MatDatepickerControl

### ISSUE THREAD

**Issue by Killerbear** [angular/components#25208]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

Intellij shows mismatching types for the assignment of a datepicker to the input.
![image](https://user-images.githubusercontent.com/5721655/176910888-2d4bbcc5-c278-4421-b178-fb397724ea1b.png)

there was already a bug report for this issue: #24572

this issue was closed with the explanation:
`It sounds like an issue with Webstorm which we can't do anything about.`

But i think that is not true because this error looks correct to me.
If you look into the angular material datepicker components.
The `MatDatepickerInput` expects a `MatDatepickerPanel`.
But the `<mat-datepicker>` component is of type `MatDatepicker<D> extends MatDatepickerBase<MatDatepickerControl<D>, D | null, D>`

And if you try to assign a `<mat-datepicker>` to the `MatDatepickerInput` it tries to match type `MatDatepicker` with `MatDatepickerPanel` which is not correct and therefor displays an error.
So this error is a correct error for mismatching types.

### Reproduction

HTML:
```
        <mat-form-field appearance="outline" class="date-picker">
            <mat-label>Select Date</mat-label>
            <input matInput
                   [matDatepicker]="datePicker"
                   formControlName="dateOfAppointment" readonly [max]="today"
            >
            <img class="calendar-icon" src="assets/icons/Calendar.svg" (click)="datePicker.open()" alt="Datepicker">
            <mat-datepicker #datePicker></mat-datepicker>
        </mat-form-field>
```

TS:
`today = new Date();`

### Expected Behavior

Intellij doesnt show an error

class MatDatepickerInput expects a datepicker of Type MatDatepicker 

### Actual Behavior

Intellij show an error because of missmatching types

class MatDatepickerInput expects a datepicker of Type MatDatepickerPanel

### Environment

- Angular:  13.2.3
- CDK/Material: 13.2.3 
- IDE: Intellij / WebStorm

**Comment by zarend** [comment]
Hello @Killerbear,

Confirming that `@Input()
matDatepicker` is correctly typed as `MatDatepickerPanel<MatDatepickerControl<D>, D, D>`. That's because `MatDatepicker` implements the `MatDatepickerPanel` interface.

```
export class MatDatepicker<D> extends MatDatepickerBase<MatDatepickerControl<D>, D | null, D> {}
...
export abstract class MatDatepickerBase<
  C extends MatDatepickerControl<D>,
  S,
  D = ExtractDateTypeFromSelection<S>,
> implements MatDatepickerPanel<C, S, D>, OnDestroy, OnChanges
```

Since the typings are correct and this compiles fine in the command line, this is an issue with Intellij. We cannot control what Intellij does, but please let us know if we have incorrect types for our API. I'm closing this issue as it is an issue with Intellij and not this repo.

We're not able to help with this here. I would recommend you file an issue with Intellij and ask in Stackover. that would be a better place for you to get help with this.

Best,
Zach
