### ISSUE TITLE
help(material/list): need help understanding list typography

### ISSUE THREAD

**Issue by Tomassito** [angular/components#25269]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

Giving list component as[ an example](https://github.com/angular/components/blob/3463c5a38cbbe187d022e3bfca075c93dcad2919/src/material/list/_list-theme.scss#L63) here. 
Why does it have `subheading-2` defined as its font? 
Normally `subheading-2` corresponds to `h3` element which is bold (~700) and relatively big (~1.15 REM).
This is how it looks like when dev-tools-applied to 1. element:
![image](https://user-images.githubusercontent.com/37559178/178722495-da89c651-c887-488f-9d77-70e891b86cc4.png)

The problem is hidden until you want to provide your own typography definitions, because normally the theme sets the font to a fixed size of ~16px. However when we want our custom typography for the app, and define the `h3` (subheading-2) this is when it breaks. 

### Reproduction

Steps to reproduce:
1. Provide custom typography for subheading-2:
```
$my-custom-typography: mat.define-typography-config(
  $subheading-2: mat.define-typography-level(1.125em, 1.333, 700),
);
@include mat.core($my-custom-typography);
```

2. Use list with list items somewhere. 

### Expected Behavior

Angular material components look good after providing near-standard typography.

### Actual Behavior

The list component look much different after providing 'standard' styling for `h3`.

### Environment

- Angular:
- CDK/Material:
- Browser(s):
- Operating System (e.g. Windows, macOS, Ubuntu):

**Comment by wagnermaciel** [comment]
Hi, if you'd like subheading-2 to look one way for most of your application and then just want it to look a different way for list, you can call it's typography mixin separately like this `mat.list-typography($my-custom-list-typography)`

I'm not certain why the list is subheading-2 (I forget where the source of truth is located for these sorts of things), but I _**think**_ it's because it's part of the material design spec

I believe my first tip should solve your problem so I'll close this issue. If you'd like a more concrete answer for why the list uses subheading-2, feel free to open a new issue 👍
