### ISSUE TITLE
bug(COMPONENT): how to make mat-label to come in next line if mat-label is too lengthy in mat-form-filed(angular)

### ISSUE THREAD

**Issue by PriyankaNGowda** [angular/components#25367]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

Mat-label length is too long so its getting cut in mat-form-field.
But we want tht mat-label to come in next line if length is too long in angular

### Reproduction

Steps to reproduce:
1. 
2.

### Expected Behavior

we want mat-label to come in next line if length is too long using mat-form-field in angular.

### Actual Behavior

Mat-label is getting cut since mat-label length is too long.

### Environment

- Angular:
- CDK/Material:
- Browser(s):
- Operating System (e.g. Windows, macOS, Ubuntu):

**Comment by amysorto** [comment]
You have a few options here. More text tends to fit on a floating label so that might be a better option. You can change the input to a text area if the label is non floating and if that makes sense in the context of your application since that would fit more text. By default the label text gets truncated if it doesn't fit in the mat-form-field.
