### ISSUE TITLE
Angular CDK Dialog missing afterOpened feature?

### ISSUE THREAD

**Issue by FlashBanistan** [angular/components#25491]
### What are you trying to do?

The MatDialogRef exposes an `afterClosed ` and `afterOpened` observable that are really useful. The new CDK DialogRef looks like it renamed the `afterClosed` observable to just `closed` and completely removed the `afterOpened` observable. Is this intentional?

### What troubleshooting steps have you tried?

Nothing

### Reproduction

Steps to reproduce:
1. 
2.

### Environment

- Angular:
- CDK/Material:
- CDK/Dialog

**Comment by crisbeto** [comment]
`closed` is basically the same as `afterClosed` and we don't have an `afterOpened` equivalent, because the opening sequence of the dialog is synchronous so it'll fire immediately when you call `open`. We have one in the Material dialog, because it has an animation, whereas the CDK dialog doesn't have one.

**Comment by FlashBanistan** [comment]
That's what I was thinking.  The more I thought about it the more I realized there really wasn't any point to having an `afterOpened` observable. Thanks for the clarification!
