### ISSUE TITLE
feat(MatDialog): dialog close button

### ISSUE THREAD

**Issue by dsl400** [angular/components#25727]
### Feature Description

solution to declare close button for dialogs across all application

**Comment by crisbeto** [comment]
Closing this issue as it does not follow the issue template. Please file a new issue that follows the template, which gives the team the information needed to investigate.

**Comment by dsl400** [comment]
clue me .... what is there to investigate on this kind of request?

**Comment by crisbeto** [comment]
There are a lot of different ways to interpret the one sentence which was written in the issue report. Furthermore, we have the `matDialogClose` directive already which allows you to close the current dialog. There's also the `MatDialog.closeAll` method that allows you to close all of the open dialogs.

**Comment by dsl400** [comment]
I am aware that `matDialogClose` exists but the actual button must be declared by the component / content that is rendered in the dialog. My request if for a close-button declared a single time globally for all dialogs to avoid code repetition

**Comment by crisbeto** [comment]
We already have all the APIs in place that allow you to build such a directive yourself. I'm not sure that it's a common enough scenario to bake it into the library. It would basically be this:


```
@Directive({selector: '[matDialogCloseAll]'})
export class DialogCloseAll {
  private dialog = inject(MatDialog);

  @HostListener('click')
  handleClick() {
    this.dialog.closeAll();
  }
}
```

**Comment by dsl400** [comment]
Seams that  my message was not written in the right way. This request is about the HTML definition of a button that will close the dialog. This button should be declared one time only and be available on all instances of MatDialog and close only one dialog at a time

**Comment by crisbeto** [comment]
We're following the Material design spec which generally has the close button inline, rather than the top right so it'll be difficult to guess where we should place it. It's also going to be tricky to provide some way of overriding the template of `mat-dialog-container`, because we would have to either allow for a string template to be passed, which isn't feasible since the template would have to be passed through the Angular compiler, or we would have allow for the entire component to be swapped out which won't be a great API since we would have to require consumers to implement a lot of functionality from the current dialog.

**Comment by dsl400** [comment]
@crisbeto  is there any solution to bind a click event to some :before or :after element and use css for graphics ?
