### ISSUE TITLE
bug(menu, drag and drop): host-context does not work on menu or drag and drop components

### ISSUE THREAD

**Issue by dylanreid7** [angular/components#25816]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

When using :host-context() with a menu or drag and drop component item, the styling is not applied.

### Reproduction

Steps to reproduce:
1. Place a class called "parent-class" on a parent div
2. Place a class on the specific item that should be styled (when an ancestor component has the selector of .parent-class)
3. Apply 
:host-context(.parent-class) {
        .item-class {
             // some styling
        }
  }

See stackblitz for menu component: https://stackblitz.com/edit/angular-shpfzq?file=src/app/menu-overview-example.scss

See stackblitz for drag and drop component: https://stackblitz.com/edit/angular-vwsq5v?file=src/app/cdk-drag-drop-connected-sorting-group-example.css

### Expected Behavior

Styling should be applied when using :host-context() with an ancestor element's selector.

### Actual Behavior

Styling is not applied to menu or drag and drop component items when using :host-context() with an ancestor element's selector.

### Environment

- Angular: 14.0.0
- CDK/Material: 14.2.5
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

**Comment by mmalerba** [comment]
None of the Angular Material components use shadow DOM. Given that `:host-context` is meant to [select the shadow host](https://developer.mozilla.org/en-US/docs/Web/CSS/:host-context), this seems to be working as expected to me.

**Comment by michaelfaith** [comment]
The way the Angular docs describe `:host-context` it behaves as a sort of "ancestor" selector.  And this works great for light/dark theme applications, where we apply a theme class to the body, and then use `:host-context` in our component styles to change the colors for the applied theme.  That all works great in non-dialog use-cases.  But for dialog's we end up having to put those definitions in our `styles.scss`.  I always assumed it's because dialogs are created in a different part of the dom that disrupts that from matching correctly.  But I didn't think it was a lack of shadow dom issue.
