### ISSUE TITLE
docs-bug(cdk/listbox): Refused to load the image

### ISSUE THREAD

**Issue by Totati** [angular/components#26019]
### Documentation Feedback

The `background-image` used for indicating selection does not work. There's an error on the console:
![image](https://user-images.githubusercontent.com/17689719/202700018-45032483-a2fc-40c1-a9a6-d86393c12d83.png)

> Refused to load the image 'data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" height="24" width="24"><path d="m9.55 18-5.7-5.7 1.425-1.425L9.55 15.15l9.175-9.175L20.15 7.4Z"/></svg>' because it violates the following Content Security Policy directive: "img-src 'self' *". Note that '*' matches only URLs with network schemes ('http', 'https', 'ws', 'wss'), or URLs whose scheme matches `self`'s scheme. The scheme 'data:' must be added explicitly.

https://user-images.githubusercontent.com/17689719/202701346-e7d7c98d-5d0c-4abb-9088-cbf1f94a0097.mp4

### Affected documentation page

https://material.angular.io/cdk/listbox/examples

**Comment by kashyapkaki** [comment]
Hi @crisbeto, would love to work on it if no one else working on this issue.

**Comment by allexgut** [comment]
@crisbeto the issue lies within the server's CSP. The img-src part of it is currently configured as follows:
`img-src 'self' 'data:' *; frame-src https://www.youtube.com;`
The error here is that data: is wrapped in quotes. It shouldn't be wrapped in anything, e.g.:
`img-src 'self' data: *; frame-src https://www.youtube.com;`

There's nothing we can do on the frontend side to fix this, so I guess this ticket should be handled internally?

**Comment by Totati** [comment]
Fixed
