### ISSUE TITLE
bug(MatSlider): Value changes events fired twice on firefox

### ISSUE THREAD

**Issue by malciin** [angular/components#26333]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

Described in reproduction & actual behaviour. I also found https://github.com/angular/components/issues/14363 but it was closed.

### Reproduction

Steps to reproduce: https://stackblitz.com/edit/components-issue-u1fdsd?file=src%2Fapp%2Fexample-component.html,src%2Fapp%2Fexample-component.ts

![JZlTBkxW8e](https://user-images.githubusercontent.com/23403545/209720842-1d6b11b6-186e-4b53-b4b3-9251efef57e6.gif)

### Expected Behavior

valueChange is called only once **on firefox**. Should work same as on chrome.

### Actual Behavior

valueChange is called twice, firstly with "weird" values **on firefox** (on chrome it works correctly)

### Environment

- Angular: 15
- CDK/Material: 15
- Browser(s): firefox
- Operating System (e.g. Windows, macOS, Ubuntu): stackblitz, linux, windows

**Comment by wagnermaciel** [comment]
I tried this out on the latest version (15.0.3) but was unable to reproduce it. It may have been fixed in one of the latest patches. Are you able to reproduce it with @angular/material on version 15.0.3? Here's a link to my forked stackblitz

https://stackblitz.com/edit/components-issue-hvxcnh?file=package.json,src%2Fapp%2Fexample-component.ts

**Comment by malciin** [comment]
Indeed it works, on my project I've got 15.0.1 but it looks like on newest version everything works correctly. Thanks!
