### ISSUE TITLE
feat(slider): vertical slider

### ISSUE THREAD

**Issue by oleal** [angular/components#26695]
### Feature Description

slider seems to be only horizontal

for material for angular js, a "vertical" property existed for mat-slider

### Use Case

chose orientation for mat-slider

**Comment by sorozco2** [comment]
Any update on this feature?

**Comment by bgomes-bacardi** [comment]
Given that

![image](https://github.com/angular/components/assets/122870289/ebff68fb-fd7d-48dc-8521-eb8c4513cfce)

The legacyslider will be deprecated this priority should be higher? @wagnermaciel

**Comment by wagnermaciel** [comment]
@jelbourn Is this still a feature we are considering adding?

**Comment by wagnermaciel** [comment]
I discussed this with the team and the unfortunate conclusion is that this is not something we plan on implementing

### Context
The new mdc-based slider is built following the [Material Design Component's html structure](https://m2.material.io/components/sliders/web#sliders) and **directly using** their styles (IMPORTANT: This is not owned by us). The reason why the `vertical` option was removed from our library is that the [Material Design Slider spec & implementation](https://m2.material.io/components/sliders) do not include a vertical slider.

### Why not provide one anyway?
Since we are Angular **Material** Components, we already have incentive not to diverge from the Material Design spec. On top of this, if we were to try to implement this on our end (on top of MDC's styles) it would be a hacky workaround at best and make it more difficult to maintain the interface between our library and theirs.

### Conclusion
As long as the Material Design Spec does not include a vertical slider, our library will not be implementing one.

If you'd like to advocate for a vertical slider to get added to the Material Design Spec, please feel free to visit https://m2.material.io/components/sliders. At the bottom of the page, there is a `feedback` link which you can use to request this feature.

If a vertical slider is ever added to the Material Design Spec, I am more than happy to reopen this issue
