### ISSUE TITLE
bug(mat-chip-grid): mat-chip-grid does not show mat-error field

### ISSUE THREAD

**Issue by antonthomas** [angular/components#26728]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

Using `mat-error` in a `mat-form-field` that features a `mat-chip-grid` does not display an error field.

### Reproduction

Steps to reproduce:
1. Create a `mat-form-field` with a `mat-chip-grid` and a `mat-error`

https://stackblitz.com/edit/angular-jpb6vv?file=package.json

### Expected Behavior

The error should be displayed.

### Actual Behavior

The error is not displayed.

### Environment

- Angular: 15.0.0
- CDK/Material: 15.2.1
- Browser(s): MS Edge
- Operating System (e.g. Windows, macOS, Ubuntu): Windows 11

**Comment by mmalerba** [comment]
`<mat-error>` works together with `@angular/forms` to show error messages when the form is in an invalid state. Since your example is not using Angular Forms, it is not in an invalid state and the error is not shown. Here is an example with Angular Forms where the error message is shown: https://stackblitz.com/edit/llqfdo?file=src%2Fapp%2Fchips-form-control-example.html
