### ISSUE TITLE
docs-bug(sidenav): All examples broken

### ISSUE THREAD

**Issue by Sanafan** [angular/components#26743]
### Documentation Feedback

I just only tested the sidenav doc right now but the examples on stackblitz are not loading anymore. There is an error message:

> Error in material-module.ts
> The entrypoint for '@angular/cdk' could not successfully be resolved. The file '/turbo_modules/@angular/cdk@6.4.7/drag-drop' > does not exist. Please log an issue with the package author or check for an updated version of the package.

### Affected documentation page

https://v6.material.angular.io/components/sidenav/examples

**Comment by amysorto** [comment]
Hey thanks for pointing this out! This affects a much older version of the docs site (v6, we are currently on v15). I am going to close the issue since we won't be able to spend the time to look into this, and the code for the examples is still accessible on the docs site. Apologies for the inconvenience.
