### ISSUE TITLE
customized transition time

### ISSUE THREAD

**Issue by Frozen-byte** [angular/components#2675]
#### What is the expected behavior?
Please let us customize the transition timings without hacking it into the current build.

#### What is the current behavior?
Transition time is fixed at 150ms (i.e. MdTooltip)

#### What are the steps to reproduce?
Look: https://github.com/angular/material2/blob/b49bfce5a9796441314bd2eed93e26e47a48e9ca/src/lib/tooltip/tooltip.ts#L259

#### Is there anything else we should know?
This request is especially for MdTooltip, but I guess it is smarter to allow customized transition timings on every Component.

**Comment by jelbourn** [comment]
(revisiting old feature requests)

Closing this issue since I don't realistically see us adding support for custom animation durations in the immediate future. It may happen as part of a larger theme system overhaul (where animations are included in the theme), but not something we would tackle standalone.
