### ISSUE TITLE
bug(Mat-Slider): Max value disregarded while async hook fires

### ISSUE THREAD

**Issue by knackstedt** [angular/components#26844]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

When using the mat-slider with an asynchronous event (e.g. timeout or stream callback), with a dynamic `[max]` property, the max property is disregarded in favor of `100` as the max value.

It also seems to debounce events, given how frequently it actually moves the slider thumb. It would be nice to be able to disable this, for smoothing out the animation when using the slider as an adjustable progress bar (think of a Youtube video slider bar)

### Reproduction

1. click on "trigger lifecycle". This starts an async setInterval that increments the [value] provided to the slider.
2. click on "change max". This increases the [max] by 100
3. move the slider to the center, and observe the reported "current value" being ~50, where ~100 would be expected as the max was updated to 200. The output text reports an accurate max value, while the slider is disregarding it.

https://stackblitz.com/edit/components-issue-mid1b8?file=src%2Findex.html,src%2Fapp%2Fexample-component.html,src%2Fapp%2Fexample-component.ts,src%2Fapp%2Fexample-component.css

### Expected Behavior

Dynamic update of [max] such that the current slider position is always a percentage of the current maximum

### Actual Behavior

maximum is defaulted to 100 when there is an async lifecycle hook

### Environment

- Angular: 15.1.2
- CDK/Material: 15.1.2
- Browser(s): Chrome 112.0.5615.20 (Official Build) beta (64-bit)
- Operating System (e.g. Windows, macOS, Ubuntu): linux x64

**Comment by wagnermaciel** [comment]
The `min`, `max`, and `step` should be set on the parent `<mat-slider>` element. For example:

```html
<mat-slider min="0" [max]="duration" step="0.1">
    <input matSliderThumb [value]="myValue" />
</mat-slider>
```

Setting the min max and step of the native input element directly will bypass most of our logic for updating the visual component

**Comment by wagnermaciel** [comment]
Btw, just wanted to say ty for the clear stackblitz! We _**really**_ appreciate when folks take the time to produce clear steps to reproduce an issue. I just wanted to take a second to say thank you 😃

**Comment by knackstedt** [comment]
Thanks!
Is it possible to remove the typing for the min max and stop values from the child input element? It wasn't clear to me that doing so was problematic.
It would also be nice to have a simple example on the CDK site showing a 2-way bound slider for reference ;)

**Comment by wagnermaciel** [comment]
> Is it possible to remove the typing for the min max and stop values from the child input element?

We actually can't remove the typing for the min, max, and step from the child input element bc it _is_ an input element. Exposing the native input this way instead of keeping it hidden to devs might create some confusion, but it's very common to want to directly interact with the native input

> It would also be nice to have a simple example on the CDK site showing a 2-way bound slider for reference

That does sound like a good improvement to the docs site, but Angular offers a lot of different ways to bind to inputs. If we were going to add an example like this to the docs site I think it'd also make sense to add examples for all of these options

1. Template driven form controls
2. Reactive form controls
3. One-way property bindings
4. Two-way property bindings

But honestly, I think it's a good idea. If you want to file another issue for improving the docs on slider it'd probably be pretty low priority but it'd likely get picked up in a future fixit or if I'm bored one afternoon lol
