### ISSUE TITLE
docs-bug(MatChips): Input placeholder is not showing if not focused

### ISSUE THREAD

**Issue by jakubweber** [angular/components#26883]
### Documentation Feedback

In v14 the placeholder is always visible, since v15 is visible only when input is focused. Is it a purpose?
Also the add input is wrapped on the next line.

### Affected documentation page

https://material.angular.io/components/chips/examples
![Screenshot from 2023-04-04 14-50-22](https://user-images.githubusercontent.com/5078760/229798655-5055401b-1fd7-468e-a803-99dd757763fa.png)
![Screenshot from 2023-04-04 14-50-12](https://user-images.githubusercontent.com/5078760/229798681-56470ce9-019f-496d-9e91-70c9b298c774.png)

**Comment by zarend** [comment]
Hello @Naaajii ,

Thank you for reaching out.

I believe that in Material Design spec, placeholder is not supposed to be shown on text inputs until focused. I believe this is working as intended since it follows MD spec. Please let us know if you find something in Material Design specification that says otherwise, so that we can consider it.

Best regards,

Zach
