### ISSUE TITLE
docs-bug(COMPONENT): Custom themes for mat-menu is missing in documentation

### ISSUE THREAD

**Issue by vitaly-t** [angular/components#26965]
I'm stuck trying to make `mat-menu` apply my custom themes for Angular v15. Any issue related to it forwards me to the [official documentation for theming with overlays](https://material.angular.io/guide/theming). All the while, there are no overlay details of any kind in that documentation, or anything pertinent to menu specifics.

So I don't know if it is an issue with invalid documentation or functionality, and how to make custom themes work for `mat-menu`. Do you have anything in documentation to help with that at all? I cannot seem to find.

### Affected documentation page

https://material.angular.io/guide/theming

**Comment by amysorto** [comment]
Closing this issue since this is will be available in V19. There is a new `theme()` mixin that will greatly simplify theming files. By default that mixin creates system variables which are CSS variables that the different components use. On each component page there will be a styling tab that has documentation on how to customize the theme. This is the preview for menu: https://next.material.angular.io/components/menu/styling. The theming guide will be updated with more details and instructions.
