### ISSUE TITLE
bug(mat-form-field): Rendering performance issue for mat-form-field with outline appearance

### ISSUE THREAD

**Issue by artembelik** [angular/components#27005]
### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

<15.0.0

### Description

Low rendering performance occurs only on MacBook with an Intel processor (i7, see environment), on MacBook with an Apple processor (m1) everything works as expected.

### Reproduction

Steps to reproduce:
- Create multiple mat-form-field with outlline appearance

[stackblitz reproduction](https://stackblitz.com/edit/47rzdj?file=src/app/input-overview-example.ts)

### Expected Behavior

Fast  rendering performance for any device

### Actual Behavior

![Screen Recording 2023-04-28 at 13 55 27](https://user-images.githubusercontent.com/24925224/235136901-d8a3e7ef-94d3-4b24-8d64-cf6b2f6ef8fd.gif)

### Angular version:

Angular CLI: 15.0.5
Node: 16.14.2
Package Manager: yarn 1.22.19
OS: linux x64

Angular: 15.0.4

| Package | Version |
| --- | --- |
| @angular-devkit/architect  |  0.1500.5 |
| @angular-devkit/build-angular | 15.0.5 |
| @angular-devkit/core | 15.0.5 |
| @angular-devkit/schematics | 15.0.5 |
| @angular/cdk | 15.2.8 |
| @angular/cli | 15.0.5 |
| @angular/material | 15.2.8 |
| @angular/material-moment-adapter | 15.2.8 |
| @schematics/angular | 15.0.5 |
| rxjs | 7.4.0 |
| typescript | 4.8.4 |

---

### System Software Overview:
- System Version: macOS 13.3.1 (22E261)
-  Kernel Version: Darwin 22.4.0

### Hardware Overview:
- Model Name: MacBook Pro
- Model Identifier: MacBookPro16,1
- Processor Name: 6-Core Intel Core i7
- Processor Speed: 2,6 GHz
- Number of Processors: 1
- Total Number of Cores: 6
- Hyper-Threading Technology: Enabled
- Memory: 16 GB

**Comment by Julien-Marcou** [comment]
I'm on a MacBook with an M1 processor, and I'm having the same issue, though it may be harder to reproduce.

To make the issue easier to reproduce, the idea is to have a great amount of inputs visible at the same time on your display, if you render like 200 inputs, but only 10 are visible at once, the problem may not be visible, but if 200 inputs are visible at the same time, when you start to scroll, you'll see input disappearing and reappearing as if there were not enough resources on the machine.

When I disable the `hardware acceleration` on Chrome, the issue is no longer present, but the page becomes extremely laggy.

Here is my system info:

```shell
Software Overview:

      System Version: macOS 13.3.1 (a) (22E772610a)
      Kernel Version: Darwin 22.4.0

Hardware Overview:

      Model Name: MacBook Pro
      Model Identifier: MacBookPro17,1
      Chip: Apple M1
      Total Number of Cores: 8 (4 performance and 4 efficiency)
      Memory: 16 GB
```

I investigated the problem and I can confirm the problem is only present for `outline` inputs, and that this issue didn't exist in Angular Material v14.

Removing the `will-change: transform;` CSS rule from `.mdc-floating-label` entirely resolves the performance issue for me.

So here is my work around:

```scss
// In your global CSS
.mat-mdc-form-field .mdc-floating-label {
  will-change: initial;
}
```

**Comment by crisbeto** [comment]
Same root cause as https://github.com/angular/components/issues/14336 which has a pending fix.
