### ISSUE TITLE
Animations for md-select can not be disabled.

### ISSUE THREAD

**Issue by Tqader** [angular/components#2719]
#### Bug, feature request, or proposal:
unable to disable md-select animations

#### What is the expected behavior?
I want to be able to disable all animation behavior for md-select

#### What is the current behavior?
Animations are a part of the template for md-select. There is not api to disable them.

#### What are the steps to reproduce?
Add md select to a html page, cjick on it, there is is an animation as the ms-select-panel is displayed. Oce an item is selected, ther is another animation as the menu is closed.
Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: http://plnkr.co/edit/o077B6uEiiIgkC0S06dd

#### What is the use-case or motivation for changing an existing behavior?
Do not want animated behavior for my application.
#### Which versions of Angular, Material, OS, browsers are affected?
2.0.0-beta.1

**Comment by Jonatthu** [comment]
@kara  Is this going to be implemented?

**Comment by liri2006** [comment]
+1

**Comment by victornoel** [comment]
@Tqader if you want to disable animations for the whole application, have you tried using `NoopAnimationsModule` instead of `BrowserAnimationsModule`?
Not sure it will solve the problem since according to #4227, not everything is disabled with it…

**Comment by lokeshdaiya** [comment]
In angular's new update in [4.3.1](https://github.com/angular/angular/blob/master/CHANGELOG.md) animations can be disable. 
I tried to disable animation on md-tab and it worked but for md-select I don't want option overlay to move upside.But due to transform-origin which is in inline style for md-select, can't disable it.

here is sample plnkr https://plnkr.co/edit/sVJM8H?p=preview

**Comment by Stas-tolpekin** [comment]
@kara 
This problem is still actual for beta.10. 
Why is it a problem?
1. fade in/out animation of panel is very slow for fast(power) users.
2. the animation work slow on IE11 (has lags)

I would like to suggest one more feature: API allows to select animation speed.

**Comment by supruniuk** [comment]
@victornoel your solution works. md-select is perfect without animation.

**Comment by GitSage** [comment]
I'm having the same problem. I'm trying to write Protractor automated tests but these animations are causing a headache.

`[[@.disabled]]` doesn't have any effect at all on whether animations occur. This same issue applies to `mat-menu`. [See stackblitz](https://stackblitz.com/edit/angular-mlufhj). 

`@HostBinding('@.disabled') public animationsDisabled = false;` also does nothing (I know it's the same thing, but I had to give it a try).

`NoopAnimationsModule` disables the dropdown animation, but I can't use that due to AOT making it impossible to conditionally add modules to `imports`. 

Adding the style `* { transition: none !important }` does not affect the animations. Apparently they're not CSS transitions.

Does anyone have any good workarounds to get these Protractor tests working? Maybe a way to conditionally load NoopAnimationsModule even with AOT in place? I'd even settle for a reliable way to have Protractor `wait` until all animations are complete.

**Comment by ChrisProlls** [comment]
Same problem here ! Any news ?

**Comment by eugenefedotov** [comment]
still nothing?

**Comment by jelbourn** [comment]
The animation for `MatSelect` can be disabled with `NoopAnimationsModule`
