### ISSUE TITLE
bug(cdk/drag-drop): dragging does not work for elements that are outside the first screen when scrolling horizontally

### ISSUE THREAD

**Issue by NeoSimvolist** [angular/components#27287]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

Check out the sandbox. Drag and drop only works for the first 4 items that go into the first scroll screen.

https://stackblitz.com/edit/448fm5-wvlpbq

### Reproduction

StackBlitz link: 
Steps to reproduce:
1. scroll to the 6th element.
2. Try to move it.
3. Other elements do not respond to movement. The cdkDropListDropped event returns the same currentIndex and previousIndex

### Expected Behavior

All 13 elements respond to each other's movements

### Actual Behavior

from the 5th to the 13th elements do not respond to movement

### Environment

- Angular: 16
- CDK/Material: 16
- Browser(s): Chrome 114.0.5735.110
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

**Comment by crisbeto** [comment]
I looked into this and it seems to be behaving as expected. The problem is that when the `.columns-container` is `display: block`, the inner drop container on `.columns` is 300px wide as well. The reason you can see all the items is because it's `overflow: visible` by default, but if you put `overflow: hidden` on it, the parent won't be scrollable anymore. Dragging doesn't work for the items outside the viewport, because the CDK measures the size of the container, not the size of the visible content. It starts working with `display: flex`, because now the drop list matches the size of its content.
