### ISSUE TITLE
Use importLibrary API to load Google Maps

### ISSUE THREAD

**Issue by crisbeto** [angular/components#27373]
Google Maps has an API that requires a minimal JavaScript snippet to allow for the full API to be loaded asynchronously. We should consider supporting it since it'll improve the DX of the Google Maps package. Note that using it would involve some refactoring to turn the existing synchronous call sites into asynchronous ones.

Docs for the `importLibrary` API: https://developers.google.com/maps/documentation/javascript/load-maps-js-api#dynamic-library-import

**Comment by jackson-green** [comment]
I think this is a really good idea, especially since the documentation refers to it as the "recommended" way to load the api. It also mentions being able to load the libraries you need only when you need them, it would be really cool if this could somehow be implemented with the new standalone api architecture in v16. Maybe something like this
```typescript
export const routes: Route[] = [
  {
    path: 'map',
    providers: [
      provideMapsApi({ key: 'YOUR_API_KEY', version: 'weekly' }, withDrawingLibrary())
    ]
  }
];
```
Or maybe if it were possible to make it even more granular and sort of follow what ngrx has done with their standalone api
```typescript
export const routes: Route[] = [
  {
    path: 'map',
    providers: [
      provideMapsApi({ key: 'YOUR_API_KEY', version: 'weekly' })
    ],
    children: [
      {
        path: 'drawing',
        providers: [
          provideMapsDrawingLibrary()
        ]
      }
    ]
  }
];
```
I'm not sure if either of these are even possible but I thought I would throw in my two cents.

**Comment by crisbeto** [comment]
This one was fixed in https://github.com/angular/components/pull/28307.
