### ISSUE TITLE
bug(@angular/google-maps): google not defined

### ISSUE THREAD

**Issue by Om-Codal** [angular/components#27437]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

12

### Description

I used 12.2.13 version of @angular/google-maps in my angular application and it is working great but when i tried to run test cases in my angular application i am getting **ERROR: google is not defined**

I tried one solution added **https://maps.googleapis.com/maps/api/js?key** in karma.conf.js inside files but still getting same error.

So can you please provide me solution.

### Reproduction

install @angular/google-maps

### Expected Behavior

it should work

### Actual Behavior

google is not defined

### Environment

- Angular: 12.2.15
- CDK/Material:
- Browser(s): Google Chrome
- Operating System (e.g. Windows, macOS, Ubuntu):Windows

**Comment by crisbeto** [comment]
It's because the Google Maps API isn't loaded in the test. You'll have to either exclude the Maps component from the test or mock out the Maps API yourself. You can see how it can be mocked out in our own tests https://github.com/angular/components/blob/main/src/google-maps/google-map/google-map.spec.ts.
