### ISSUE TITLE
bug(mat-slide-toggle): Incorrect accent dark theme color

### ISSUE THREAD

**Issue by lukasma** [angular/components#27484]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

The accent colors for `mat-slide-toggle` were overriden by random colors:

![slide-toggle-random-dark-theme-colors](https://github.com/angular/components/assets/27922584/0dd162c2-f8fd-489a-a8c3-3ac351f319be)
![slide-toggle-overriden-dark-theme-colors](https://github.com/angular/components/assets/27922584/fde5ff46-dc54-4e76-8e94-7a4d31267692)

### Reproduction

Steps to reproduce:
1. Use `@include mat.all-component-colors($dark-theme);` to set component colors for dark theme.
2. Add `mat-slide-toggle` to a template:
`<mat-slide-toggle color="accent"></mat-slide-toggle>

### Expected Behavior

Accent colors of dark theme are used for `mat-slide-toggle`'s.

![slide-toggle-correct-dark-theme-color](https://github.com/angular/components/assets/27922584/b279e226-ec9c-43f5-a663-2365e3a7178d)

### Actual Behavior

Random colors are used for `mat-slide-toggle`'s in dark theme.

![slide-toggle-wrong-dark-theme-color](https://github.com/angular/components/assets/27922584/a947a1d5-8bfd-4e46-93b2-9d6f9d2628e1)

### Environment

- Angular: 16.1.6
- CDK/Material: 16.1.6
- Browser(s): Chrome, Version 114.0.5735.133 (Official Build) (64-bit)
- Operating System (e.g. Windows, macOS, Ubuntu): Ubuntu

**Comment by json-derulo** [comment]
The default behavior is that Angular Material sets the colors which you defined in your theme. In light theme apparently you are overriding this colors with your own CSS variables. In dark theme you don't do it. By using the `mat.all-component-colors` mixin, the colors from the theme are set, scoped to the `.dark-theme` selector and without your own CSS variables. Due to higher specifity they win over your variables. I think everything is working as intended.

To fix it you either need to do whatever you do for light theme again for dark theme, however you would end up having the same CSS variables twice. What you could also try is to stop using the `mat.all-component-colors` mixin for dark mode and load the colors of each component separately with the corresponding mixin, omitting the one for the slide toggle. However this could have the side effect that colors like the text colors end up missing.

**Comment by wagnermaciel** [comment]
+1 to everything @json-derulo said. As far as I can tell, this is working as intended
