### ISSUE TITLE
bug(Mat-Form-Field): The two mat-form-field shows overlapping error message

### ISSUE THREAD

**Issue by tyagi-bhoopesh** [angular/components#27522]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

I am facing an issue when two mat-form-field with input["text"] and outline design , so i am getting overlapping the error message between two mat-form-field. Here, I have attached the screenshot..

<img width="356" alt="image-2023-07-25-16-46-23-954" src="https://github.com/angular/components/assets/24448437/a9ef0788-2186-4500-b40b-fd1037270601">

### Reproduction

Here I attached the component which uses the mat-form-field-component.

[category-card.zip](https://github.com/angular/components/files/12179474/category-card.zip)

### Expected Behavior

If we use two or more mat-field-form component with outline design these are overlapp with each other.

### Actual Behavior

The mat-field-form error message should not overlapping with any other component.

### Environment

- Angular: 15.2.6
- CDK/Material: 15.2.6
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

**Comment by json-derulo** [comment]
This is by design. As per [docs](https://v15.material.angular.io/components/form-field/overview#error-messages):

> `<mat-form-field>` only reserves enough space to display one error message at a time.

It is not expected that error messages wrap into a new line, in this case it's up to you to reserve enough space.

In case you are already using the MDC-based components, you can set the `subscriptSizing` option on the form field to `dynamic`. This will make sure that enough space will be reserved for the error message, as needed. However this is not the default behavior.

**Comment by tyagi-bhoopesh** [comment]
@json-derulo Thank you! It works for me. I am closing this issue.
