### ISSUE TITLE
bug(MatTable): Expandable MatTable rows are expanded when inside a MatTab inside a component

### ISSUE THREAD

**Issue by kvnhrtwg** [angular/components#27560]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

When putting a MatTable with expandable rows (example is taken from the [docs](https://material.angular.io/components/table/examples#table-expandable-rows)) inside a component and nesting this component inside a MatTab, all rows are expanded simultanously when going back to the tab with the component inside.
If the table is not inside a component but the code is put directly inside the MatTab then everything is working fine.

### Reproduction

StackBlitz link: https://stackblitz.com/edit/nbcsw1
Steps to reproduce:
1. Go to second step in stepper
2. Go back to first step

### Expected Behavior

All rows are collapsed

### Actual Behavior

All rows are expanded

### Environment

Angular CLI: 16.1.0
Node: 16.20.0
Package Manager: yarn 1.22.19
OS: linux x64

Angular: 16.1.1
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.1601.0
@angular-devkit/build-angular      16.1.0
@angular-devkit/core               16.1.0
@angular-devkit/schematics         16.1.0
@angular/cdk                       16.1.6
@angular/cli                       16.1.0
@angular/material                  16.1.6
@angular/material-moment-adapter   16.1.6
@schematics/angular                16.1.0
rxjs                               7.4.0
typescript                         5.0.3

**Comment by andrewseguin** [comment]
Try using Lazy Loading for tabs to see if this helps https://material.angular.io/components/tabs/overview#lazy-loading

**Comment by kharazian** [comment]
Hello,

I believe the observed behavior can be attributed to a specific cause. It appears that the simultaneous expansion of all rows in a MatTable with expandable rows, within a custom component nested inside a MatTab, is influenced by the parent element's visibility being set to "hidden." This action triggers Angular's change detection mechanism and Angular Material's animation cleanup process, including the execution of the eraseStyles function.

In order to address this issue, a potential solution could be to integrate the void state within animations. This approach would lead to animations resetting to their original conditions after the eraseStyles function is executed. By taking this proactive step, it is possible to effectively resolve the challenge of simultaneous row expansion. As a result, users would enjoy a seamless and expected interaction when they return to the MatTab containing the nested component.
