### ISSUE TITLE
bug(mat.core()): Undeclared mixin

### ISSUE THREAD

**Issue by nbianka99** [angular/components#27842]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

I want to make a custom theme for my Angular Project and I receive the 'Undeclared mixin' error even though I insert the following line at the top of my theme file: @use '@angular/material' as mat;
When I try to @include mat.core(); I receive this error.

### Reproduction

StackBlitz link: 
Steps to reproduce:
1. Create a .scss file 
2. Add the following code to it:
`@use '@angular/material' as mat;

@include mat.core();

$my-primary: mat.define-palette(mat.$indigo-palette, 500);
$my-accent: mat.define-palette(mat.$pink-palette, A200, A100, A400);

$my-theme: mat.define-light-theme((
 color: (
   primary: $my-primary,
   accent: $my-accent,
 ),
 typography: mat.define-typography-config(),
 density: 0,
));

@include mat.all-component-themes($my-theme);`
4. 

### Expected Behavior

It should not throw an error

### Actual Behavior

It throws an error

### Environment

- Angular:  16.2.3
- CDK/Material: 16.2.5
- Browser(s): Chrome/Edge
- Operating System (e.g. Windows, macOS, Ubuntu): Windows 10

**Comment by mmalerba** [comment]
It sounds like something is misconfigured in your project. That mixin should exist, as you can see in the example here it works without any errors: https://stackblitz.com/edit/6jqdea?file=src%2Ftheme.scss

Please reserve Github issues for bug reports and feature requests rather than troubleshooting. Consider asking in other channels such as stackoverflow for help troubleshooting (and please provide as much information as possible about the error, it will be hard for people to help without sufficient information).
