### ISSUE TITLE
feat(multiple): still support legacy components in v17

### ISSUE THREAD

**Issue by pweyrich** [angular/components#27942]
### Feature Description

In https://github.com/angular/components/pull/27622 you've removed support for legacy components. This means, that once Angular v17 is out, one would be forced to use the mdc-based components only.

While this might have been a reasonable choice for your team - also conforming to your update and deprecation policies - there are codebases out there (including ours) that haven't migrated to the new components yet.
Reasons for that are probably diverse, but one major reasons for us was the knowledge about your efforts on eventually offering a brand-new token-based theming API.

We work on a bigger enterprise grade application with a design system that's based on customized material components. Due to limited official support for customizations on the current theming API (as of v16 with legacy components) , we tend to override a lot of (global) component styles.
While eagerly waiting for the new token-based theming API to evolve and stabilize, we hoped to have the chance to upgrade directly to this new theming API, component by component.
With the discontinued support of legacy components in v17 however, this is now impossible and our migration path to the mdc-based components is very steep (either high effort or high risk).

### Use Case

I can only see 2 options for us to move forward right now:

1. While staying on v16, migrate each legacy component to the new mdc-based ones, component by component. This will require us to integrate with a new but still not latest theming API of the mdc-components first. After that migration is completed we would upgrade to v17 and have to re-integrate with the latest theming API once more, resulting in doubled theme integration effort. (high effort)
2. Upgrade to v17 and migrate to mdc-based components at the same time. This would require us to migrate all components at once, which would tremendously increase the risk of the migration. However, we would only need to integrate with the latest theming API once. (high risk)

Is there maybe another scenario that I am missing?

In case there's really no other option than these two, which I both consider as "not ideal", I would kindly ask you to re-consider still supporting legacy components in v17!

**Comment by EmmanuelRoux** [comment]
I have the exact same problem in my company. 
Thank you for detailing it @pweyrich

**Comment by andrewseguin** [comment]
Thanks for reporting this issue and clearly explaining your scenario. We understand that this migration is not easy, especially for uses where clients have applied their own custom style overrides. Since the HTML has changed, this means a significant amount of work to re-adjust overrides. This is something we found across several large-scale applications within Google. We wish we had better theming and style customizations available before this effort took place, which would have made this migration smoother for clients.

I’d strongly recommend the approach of migrating component-by-component while using v16. This should not block you from moving on to v17 (and later, v18) for the rest of Angular. As you switch, you should take advantage of the density API and utilize CSS variable overrides for some customization. I don’t expect the subsequent move to the latest theming API will be nearly as significant (hopefully just a few changed API calls in your theming file).

We empathize with our clients having to put in this immense effort to migrate. We know it’s challenging and painful for many clients. In the past we’ve done our best to make upgrades as simple as possible, but due to the nature of these HTML changes, this was challenging to simplify. Going forward, if your migration holds your back for a while, we are working with HeroDevs to make sure the legacy components stay compatible with ongoing Angular versions.
