### ISSUE TITLE
bug(Mat-Autocomplete): Selected Option does not get appropriate CSS when using OptGroup and Filtered List

### ISSUE THREAD

**Issue by Rudazzle** [angular/components#28082]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

In the normal AutoComplete when selecting an option, it will get highlighted via the "mdc-list-item--selected" class being added to the mat-option and also the mat-pseudo-checkbox element getting inserted.  However, when you configure an AutoComplete with OptGroup and use filtering, this does not occur.  

This is reproducible in the Angular Material example for the Options Groups Autocomplete.

### Reproduction

StackBlitz link: https://stackblitz.com/edit/youm9c?file=src%2Fexample%2Fautocomplete-optgroup-example.html
Steps to reproduce:
1. Select an option in the Filtered group
2. Open the dropdown after selecting and note that it is not highlighted and does not include the checkbox

### Expected Behavior

Selected option gets Highlighted via the "mdc-list-item--selected" class being added to mat-option and inserts html for mat-pseudo-checkbox

https://i.stack.imgur.com/II4v3.png

### Actual Behavior

Selected option does not get the css or html added to provide any visual indication that this option has been selected.

https://i.stack.imgur.com/UFq2N.png

### Environment

- Angular: 17
- CDK/Material: 16.2.11
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Windows 11

**Comment by yurakhomitsky** [comment]
@Rudazzle As far as I can tell, the problem is not with the `OptGroup` component; rather, it is with the `MatAutoComplete` component, which does not handle a selection of selected `mat-option` like `MatSelect` does (At least I don't see that code)

The way it works: Each `mat-option` holds a selected state and emits the event that the selection has been made. The `MatAutoComplete` does not listen to those changes and does not manage a selection state.

In the example that you have provided, you are returning a brand-new object after the search
`.map((group) => ({
          letter: group.letter,
          names: _filter(group.names, value),
        }))`
        
 This code makes Angular to re-render the list which destroys `mat-option` instances that had the `selected` flag set to `true` and that is why you don't see the "highlighted" state.
 
 To fix your issue you could use a `trackBy` function
`*ngFor="let group of stateGroupOptions | async; trackBy: trackByFn"`
 
 `trackByFn = (_: number, item: StateGroup): string => {
    return item.letter;
  };`

**Comment by Rudazzle** [comment]
@yurakhomitsky That worked perfectly!  Thank you so much!
