### ISSUE TITLE
bug(MatAutoComplete): filterOptions always use first element

### ISSUE THREAD

**Issue by maxwell60701** [angular/components#28118]
### Description

I wrote two mat-autocomplete controls,but the filterOptions always use first element

https://stackblitz.com/edit/zdy1sg-q7hzgp?file=src%2Fexample%2Fautocomplete-auto-active-first-option-example.html

### Reproduction

StackBlitz link: https://stackblitz.com/edit/zdy1sg-q7hzgp?file=src%2Fexample%2Fautocomplete-auto-active-first-option-example.html

Steps to reproduce:
1. two different filterOptions,but always use first one

### Expected Behavior

filterOptions are correct

### Actual Behavior

filterOptions always use first one

### Environment

- Angular: 14,16
- CDK/Material:16
- Browser(s):edge,chrome
- Operating System (e.g. Windows, macOS, Ubuntu):Windows

**Comment by crisbeto** [comment]
It's because you've assigned the same name to both of the autocomplete panels and you're pointing the trigger to the same one. You should rename one of the panels (e.g. `#auto` to `#autoTwo`) and change one of the triggers to point to it. See https://stackblitz.com/edit/zdy1sg-idvyfi?file=src%2Fexample%2Fautocomplete-auto-active-first-option-example.html

**Comment by maxwell60701** [comment]
it is worked,thank you very much

**Comment by maxwell60701** [comment]
Hello,one more question,does it support multi selection? @crisbeto

**Comment by crisbeto** [comment]
It does not.
