### ISSUE TITLE
docs-bug(theming): view encapsulation and theming own Angular components?

### ISSUE THREAD

**Issue by rpanadero** [angular/components#28128]
### Documentation Feedback

I don't find clear information about how to theme my own Angular components. I have just found this documentation: 

https://material.angular.io/guide/theming-your-components

In the next example, image I'm creating a custom carousel Angular component which has a theming scss file.

```
// _carousel-theme.scss

@use 'sass:map';
@use '@angular/material' as mat;

@mixin color($theme) {
  .my-carousel-button {
    // Read the 500 hue from the primary color palette.
    color: mat.get-theme-color($theme, primary, 500);
  }
}

@mixin typography($theme) {
  .my-carousel {
    // Get the headline font from the theme.
    font: mat.get-theme-typography($theme, headline-1);
  }
}

@mixin theme($theme) {
  @if mat.theme-has($theme, color) {
    @include color($theme);
  }

  @if mat.theme-has($theme, typography) {
    @include typography($theme);
  }
}
```

```
@use '@angular/material' as mat;
@use './path/to/carousel-theme' as carousel;

@include mat.core();

$my-primary: mat.define-palette(mat.$indigo-palette, 500);
$my-accent: mat.define-palette(mat.$pink-palette, A200, A100, A400);

$my-theme: mat.define-light-theme((
 color: (
   primary: $my-primary,
   accent: $my-accent,
 ),
 typography: mat.define-typography-config(
    $font-family: serif,
  );
));

@include mat.all-component-themes($my-theme);
@include carousel.theme($my-theme);
```

However, this approach doesn't take into account Angular view encapsulation at component level since 'my-carousel' class styles are global after '@include' them in 'styles.scss' file. Therefore, if I use 'my-carousel' CSS class in some HTML element of my application, apart from 'carousel' Angular component, the theming is applied.

Could you provide me with best practices to deal with this scenario?

On the other hand, is it a good practice to use `mat-*` classes in component html? I don't find docs on this, so I guess not.

Thanks in advance to everyone!

### Affected documentation page

https://material.angular.io/guide/theming-your-components

**Comment by JGSolutions** [comment]
i 'm curious about this too

**Comment by amysorto** [comment]
There is more info in our [theming guide](https://material.angular.io/guide/theming#theming-and-style-encapsulation) about this, but yes theme files are assumed to loaded as global CSS which is why other components are able to use styles from `_carousel_theme.scss`. As far as I know something like that isn't formally supported, but you can make your styles more specific (you could even use the carousel component selector name in the CSS rule). 

I would advise against creating any custom components that have a `mat-*` prefix. It will make it harder for you to separate what is your code versus the library code. In some cases you might even the same name which would likely cause issues.
