### ISSUE TITLE
bug(MatChipGrid): Mat Chip Input includes its own styling which overwrite custom styles

### ISSUE THREAD

**Issue by jakemraz20** [angular/components#28265]
### Is this a regression?

- Unsure

### Description

I am working with a matChipInput and once added, it added its own styling which made the cursor blue and shifted it slightly. I should be able to have a simple matChipInput which will not overwrite my input styling.

![AnuZswTPB3iaeiw](https://github.com/angular/components/assets/38114304/13ff4515-d6a8-4795-8a6b-59ad7f6532c3)

### Reproduction

Create a mat chip grid and an associated input with the following line
 [matChipInputFor]="chipGrid" where chipGrid is the mat chip grid which will be associated with this input.

### Expected Behavior

A regular non-styled cursor

### Actual Behavior

a blue and shifted styled cursor

### Environment

Angular material on Chrome on Mac

**Comment by crisbeto** [comment]
The chip input is intended to be used within a Material context so that's why it includes Material styles. You may be able to clear the styling by adding `[class.mat-mdc-input-element]="false" [class.mdc-text-field__input]="false"` to it, but it would be at your own risk. Closing since this isn't something we officially support.
