### ISSUE TITLE
Bug with Angular Material Icon

### ISSUE THREAD

**Issue by ZsirosBen** [angular/components#28312]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

Hi, some google icon is not visible if I put them in a mat-icon tag
for example I can use 'home' icon but I can't use 'destruction','infrared'  and 'Motionsensor urgent' - icons

Do you know anything about this?

### Reproduction

https://stackblitz.com/edit/components-issue-kujppp?file=src%2Fapp%2Fexample-component.html

### Expected Behavior

It should be visible.

### Actual Behavior

I do not see the destruction icon

### Environment

- Angular: 13.3
- CDK/Material: 13.3
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

**Comment by json-derulo** [comment]
It doesn't work because those icons are not part of the Material Icons font.

https://fonts.google.com/icons?icon.query=destruction&icon.set=Material+Icons
https://fonts.google.com/icons?icon.query=infrared&icon.set=Material+Icons

Maybe you are looking for support of Material Symbols? This is a new icon font by Google which is not officially supported by Angular yet. See #24845.

**Comment by ZsirosBen** [comment]
Hi,

Yes! Sorry I was not aware of this.. 

Thanks for your answer!

Happy Holidays!!
