### ISSUE TITLE
bug(Dialog): The browser's focus is set to an element that is not contained in the Dialog box.

### ISSUE THREAD

**Issue by AStrelkov** [angular/components#28327]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

In my _Dialog_ control I have two buttons _OK_ and _Cancel_, that have _tabindex_ properties equal **1** and **2** accordingly. When I press _TAB_ key several times, the browser focus leaves the Dialog container to an element that lies below _cdk-overlay-container_.  When I remove _tabindex_ properties from the buttons,  program works as expected.

### Reproduction

StackBlitz link: https://stackblitz.com/edit/jpj3f8?file=src%2Fexample%2Fcdk-dialog-overview-example-dialog.html
Steps to reproduce:
1.  Add _tabindex_ properties to all controls with values other then '0'.
2. Press _TAB_ key several times.
3. Browser focus changed to an element that is not a child of the Dialog container

### Expected Behavior

Browser cursor must not leave the borders of the Dialog container

### Actual Behavior

Browser cursor leaves the borders of the Dialog container

### Environment

- Angular: **17.0.6**
- CDK/Material: **17.0.4**
- Browser(s): **Microsoft Edge**
- Operating System (e.g. Windows, macOS, Ubuntu): **Windows 11**

**Comment by crisbeto** [comment]
It's because the focus trap around the dialog works with two elements that have `tabindex="0"`. [In general it isn't recommended](https://adrianroselli.com/2014/11/dont-use-tabindex-greater-than-0.html) to set the tabindex to anything besides 0 and -1. You can fix this on your end by removing the `tabindex` from the buttons and setting the `cdkFocusInitial` attribute on the button you want to receive the initial focus.

**Comment by crisbeto** [comment]
I'm closing the issue, because as the focus trap is set up right now, we can't do much about it. It'll be fixed automatically when we switch to using `inert` https://github.com/angular/components/issues/24868.
