### ISSUE TITLE
bug(mat-option): mat-mdc-option-active assigned to the first option when nothing is selected

### ISSUE THREAD

**Issue by kristinakononovich** [angular/components#28562]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

When select doesn't have a value the first option in the dropdown has `mat-mdc-option-active` class and is highlighted. It stays highlighted while you scroll through and hover over other options:
<img width="397" alt="Screenshot 2024-02-08 at 2 53 17 PM" src="https://github.com/angular/components/assets/24557584/c1c37447-781a-483f-9157-d2b4af2db77a">

On this screenshot the mouse is hovering over option 3:
<img width="439" alt="Screenshot 2024-02-08 at 2 53 05 PM" src="https://github.com/angular/components/assets/24557584/1030c7d4-1a92-472a-9a2b-66b4cdd475fa">

### Reproduction

Can be seen here: https://material.angular.io/components/select/examples

### Expected Behavior

If nothing is selected no options should be marked as active.

### Actual Behavior

When element has no value the first option is marked as active.

### Environment

- Angular: 17.1.2
- CDK/Material: 17.1.2
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): macOS

**Comment by crisbeto** [comment]
The `mat-mdc-option-active` class shows where the focus is. It's working as expected since the first option receives focus when the dropdown is opened and nothing is selected.

**Comment by Jacobra93** [comment]
Hey @crisbeto, it makes sense that the first item receives focus initially since we just open the menu. However, it does seem odd that it remains highlighted when hovering over other options. Could this be something we could fix?

You can see in this w3 example that it highlights the first item initially, but removes the focus when others are hovered:
https://www.w3.org/WAI/ARIA/apg/patterns/menu-button/examples/menu-button-actions/
