### ISSUE TITLE
bug(CdkStepper): form less linear CdkStepper.next() doesn't switch to next step

### ISSUE THREAD

**Issue by noguespi** [angular/components#28620]
### Description

Once a step has been marked completed using `CdkStep.completed` input, using the `CdkStepper.next()` doesn't move to the next step, I have to click two times on the button.

If I mark the step using `@ViewChild` and the CdkStep completed setter, it works as expected.

### Reproduction

StackBlitz link: https://stackblitz.com/edit/components-issue-fakctk?file=src%2Fapp%2Fstepper-test.component.ts
Steps to reproduce:
1. click next via binding, nothing happens.
2. click a second time on next via binding, the stepper switch to next step.

### Expected Behavior

When I complete the step and call CdkStepper.next, it should display the next step

### Actual Behavior

When I complete the step and call CdkStepper.next nothing happens the first time.

### Environment

- Angular: 17.2
- CDK/Material: 17.2
- Browser(s): Chrome

**Comment by crisbeto** [comment]
The `nextViaBinding` doesn't work in your example, because Angular doesn't have time to evaluate the data binding between when you set `this.completed` and when you call `stepper.next`. The component just doesn't know that the value has changed yet. You would either have to add `this.cdr.detectChanges();` after changing `this.completed` or do it directly on the step like in `nextViaViewChild`. Here's a working example: https://stackblitz.com/edit/components-issue-g94v2c?file=src%2Fapp%2Fstepper-test.component.ts
