### ISSUE TITLE
bug(theme): promlem with css var calculation

### ISSUE THREAD

**Issue by feichin-noreja** [angular/components#28621]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

If i define a css var with the value of a css var like in the code snippet below some material css variables are not defined correctly.
E.g. --mdc-linear-progress-track-color is set to `var(--primary-500)` but should be converted to a rgba color with 0,25 opacity.

That causes the theme to have some bad behaviour.

`:root{
  --primary-500: #FF0000
}

$primary:(
  500: var(--primary-500)
)
`

### Reproduction

StackBlitz link: https://stackblitz.com/edit/stackblitz-starters-d9ccxk

### Expected Behavior

The css var should be handled like a hex value

### Actual Behavior

The css var is copied

### Environment

- Angular: 17.2
- CDK/Material: 17.2
- Browser(s): Edge
- Operating System (e.g. Windows, macOS, Ubuntu): Windows 11

**Comment by Blafasel3** [comment]
Upvote, I experienced this today when updating to material v16 as well. Really annoying in combination with https://github.com/angular/components/issues/26056#issuecomment-1954744221, because of this bug I have to hard copy values out of my custom palette in order to fix the aforementioned bug. Workaround inception which gets really hard to maintain.

**Comment by crisbeto** [comment]
Palettes based on CSS variables were never supported, see https://github.com/angular/components/issues/25981#issuecomment-1325334683. Instead of creating a palette with CSS variables that are initialized to colors, you can pass those colors directly to the palette and it'll create variables for you. This specific case can also be worked around with `.mdc-linear-progress__buffer-bar { opacity: 0.25 }`, but there's no guarantee other places won't have a similar issue.

**Comment by feichin-noreja** [comment]
@crisbeto can you update the https://material.angular.io/guide/theming page so that is clear that the Palettes dont "understand" css vars?

The better solution for us would be if the material theme supported css variables.
