### ISSUE TITLE
bug(cdk/overlay): Overlay is still visible outside the scrollable container

### ISSUE THREAD

**Issue by 27790635** [angular/components#28647]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

When we have an overlay attached to an element in a scrollable container, it moves out of the container as we scroll.

### Reproduction

StackBlitz link: https://stackblitz.com/edit/components-issue-3yjw2j?file=src%2Fapp%2Fexample-component.ts
Steps to reproduce:
1. Click inside the input, and then the overlay should be visible.
2. Scroll inside the red container
3. You can see that the overlay is visible outside the red container.

### Expected Behavior

The overlay shouldn't be visible when it's outside the container.

### Actual Behavior

The overlay can be visible outside the container

### Environment

- Angular:  17.1
- CDK/Material: 17.1
- Browser(s): Safari 17.3.1, Edge 122, Chrome 122
- Operating System (e.g. Windows, macOS, Ubuntu): Windows, macOS

**Comment by crisbeto** [comment]
The overlay won't close when clipped automatically, because that doesn't make sense for all use cases, however it does provide the necessary information if you want to do it yourself. Here's an updated Stackblitz showing how to do it: https://stackblitz.com/edit/components-issue-tmw9dy?file=src%2Fapp%2Fexample-component.ts,src%2Fapp%2Fmaterial-module.ts
