### ISSUE TITLE
feat(MatSelectHarness): Allow harnesses to be extended

### ISSUE THREAD

**Issue by undsoft** [angular/components#28690]
### Feature Description

It would be helpful if `private` fields were replaced with `protected` fields in `MatSelectHarness` and other harnesses.

I understand that you generally don't want to make things `protected` if they are not extended in the codebase, but I think it would make life easier for the consumers.

### Use Case

We have html code for tooltips in some of our select options. It gets parsed when calling `getOptions[0].getText()`.
Previously I could just extend the harness and override `_optionClass` to get a custom behaviour for `getText()`. After version 17 this is no longer possible and I need to reimplement more things.

**Comment by amysorto** [comment]
It seems that the change from this PR: https://github.com/angular/components/pull/27632.

I assume these methods are not meant to be overrriden since it's based on the material select component and how it works, and your component would unlikely be changing that. It isn't clear to me why getText() should be overridden, as opposed to making your own function for your case (ex, getTooltipText()). If you can provide more context for overridding please open this issue again. Thanks!
