### ISSUE TITLE
youtube-player: initial image to improve load performance is not loading and we she broken video image

### ISSUE THREAD

**Issue by mattiLeBlanc** [angular/components#28697]
### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

https://github.com/angular/components/pull/28207

### Description

<img width="1726" alt="image" src="https://github.com/angular/components/assets/5285035/c5aae0e5-ea40-4544-877a-cc10994b429c">

In the feature requests (https://github.com/angular/components/pull/28207) an image with a loading button was put in front of the youtube iframe to improve loading speed.
However, we have more and more video's  displaying a loading error on that background image.
The youtube video reference is XKdBeRE5E9A and when you embed the iframe directly, it shows a correct image.
I am not sure why this image is loaded https://i.ytimg.com/vi_webp/XKdBeRE5E9A/sddefault.webp 404 (Not Found) since it doesn't seem to exist.

### Reproduction

StackBlitz link: 
Add angular youtube player:
```
<youtube-player videoId="XKdBeRE5E9A" ></youtube-player>
```

### Expected Behavior

If image can not be retrieved, do not show this broken video image but maybe just load the youtube iframe?

### Actual Behavior

When failing to get the cover image, it shows a broken video image with play button. This is not pretty behaviour.

### Environment

- Angular: 17.2
- CDK/Material: 17.2
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): MacOs latest

**Comment by crisbeto** [comment]
This is covered under the "Placeholder image quality" section in the docs: https://github.com/angular/components/tree/main/src/youtube-player#placeholder-image-quality. Unfortunately we don't have a way of knowing ahead of time what quality of image will be available so it needs to be set manually. If you want to get the old behavior back, you can also disable the placeholder.

**Comment by mattiLeBlanc** [comment]
@crisbeto okay. But in some cases the image is not available at all. But other video's do have images. If that is the case, then the placeholder function is not very useful, right?
We don't control the youtube videos on our platform.

So I guess, disabling the placeholder is the only way then.

**Comment by crisbeto** [comment]
At least when I was experimenting, all the videos I tried had at least a low-quality placeholder. But yes, unfortunately we can't do anything to handle this better internally within the component since YouTube doesn't expose what's available. If you want to disable the placeholder for the entire app, you can use the `YOUTUBE_PLAYER_CONFIG` injection token at the root of the app.

**Comment by crisbeto** [comment]
I was considering that when I was setting up the placeholder, but I decided not to because the user would see a flash between the grey 404 image and the fallback image when we swap it out. I think another approach to this might be to have an input that allows users to specify the placeholder image themselves.
