### ISSUE TITLE
Google cloud style sidebar

### ISSUE THREAD

**Issue by mr-zgaya** [angular/components#28693]
### Feature Description
I haven't found any component that is like google cloud sidenav menu. Is there any plan about this.

![Uploading Screenshot 2024-03-07 at 12.51.04 AM.png…]()

**Comment by amysorto** [comment]
The material components follow Material design, Google cloud does not since they have their own design system. The screenshot does not show up for me, so I cannot see the specifics of what you are referring to. Although I assume most likely not since that is outside of our scope. Feel free to open a new issue more specifics!
