### ISSUE TITLE
docs(form-field): the example for the mat-error is using a function call in template

### ISSUE THREAD

**Issue by mpricu** [angular/components#28732]
### Documentation Feedback

The example for the form field mat-error is using a function call in the template: 
 @if (email.invalid) {
      <mat-error>{{getErrorMessage()}}</mat-error>
    }
Best practices mentions to avoid using function calls in templates, but the documentation contains this example since the Material version 5. After all, is it correct using a function call in template for the mat-error?

### Affected documentation page

https://material.angular.io/components/form-field/overview#error-messages

**Comment by mmalerba** [comment]
Its not always bad to call a function in your template, but if you call a function in a template it will be re-evaluated every time change detection runs. This can be problematic depending on how much work the function is doing and what kind of side effects it has. In this case the function is doing very little work so its probably fine. That said I've created https://github.com/angular/components/pull/28748 to change it since its not a pattern people should carelessly copy without understanding the implications.
