### ISSUE TITLE
bug(cdk/drag-drop): cdk classes are not applied when drag item is created using DragDrop service

### ISSUE THREAD

**Issue by chintankavathia** [angular/components#28821]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

I am not sure if this is intended but when we create the drag item using `createDrag` method of `DragDrop` service. cdk classes like `cdk-drag`, `cdk-drag-dragging` etc don't get applied to element.

### Reproduction

StackBlitz link: 
Steps to reproduce:
1.  inject DragDrop service in a component
2. use `createDrag` of the DragDrop service to convert any element of the component into cdkDrag item
3. observe that cdk drag specific classes on that element are not present.

### Expected Behavior

cdkDrag specific classes should be applied to element just like when we use cdkDrag directive on that element.

### Actual Behavior

cdkDrag specific classes are missing on drag element.

### Environment

- Angular: 17
- CDK/Material: 17
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Mac

**Comment by crisbeto** [comment]
This is working as expected since the classes are tied to the directives. You can see how they're added if you want to include them in your own directive: https://github.com/angular/components/blob/main/src/cdk/drag-drop/directives/drag.ts#L73. Another option would be to toggle them in the `started` and `ended` events.
