### ISSUE TITLE
bug(COMPONENT): Unexpected Behavior with Number Input and MatTooltip Scrolling

### ISSUE THREAD

**Issue by armellarcier** [angular/components#29074]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

In Angular Material, when a with matInput is used, the expected behavior is that scrolling over this input field scrolls the page. However, if I hover over any element with MatTooltip, then focus back on the number input field, the scrolling behavior unexpectedly changes. Instead of scrolling the page, it increments or decrements the number in the input. This issue can also occur on the Angular Material official [website](https://v11.material.angular.io/components/tooltip/overview).

![image](https://github.com/angular/components/assets/1194274/eb1a9a3c-70d4-40f2-a029-9986384023a7)

This is not the expected behavior : https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/number

### Reproduction

StackBlitz link: https://stackblitz.com/angular/porobbapdry?file=src%2Fapp%2Ftooltip-delay-example.ts
Steps to reproduce:
1. Navigate to a page with a with matInput.
2. Hover over an element with MatTooltip.
3. Focus on the number input field.
4. Try scrolling over the number input field.

### Expected Behavior

The expected and consistent user experience is that scrolling over a number input field should scroll the page, not change the input's value. This unexpected behavior disrupts the user experience, especially in forms with tooltips and number inputs.

### Actual Behavior

When a field with matInput is focused, and the user scrolls with the mouse wheel, the default behavior is for the page itself to scroll, not the number in the input field. However, this behavior changes after interacting with an element that has MatTooltip. Specifically, after hovering over a MatTooltip element and then focusing on the number input field, scrolling with the mouse wheel no longer scrolls the page. Instead, it changes the value in the number input field, incrementing or decrementing it. This is inconsistent with the expected behavior and occurs even on the Angular Material official website.

### Environment

- Angular: 16
- CDK/Material: 16
- Browser(s): Chrome
- Operating System Windows + macOS + ArchLinux

**Comment by ChristophWieske** [comment]
The issue comes from the wheel event that the tooltip uses to get a proper trigger to hide again. However there is an issue with the wheel event in chromium: https://issues.chromium.org/issues/334994023

Last info from the chromium team was: Won´t Fix.
I attached a test page to show the issue.

I think there are two ways how we could solve it for us:

1. After hiding the tooltip we remove all the handlers that are attached to trigger hiding (and reattach when shown again)
--> The user would still experience the changed behavior while the toolip is open (due to delay or when it is attached directly to the input)

2. We add a wheel handler on matInput[type=number] per default
--> The behavior would consistently stay increment/decrement

(Firefox always shows increment/decrement behavior)
