### ISSUE TITLE
bug(Drag and Drop): Drag scroll problem with scrollable element that are not body

### ISSUE THREAD

**Issue by TommyKila** [angular/components#29161]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

the scrollable element inside body does not scroll when im dragging the draggable element to the top or bottom of scrollable and when i use mousewheel to manually scroll, the drop indicator does not follow

### Reproduction

StackBlitz link: https://stackblitz.com/edit/u7z1ur-nutg2j?file=package.json
Steps to reproduce:
1. make the body element unscrollable
2. have an element inside body that scrollable and have a cdkDropList and Draggable element inside that element

### Expected Behavior

the scrollable element inside body should scroll when im dragging the draggable element

### Actual Behavior

the scrollable element inside body does not scroll and when i use mousewheel to manually scroll, the drop indicator does not follow

### Environment

- Angular:
- CDK/Material:
- Browser(s):
- Operating System (e.g. Windows, macOS, Ubuntu):

**Comment by crisbeto** [comment]
You need to indicate which elements are scrollable using the `cdkScrollable` directive. Here's a working example: https://stackblitz.com/edit/u7z1ur-eysxmd?file=src%2Fexample%2Fcdk-drag-drop-custom-placeholder-example.ts

Note that I had to use `hostDirectives` here since the root component was scrollable. If it was a regular component, you can just add the `cdkScrollable` attribute to it instead.
