### ISSUE TITLE
bug(menu): mat-icon misaligned if used within ng-container

### ISSUE THREAD

**Issue by madmurl0c** [angular/components#29185]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

mat-icon is not aligned correctly when used inside an ng-container

### Reproduction

StackBlitz link: https://stackblitz.com/edit/hk7kbz
Steps to reproduce:
1. Open the menu

### Expected Behavior

mat-icon should be aligned correctly

### Actual Behavior

mat-icon is misaligned

### Environment

- Angular: 18.0.1
- CDK/Material: 18.0.1
- Browser(s): Edge 125.0.2535.67
- Operating System (e.g. Windows, macOS, Ubuntu): Windows 10

**Comment by crisbeto** [comment]
Closing since this is how change detection works. The `ng-content` slot matching `mat-icon` won't pick up the icons since they're inside the `ng-container`. You have a few options to work around it:
1. Add `matMenuItemIcon` to the `ng-container`.
2. Add `ngProjectAs="mat-icon"` to the `ng-container`.
3. Use the new `@switch` syntax which should project the icons properly.

Here's an example of the first approach: https://stackblitz.com/edit/hk7kbz-npr4vu?file=src%2Fexample%2Fmenu-icons-example.html
