### ISSUE TITLE
bug(mat-optgroup): using @if block directly in a mat-optgroup results in all mat-options rendered inside of the group label

### ISSUE THREAD

**Issue by dkarbayev** [angular/components#29493]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

The bug is reproducible both in mat-select and mat-autocomplete.

If I wrap the `mat-optgroup`'s content in `<ng-container *ngIf="...">`, the `mat-autocomplete` is rendered properly.

### Reproduction

StackBlitz link: https://stackblitz.com/edit/sfwhbx?file=src%2Fexample%2Fautocomplete-optgroup-example.html
Steps to reproduce:
1. Go to https://material.angular.io/components/autocomplete/overview#option-groups
2. Open the example in Stackblitz
3. Open autocomplete-optgroup-example.html
4. Locate <mat-optgroup>
5. Wrap its immediate content with `@if(true) {...}` block
6. Check the autocomplete dropdown - all options are now narrower because they're rendered inside of the option group label's `span` element

### Expected Behavior

`mat-option` elements should be rendered after `span.mat-mdc-optgroup-label` as siblings.

### Actual Behavior

`mat-option` elements are rendered as descendants of `span.mat-mdc-optgroup-label`.

### Environment

- Angular: 18.0.1
- CDK/Material: 18.1.2
- Browser(s): Chrome 127.0.6533.57
- Operating System (e.g. Windows, macOS, Ubuntu): macOS 14.5 (Sonoma)

**Comment by crisbeto** [comment]
It's a valid issue, but I'm closing it because we can't do much about it. Content projection with the new control flow only works on the root node. E.g. in the example the root node of `@for` is `mat-option` so the framework knows where it needs to be projected. When you add an `@if`, the `@if` becomes the new root node so it gets projected into the catch-all `ng-content`, rather than the one for `mat-option`.
