### ISSUE TITLE
feat(mat-card): mat-card-image does not follow M3 specs

### ISSUE THREAD

**Issue by shimonsalamon** [angular/components#29505]
### Feature Description

The mat-card-image should be updated to follow the Material 3 specifications. Specifically, the image should have a border radius and be positioned on top of the card.

https://m3.material.io/components/cards/guidelines#da988650-d826-4939-9902-5b0670050462

![image](https://github.com/user-attachments/assets/fa37066e-5dad-4c7f-9ef2-e2bc348c1f73)

**Comment by amysorto** [comment]
The specs don't mention images in cards explictly: https://m3.material.io/components/cards/specs. On that guidelines tabs of the M3 docs, there are examples of images that have different bottom border radiuses for images as well.

The `mat-card` component is [meant to be composable with its different directives](https://material.angular.io/components/card/api#material-card-directives). There is a `MatCardImage` directive that is meant to represent the primary image for that card. If placed first within `mat-card`, the top corners have the same border radius as the card.

![Image](https://github.com/user-attachments/assets/87190b31-d48b-4619-a3df-0129be399710)

The bottom corners do not get changed. Since it isn't technically in the specs, I will close this issue. Although you can change this for your application with custom styles.
