### ISSUE TITLE
bug(core-theming): get-theme-color($theme, $role-color) returns incorrect shades for 4 colors

### ISSUE THREAD

**Issue by vulture9** [angular/components#29577]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

For the given function get-theme-color($theme, $role-color) four of the shades are incorrectly mapped:
Light mode:
- surface . Current implementation is using n-98 , where should be mapped to n-99.

dark mode:
- surface . Currently using n-10, where should be mapped to n-6.
- on-surface-variant Currently using nv-80 , where should be mapped to nv-90
- surface-container-highest  Currently using n-22, where should be mapped to n-24.

reference to comparison material theme builder: 
https://material-foundation.github.io/material-theme-builder/
![image](https://github.com/user-attachments/assets/a24c1e4e-f3d6-4bc1-8ebd-f08fb14f967d)
![image](https://github.com/user-attachments/assets/58caf1ea-6122-4d04-851f-b1e51dc67453)

Tested version:
 "@angular/material": "18.1.0",

### Reproduction

Steps to reproduce:
1.  call get-theme-color($theme, role-color) for role colors 'surface', 'on-surface-variant', 'surface-container-highest'
2. compare shades of colors from the pallet that are returned. wrong shades are used according to spec

### Expected Behavior

correct shades are returned based on the specification. reproduction steps are very clear.

### Actual Behavior

slightly wrong color shades are returned than on specification. just compare whatever is here for given mode light/dark mode and you can clearly see that wrong shades are used

### Environment

- Angular: 18.1.0
- CDK/Material: 18.1.0
- Browser(s): all, browser independent
- Operating System (e.g. Windows, macOS, Ubuntu): Mac and Windows

**Comment by amysorto** [comment]
Good catch, thanks for pointing this out!

As mentioned above, the current [colors are mapped incorrectly](https://github.com/angular/components/blob/main/src/material/core/tokens/m3/definitions/_md-sys-color.scss#L111). The rest should be audited as well:

- (Light theme) `surface` maps to neutral 99 instead of neutral 98
- (Dark theme) `surface` maps to neutral 10 instead of neutral 6
- (Dark theme)  `on-surface-variant` maps to neutral 80 instead of 90
- (Dark theme)  `surface-container-highest` maps to neutral 22 instead of 24
