### ISSUE TITLE
bug(mat-table): Mouse with double wheel - vertical scroll suspended

### ISSUE THREAD

**Issue by aszafran-sintra** [angular/components#29753]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

When using a mouse with two scroll wheels (e.g., Logitech Master 3s), there is an issue with scroll suspension. After scrolling horizontally using the horizontal wheel, the vertical wheel doesn't work when trying to scroll vertically. The table occupies the full height, so there is no vertical scroll bar in the table.

### Reproduction

StackBlitz link: 
Steps to reproduce:
1. 
2.

### Expected Behavior

Table container should scroll verticaly.

### Actual Behavior

The vertical scroll is suspended after horizontal scrolling.

### Environment

- Angular:16.1.7
- CDK/Material:16.1.7
- Browser(s):Chrome 128.0.6613.138
- Operating System (e.g. Windows, macOS, Ubuntu): Windows 11 Home

**Comment by sOnU1002** [comment]
Event Handling Adjustment: Ensure that the scroll events are properly propagated. Override the default scroll behavior of the mat-table to accommodate both horizontal and vertical scrolling.

typescript

import { Component, HostListener } from '@angular/core';

@Component({
  selector: 'app-your-table',
  templateUrl: './your-table.component.html',
  styleUrls: ['./your-table.component.css']
})
export class YourTableComponent {

  @HostListener('wheel', ['$event'])
  onWheel(event: WheelEvent) {
    if (event.deltaY !== 0) {
      // Allow vertical scrolling
      event.preventDefault();
    }
  }
}
CSS Adjustments: Ensure that your table and its container are correctly styled to support overflow. The table should allow for vertical scrolling.

css

.table-container {
  height: 100%;
  overflow-y: auto; /* Allow vertical scrolling */
  overflow-x: hidden; /* Hide horizontal scrollbar */
}
Horizontal Scroll Implementation: When scrolling horizontally, ensure that the scroll event is correctly captured and does not interfere with vertical scrolling.


@HostListener('wheel', ['$event'])
onWheel(event: WheelEvent) {
  if (event.deltaX !== 0) {
    // Allow horizontal scrolling
    this.tableContainer.nativeElement.scrollLeft += event.deltaX;
    event.preventDefault(); // Prevent default scrolling
  } else if (event.deltaY !== 0) {
    // Allow vertical scrolling
    this.tableContainer.nativeElement.scrollTop += event.deltaY;
    event.preventDefault(); // Prevent default scrolling
  }
}
Testing: After implementing the above changes, test the functionality:

Ensure that both horizontal and vertical scrolling work seamlessly.
Check the behavior across different browsers and devices to confirm the fix is effective.

**Comment by crisbeto** [comment]
Closing since this is likely an issue on your end. We don't do anything special with the table's `oveflow`.
