### ISSUE TITLE
bug(material/progress-bar): mat-progress-bar not displaying in mat-option

### ISSUE THREAD

**Issue by sdedieu** [angular/components#29866]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

Putting a mat-progress-bar inside of a mat-option won't display.

### Reproduction

StackBlitz link: https://stackblitz.com/edit/s6vpnq?file=src%2Fexample%2Fselect-overview-example.html,src%2Fexample%2Fselect-overview-example.ts
Steps to reproduce:
1. Open the select dropdown

### Expected Behavior

I expect to have a progress bar inside each mat-option.

### Actual Behavior

mat-progress-bar does not display

### Environment

- Angular: 19.0.0-next.2
- CDK/Material: 19.0.0-next.2
- Browser(s): Chrome, Firefox
- Operating System (e.g. Windows, macOS, Ubuntu): macOS

Note: The issue is also present in cdk/material 15.x.x, 18.x.x, ... as it is not a regression or due to a preview version.

**Comment by alvaromartmart** [comment]
The problem seems to be that the `mat-progress-bar` doesn't grow to fill the parent `.mdc-list-item__primary-text`, which is the direct child of the _flex_ `mat-option` container.
Some possible solutions:
- Override `.mdc-list-item__primary-text` to have `flex-basis: 100%`
- Do you need the `mat-progress-bar` to be a child of an actual `mat-option`? Is it to indicate that you're loading the options? Because in that case it could be simply a child of `ma-select`

**Comment by sdedieu** [comment]
I'd go with the second solution. Works like a charm. Thanks.
