### ISSUE TITLE
mat-error not displayed in a @for loop

### ISSUE THREAD

**Issue by legrandjerome** [angular/components#29887]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

Using a @for loop a single <mat-error> is not displayer in the template.

Adding a <ng-container> or another tag arounds made it works.

### Reproduction

StackBlitz link: https://stackblitz.com/edit/m3msso?file=src%2Fexample%2Fform-field-error-example.html
Steps to reproduce:
1. launch the link
2. error should be present but it's not
3. add extra tag around the for loop or inside 
4. error message is present

### Expected Behavior

Error messages should be present without extra tag.

### Actual Behavior

Error message is not present.

### Environment

- Angular: 19.0.0-next.2
- CDK/Material: 19.0.0-next.2
- Browser(s): Chrome Version 129.0.6668.90 (Build officiel) (64 bits)
- Operating System (e.g. Windows, macOS, Ubuntu): Windows 11 Professionnel

**Comment by crisbeto** [comment]
The error doesn't show up when the page loads, because by default errors are shown only after the user has interacted, e.g. either on `blur` or when the parent form is submitted. These are the docs if you want to change the default behavior: https://material.angular.io/components/input/overview#changing-when-error-messages-are-shown

https://github.com/user-attachments/assets/20f517cc-c55b-4058-8fb5-75b341acdf70
