### ISSUE TITLE
Angular material components don't show tooltips if they are in disabled state

### ISSUE THREAD

**Issue by Muqhees** [angular/components#29962]
### Is this a regression?

- [x] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

14

### Description

Tooltips for some Angular components like mat-button and mat-checkbox do not work if they are in a disabled state whereas it works for other components like mat-menu-item

Also tooltips work for basic html elements like button work even if they are in disabled state. Wanted to get more insight on this If this is a bug or expected behavior. In latest versions tooltip behavior for disabled elements is inconsistent for different components and it use to work for all components in version 14

### Reproduction

StackBlitz link: https://stackblitz.com/edit/components-issue-starter-kmkdyn
Steps to reproduce:
1. 
2.

### Expected Behavior

Tooltips should work for disabled state components like mat-button and mat-checkbox

### Actual Behavior

Tooltips don't work for disabled state components like mat-button and mat-checkbox

### Environment

- Angular:
- CDK/Material:
- Browser(s):
- Operating System (e.g. Windows, macOS, Ubuntu):

**Comment by crisbeto** [comment]
It's because browsers don't dispatch events on disabled elements and the tooltip is triggered on `mouseenter`. We have an opt-in input called `disabledInteractive` that switches to using `aria-disabled` and allows tooltips to be triggered. See https://material.angular.io/components/button/overview#interactive-disabled-buttons.
