### ISSUE TITLE
feat(dialog,menu): add input flag to display in a bottom sheet style and animation

### ISSUE THREAD

**Issue by tommyc38** [angular/components#30233]
### Feature Description

Maybe I am missing something but I have never understood why the Bottom Sheet component exists and why this isn't a flag for a Dialog or Menu?  It would be WAY more consumable to simply throw a flag on a Menu or Dialog that displays the contents in the same style as the Bottom Sheet component does.

### Use Case

The use case behind Bottom Sheet is for a mobile friendly view for dialogs and menus. Right now, you basically needto manage a Dialog/Menu component AND a Bottom Sheet component with the same content to give a streamlined web vs mobile experience.  Rather than managing a Bottom Sheet component, it would be far more intuitive, require less boilerplate, and reduce duplication to simply have a flag that determines how the Dialog/Menu should be displayed.  It should handle nested menus such that a new "Bottom Sheet" pages over the parent sheet with back arrows, etc.

**Comment by crisbeto** [comment]
The reasons why we have a separate bottom sheet, rather than combine it with the dialog are:
1. There can only be one bottom sheet open at a time, whereas dialogs can be stacked.
2. The animation for bottom sheets is different.
3. The layout of the bottom sheet is different depending on the screen size.
