### ISSUE TITLE
Add hint text (and group-level hint text?) for radio buttons, checkboxes, and slide toggles

### ISSUE THREAD

**Issue by natsid** [angular/components#3370]
#### Bug, feature request, or proposal:
Feature request to add add hint text beneath checkboxes and radio buttons that mimic that under text inputs.

In addition, group level hint text would be a plus. Same as hint text, only it applies to a group of associated selection controls. This seems especially reasonable for a radio button group.

Something like this: http://plnkr.co/edit/HhN7ykzp0oM07IGyy4a3?p=preview

#### What is the current behavior?
Currently, you can give labels to these selection controls, but no hint text.

#### What is the use-case or motivation for changing an existing behavior?
While it's possible now to add text beneath these controls, it would be nice for the hint text to be associated with the selection control it qualifies so that it can do things like line up with the label text, obey the width of its associated control/label, etc.

#### Is there anything else we should know?
I would be happy to contribute this feature, if it's something Material is interested in including.

**Comment by jelbourn** [comment]
We've gotten this request a handful of times over the years, but we still don't have any plans to support this since it isn't captured in the Material Design spec. While we sometimes do deviate from the spec for specific reasons (e.g. a11y), this is a case where we don't feel confident enough in the UX to move forward.
