### ISSUE TITLE
[Tooltip] Tooltip does not position correctly with long message

### ISSUE THREAD

**Issue by impankratov** [angular/components#3721]
#### Bug, feature request, or proposal:
bug

#### What is the expected behavior?
Tooltip should be positioned to the left of the md-fab button

#### What is the current behavior?
Tooltip overlaps the fab button:
![0103d24c-0f2b-11e7-8d6f-b288502cb5f5](https://cloud.githubusercontent.com/assets/6479407/24199444/59f41d4e-0f2b-11e7-9490-77587472cb1e.png)

#### What are the steps to reproduce?

Tried to create fixed md-fab button in the right bottom corner:
https://plnkr.co/edit/gkr0cO

#### Is there anything else we should know?

If I change `mdTooltipPosition="left"` to `mdTooltipPosition="above"` - tooltips will be positioned correctly.
Shorter tooltip messages are working correctly.

**Comment by Goodwine** [comment]
I had to add a css rule that sets a max width to the tooltip text and makes it break into several lines, it worked really well but it's fragile and may not work for you :(

**Comment by impankratov** [comment]
@Goodwine sounds interesting, maybe we can use this to make a PR? Can you share the code?

**Comment by Goodwine** [comment]
I don't think the CSS changes would work for everyone, it's very hacky. In fact, per the material guide, the tooltip shouldn't be that long to begin with.

If you really want to do this hack, you could update your stylesheets and set custom rules on `.mat-tooltip` like a `max-width` that works for you and whether you want to show an ellipsis on the text, or reset `height` so that it can grow vertically.

Again, those things go against the material guide, so be mindful of that.

**Comment by kpaxton** [comment]
This is related to #2671 and I just commented on that one that this doesn't work. The tooltip already has a max-width property set based on the outcome of that ticket. It needs to perform the way the MatMenu does and reposition itself.

**Comment by jelbourn** [comment]
I tried this with the latest version and AFAICT the behavior seems correct, seems to have been fixed since this issue was reported
https://stackblitz.com/edit/angular-xp2yxk?file=src%2Fapp%2Ftooltip-auto-hide-example.html
