### ISSUE TITLE
md-menu can't set max-width

### ISSUE THREAD

**Issue by ninaneter** [angular/components#4462]
Bug

I'm trying to override the default 280px max-width of the `.mat-menu-panel
` but it doesn't work.

 [Plunker example](https://plnkr.co/edit/cBCcW6vAkNQto5gjeoEt?p=preview)

i'm using the latest 2.0.0-beta.3 cesium-cephalopod version, with chrome browser

**Comment by willshowell** [comment]
First, in your plunker, your stylesheet isn't being included in the component. You must add the stylesheet to `styleUrls`.

Second, unfortunately you won't be able to override the menu panel with your component styles due to [view encapsulation](https://angular.io/docs/ts/latest/guide/component-styles.html#!#view-encapsulation). You will need to either turn view encapsulation off for this component or add the override styles to your global stylesheet.

Third, in order to actually override the styles on `.mat-menu-panel`, you'll need to either use `!important` or increase your [specificity](https://developer.mozilla.org/en-US/docs/Web/CSS/Specificity) by using multiple selectors, like `.mat-menu-panel.my-overriden-menu`.

https://plnkr.co/edit/iJH8g9y3wEyXQEPSiJ4C?p=preview

All that having been said, menu width should be more easily adjustable. The spec claims that it must be an increment of 56px, but the 280px max is only for mobile screens.

**Comment by ninaneter** [comment]
Thank you!
I've improved my example to better describe my problem. Now the toggle button is aligned to the right and the menu panel gets cut.
If I use `.cdk-overlay-container .mat-menu-panel` instead of `.cdk-overlay-container .mat-menu-panel.my-menu` as the css selector, it works. But I want to apply it only with my specific `.my-menu` class.

It seems like the menu-panel is being positioned before `my-menu` class is added.

[here is the code](https://plnkr.co/edit/cBCcW6vAkNQto5gjeoEt?p=preview)

**Comment by willshowell** [comment]
Due to the css specificity rules, 2 classes of specificity are required. You don't need `.cdk-overlay-container`, you can do `.mat-menu-panel.my-menu` instead. 

But I certainly see the issue with the positioning and can't come up with workaround for it. #2584 could maybe one day be of help, but I agree that changing menu/select width and subsequent repositioning should be supported!

**Comment by galki** [comment]
There's a [question on stackoverflow](https://stackoverflow.com/questions/45841459/md-menu-override-default-max-width-in-angular-2) for this. My question is what is the [panelClass](https://material.angular.io/components/menu/api#MatMenu) property for? Couldn't make it work.

**Comment by crisbeto** [comment]
Closing since this looks like an issue on your end. Either you've put the override inside a view-encapsulated component which prevents the style from being applied to the menu, or the specificity of your style is too low.
