### ISSUE TITLE
[Tabs] Md-tab-group renders another component's view only on first md-tab

### ISSUE THREAD

**Issue by firel246** [angular/components#5505]
#### Bug, feature request, or proposal:
Only first md-tab renders a component's view. 

#### What is the expected behavior?
To render component 'my-calendars' on tab1 and component 'rooms-equipment' on tab2.

#### What is the current behavior?

Only the first component(my-calendars) is rendered. Second tab doesn't render anything unless it's plain text. Rooms-equipments do render correctly if they are put in **first** md-tab.

#### What are the steps to reproduce?

```
<md-tab-group>
    <md-tab label="My calendars">
        <my-calendars> </my-calendars>
    </md-tab>
    <md-tab label="Rooms">
         some_text //rendered
        <rooms-equipments> </rooms-equipments> //not rendered
    </md-tab>
</md-tab-group>

```
  Materials version: "2.0.0-beta.7-b00f838",

**Comment by julianobrasil** [comment]
@firel246, at first sight it seems like a bug in your app to me. Do you manange to reproduce it in a plunker? Without more information, there's a great chance that your issue is classified as a bug in your custom components, not in the tab component (and, if this is the case, you should try asking for help in other services, like stackoverflow.com).

The tab works as expected in some projects of mine (and in some cases I have a lot of custom components inside the tabs).

**Comment by firel246** [comment]
@julianobrasil I don't see why it would render properly when on first tab but not on second at all. I'd surely agree it's problem in my app if these components wouldn't render at all. I have shown you all the code I use, except for the components, but I don't think it is needed as they do work properly.

**Comment by julianobrasil** [comment]
I have already saw some issues relating to tab-group component (actually there's one open right now pointing that nested tab-groups has a problem to render the inner tab-group: #5503). The point is that there must be something particular to your `<rooms-equipments>` (ok, not necessarily a bug in your app 😃) that is preventing it from being rendered in the second tab.

Right now the code you pasted above is not enough to track it down without the details of what is inside your component (if I replace <rooms-equipments> by others components, for example, input, datepicker it'll probably work). Try to build a plunker gradually, inserting simillar components until the problems occurs, than post it here.

**Comment by mmalerba** [comment]
@firel246 please provide a plunker or additional information so we can reproduce

**Comment by andrewseguin** [comment]
Hey @firel246, I'd love to help out but we don't have enough information about what the error is. Do you see anything show up in your console that might help point to why it is not being rendered?

Feel free to re-open with more information. A plunker with reproduction would be best since it allows us to track exactly what the problem is.

**Comment by fgNv** [comment]
I'm facing this issue as well, maybe this plunkr can help:
http://plnkr.co/edit/mSHD7mC6IhY6PGKh7RhA?p=preview

The first tab renders the expanders panels correctly, but the second doesn't.

**Comment by fgNv** [comment]
one possible workaround:

http://plnkr.co/edit/Pi6ON6f6HEEghZE2O712?p=preview

**Comment by julianobrasil** [comment]
Dupe: #5269?

**Comment by mmalerba** [comment]
Confirmed that this work in v15 [stackblitz.com/edit/angular-pmsgwg](https://stackblitz.com/edit/angular-pmsgwg)
