### ISSUE TITLE
cdk-table visual explanation

### ISSUE THREAD

**Issue by 3sanket3** [angular/components#8968]
#### Bug, feature request, or proposal:
proposal

#### What is the expected behavior?
The [cdk-table](https://material.angular.io/cdk/table/overview) looks very flexible and useful. But when I try to get into its implementation details it seems very much confusing to understand the whole data-flow and template rendering.

I read the doc and also tried to refer the code many times, but I think its a visual explanation in form of a chart would be more helpful.

Maybe it's a silly requirement from a beginner, but if anyone can just guide me to the existing material available for the same on web, that would also be a great help.

Thank you

**Comment by 3sanket3** [comment]
Was just wondering, the other users, when they were newcomer, they must also have faced the issue. Did they just refer the code, it's comment and gets the whole idea? :flushed: Any tips, how should take it up, before some detailed guide available?

**Comment by Charius** [comment]
@3sanket3 Hi there! Did you look at https://material.angular.io/guide/cdk-table ?

**Comment by 3sanket3** [comment]
Yes, @Charius .  Anyway thanks for looking into.

But I think, I need to first properly understand the concepts of Attribute and Structure directive and their dynamic loading using ViewContainer, TemplateRef, and ElementRef. Clearing those concept, I  think I am slowly getting into it.

**Comment by jelbourn** [comment]
The doc here does assume knowledge of certain Angular concepts like `ng-template` and structural directives, which I think are best covered via angular.io. Recently https://angular.io/guide/content-projection#conditional-content-projection was created which I think helps a bit with this. 

Closing since I don't think we would create any sort of diagram for the table, but feel free to open a new issue if there are specific parts of the table overview that don't adequately explain what a specific part of the table API does.
