### ISSUE TITLE
Datepicker format not working in Stackblitz demo

### ISSUE THREAD

**Issue by d-damien** [angular/components#9780]
#### Bug, feature request, or proposal:
Formatting configuration for datepicker seems to be completely ignored. Uses only american `M/D/Y` format. Reading the [documentation](https://material.angular.io/components/datepicker/overview#choosing-a-date-implementation-and-date-format-settings) (note : anchor # does not work), it seems like it uses only native date and not moment.js.

#### What is the expected behavior?
Being able to change (at least) display format from MY_FORMATS variable.

#### What is the current behavior?
It does not appear to work in official demo.

#### What are the steps to reproduce?
Official demo : https://stackblitz.com/angular/gopooxxyykl

Import MatMomentDateModule in `main.ts` :
``` ts
import { MatMomentDateModule } from '@angular/material-moment-adapter'
@NgModule({
    imports: [ ... MatMomentDateModule, ...]
```
Change `MY_FORMATS.display.dateInput` variable in `app/datepicker-formats-example.ts` :
``` ts
dateInput: 'Y-MM-DD HH:mm:ss'
```
Reload the inner browser on the right.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Demo says 5.2.3, 5.0.0-rc.3, LinuxMint 18.1 with Chromium 64.0.3282.119.
tsc 1.7.5 & webpack 3.6.0 on my computer.

**Comment by d-damien** [comment]
After some tests, it appears to be SystemJS causing the trouble, as it accepts `moment.js` imports as
``` ts
import moment from 'moment'
```
while they should be
``` ts
import * as moment from 'moment'
```
which `tsc` (+ `webpack`) tolerates.

**Comment by d-damien** [comment]
It is to be noted that while SystemJS does not throw error with the former, it does not work.

**Comment by mmalerba** [comment]
appears to work when the example is embedded in the docs site, but not in the stackblitz

**Comment by mmalerba** [comment]
Looked into this a little more, it's actually not an issue with how moment is being imported. For some reason the datepicker is picking up the `NativeDateAdapter` provided by the module instead of the `MomentDateAdapter` provided on the demo component. This is really strange because if I inject `DateAdapter` in the demo component it is indeed the `MomentDateAdapter`.

**Comment by WizardPC** [comment]
I'm not sure to understand everything but the code sample from the documentation will work in a real environment (= not inside stackblitz) ?

**Comment by willwsharp** [comment]
Any new information on this issue?

**Comment by mmalerba** [comment]
This feels like either a StackBlitz or Angular core issue to me. I put a breakpoint on the `MatDatepickerInput` and verified that the `NativeDateAdapter` is still being injected. Strangely if I inject the `DateAdapter` in the demo component I get the `MomentDateAdapter` I would expect. Here's a slightly modified StackBlitz with instructions on how to observe the discrepancy: https://stackblitz.com/edit/angular-akrakp?file=app/datepicker-formats-example.html

@chuckjaz Any idea what's going on in this StackBlitz?

**Comment by EricSimons** [comment]
Creator of stackblitz here- I think this might have to do with with the module resolution strategy stackblitz employs vs local CLI. Specifically, for performance reasons stackblitz will consume UMD bundles whenever possible instead of the raw untranspiled individual files specified by the `module` field/etc. This can cause some differences in runtime behavior between SB and local. I haven't had enough time to dig into the specific culprit in this instance, but my prelim research is kinda pointing in that direction.

Will circle back once I've tracked this bug down 👍

**Comment by Wykks** [comment]
Also, if you load `MatMomentDateModule`  instead of `MatNativeDateModule` in the demo, the formating is a little bit different ('Su' instead of 'S', and so on).

Not sure why it change because `MatMomentDateModule` is just a shortcut to the two `provide` (https://github.com/angular/material2/blob/master/src/material-moment-adapter/adapter/index.ts)

**Comment by pfeigl** [comment]
@mmalerba Isn't the comment from @Wykks  the problem? The stackblitz referenced here imports the MatNativDateModule, which has this:
```
  providers: [
    {provide: DateAdapter, useClass: NativeDateAdapter},
  ],
```
which probably conflicts somehow with the custom registration done in the component.

As soon as the `MatMomentDateModule` is imported the `MatDatepickerInput` actually gets the correct `MomentDateAdapter` just as expected.

**Comment by mmalerba** [comment]
@pfeigl it should work even with that. The one provided on the component should override the one provided on the module.

The way our examples are set up now its hard to change the modules imports on a per-example basis, which is why its this way in the first place. We should change our examples to be more flexible, and then we could fix this particular example, but this behavior is still strange...

**Comment by GitStorageOne** [comment]
Not sure if it my fault, but in local project i get same problem.
I use reactive forms and code below:

```ts
this.userFormGroup = this.formBuilder.group({
    // some controls ...
    // date
    create_date: [{ value: moment([2017, 0, 1]), disabled: true }],
});
```

Template:

```html
<mat-form-field class="full-width">
  <mat-label>Caption</mat-label>
  <input matInput formControlName="create_date" [matDatepicker]="createDate" autocomplete="off">
  <mat-datepicker #createDate></mat-datepicker>
</mat-form-field>
```

**Comment by akshaybhat30** [comment]
> ```ts
> export const CUSTOM_DATE_FORMATS = {
>   parse: {
>     dateInput: 'LL'
>   },
>   display: {
>     dateInput: 'LL, dddd',
>     monthYearLabel: 'MMM YYYY',
>     dateA11yLabel: 'LL',
>     monthYearA11yLabel: 'MMMM YYYY'
>   },
> };
> ```

This worked for me :) thanks

**Comment by mmalerba** [comment]
This has been fixed, it works in the latest version of the stackblitz: https://stackblitz.com/angular/pxxppbbllrqb?file=src%2Fapp%2Fdatepicker-formats-example.ts
